### ISSUE TITLE
Multiple tabs opening - generator

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#154]
Seems to be opening 2 identical tabs, when clicking through on a generated number?

(also, not related, but I often find when you've chosen a country from the front page of d-portal, and then go back, you have to hit back twice)

**Comment by Mattdevinit** [comment]
This one still happens for me, eg generating a table of content on the generator http://www.d-portal.org/ctrack.html?#view=generator page and then clicking on a cell within the generated table below, opens up 2 identical new tabs.  Using Firefox v41.0

**Comment by notshi** [comment]
Have updated a bunch of files and removed unnecessary hyperlinks - hopefully this is now fixed on Firefox.
