### ISSUE TITLE
Write up of processes/rules that we apply once taking from datastore

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#158]
Something fairly simple, to explain everything that we do, like 

Using Disbursements and Expenditure
Using transaction value date when transaction date not present
etc

This has been requested recently ("Could you give me more information about the queries procedures applied to the XML files information?  I mean, which are the XML elements or attributes evaluated and how are the statistics prepared.") and I think is something good to clarify and publish on the site, as I'm sure more will ask.  

Could be part of an FAQ doc?

**Comment by notshi** [comment]
Does this apply to the current FAQ docs? If so, current wip - http://d-portal.org/faq.html
