### ISSUE TITLE
Link with open contracting

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#160]
to enable drilling down from a single project to related contracts

**Comment by robredpath** [comment]
This has come up this week as part of traceability. There's no central registry of Open Contracting data, but it could be possible to display a link between an IATI Activity and an open contract if the data contains the link. @timgdavies what're the ways of linking the two in the data?

**Comment by timgdavies** [comment]
There are proposals in the 2.03 for way of making the connection - but no structured data approach in any of the current data. 

This might be something to look at once 2.03 is out and we have some potential test-cases from DFID.

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
