### ISSUE TITLE
Traceability module

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#164]
So that when viewing an activity you can choose to view all the linked/related activities in that chain - so that one day we can use this to see the whole chain of aid from donor to end recipient (and everything in between)

**Comment by robredpath** [comment]
Z&Z are doing a load of work in this area. We may be able to just link out to their portal @VincentVW

**Comment by notshi** [comment]
@robredpath - how is work coming along with Z&Z?

**Comment by notshi** [comment]
https://aidperspective.org/app/

**Comment by VincentVW** [comment]
It doesn't seem to be in there indeed. Will check if I can find any of my old jsfiddles that show basic visualisations of this that can be used for inspiration. 
The logic for it was deducted from the DGIS guidelines and can be found here; https://github.com/zimmerman-zimmerman/OIPA/blob/master/OIPA/traceability/retrieve_chains.py#L139

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
