### ISSUE TITLE
Show type of org in generator

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#171]
Interest from Bond in being able to select in the generator 'org type' to allow them to view for example all NGOs together

**Comment by k8hughes** [comment]
How hard would it be to have the option in step one on this page to select by org type attribute?
http://www.d-portal.org/ctrack.html#view=generator
If it wasn't too work, it would be interesting for a user to be able to see for eg all "foundations" working in X country.

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
