### ISSUE TITLE
CRS 2013 updating

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#172]
Bringing in new data from CRS relating to 2013, and replacing 2012 columns with 2013 IATI and CRS data, updating charts etc.  Documenting process and noting other areas that need changing (eg text on front/about pages, etc referring to 2012 data).  Also check anything needing doing for this on generator.

**Comment by Mattdevinit** [comment]
This data is now available in this DAC table http://stats.oecd.org/Index.aspx?DataSetCode=TABLE2a

@xriss - can you remember last time whether you pulled the info from this table, or whether it was provided to you already (i.e every donor for every country, from this table)?  Once we get that, we can go ahead with updating the CRS data, moving everything on a year in the table, and amending any relevant text.

**Comment by xriss** [comment]
I think we got the original data via email, so will take a look at pulling this down hopefully its all using exactly the same names as that's the only bit that may be problematic.

**Comment by Mattdevinit** [comment]
Great - thanks, let me know if there's any issues on that

**Comment by xriss** [comment]
Do you have any experience with using this?

It seems to have lots of options but I couldn't find a way of getting data out in any format similar to this compact table...

https://docs.google.com/spreadsheet/ccc?key=0AmauX4JNk0rJdHRWY1dRTkQ3dXJaeDk4RFZFWElaSHc#gid=3

Mostly it seems to want to provide one table per donor, rather than a donors x recipients table.

So far all I've really managed to do is download a 270mb CSV file...

**Comment by xriss** [comment]
2013 CRS data is now live and the IATI data has been moved forward a year.

Would appreciate any reports of places where it looks broken.

Possibly we may need to update some of the other mapping tables but its looking good to me so far.

**Comment by Mattdevinit** [comment]
We've done a random check on 20 or so publishers/countries, and haven't found any issues through that or through general usage since Thursday - so looking good, thanks!

**Comment by caprenter** [comment]
@xriss I'm interested to know how the problem of getting the data into the format similar to the compact table was solved.

Can you shed any light on how it was done pls?

**Comment by bill-anderson** [comment]
@caprenter I had a complete set of CRS 2013 data (manually downloaded by DI - 270 MB) and ran a couple of pivot tables on it

**Comment by xriss** [comment]
The CRS 2013 spreadsheets provided by @bill-anderson are available at https://docs.google.com/spreadsheet/ccc?key=0AmauX4JNk0rJdHRWY1dRTkQ3dXJaeDk4RFZFWElaSHc#gid=14 along with all the other data we use.
