### ISSUE TITLE
Upgrading to 2.01

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#173]
Preparing d-portal for data published to 2.01 of the IATI Standard - including using test publisher data to be provided in early November

**Comment by Mattdevinit** [comment]
First 2.01 data has been published, by Hewlett http://d-portal.org/ctrack.html?publisher=US-EIN-941655673&tongue=eng#view=publisher
Mostly looks ok in d-portal, which is great.  There's a sectors issue but that's not related to 2.01 and has been raised with them.
One small issue related to 2.01 changes is that <narrative> is now a child field within 'title' and 'description'.  This is new on 2.01, so at the moment d-portal is treating this as text, hence each of the individual activities includes the <narrative> and </narrative> tags!  Just need a way to deal with that http://d-portal.org/ctrack.html?publisher=US-EIN-941655673&tongue=eng#view=act&aid=US-EIN-941655673-33793

**Comment by xriss** [comment]
Strange that was one of the things I thought I fixed... Its down to <title> having a special (I think?) sub tag rule in html, I thought it was fixed by changing the tag to <span-title> . Will take a look again.

**Comment by notshi** [comment]
I believe this should all be okay now, unless someone spots a problem :}
