### ISSUE TITLE
Column sorting in tables (budgets, in publisher view)

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#190]
Two different methods of sorting, depending on whether you click the actual text (eg 2015) or elsewhere in that box - and neither currently sorting correctly high to low!

**Comment by Mattdevinit** [comment]
(don't think there's two different methods depending on where you click in the cell) but when sorting by clicking in the '2015' and '2016' cells (and if moving on further into the future), eg in this table http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=publisher_countries
seems to be sorting alphabetically in some cases rather than high to low?  this only seems to happen in the budget columns, in publisher view tables

**Comment by notshi** [comment]
@Mattdevinit  Before this gets fixed, can we confirm the logic behind sorting?

For sorting the top most column header (IATI Budget / Spend):

- Sort by the highest of the Spend or the highest of the Budgets; ie. If column 2013 has highest spend, that gets higher priority, followed by next highest year column to the lowest. This may be confusing unless explicitly noted in the table notes/legend in the footer. Currently, there are no notes about sorting there.

or

- Sort by total of all three year columns so the highest (2013-2015) total will sit at the top of the table; bottom part of table will mostly be made of 0, 0, 0 columns, followed by negative numbers under those.

Keep in mind that rows with 0s in all columns will be randomly sorted.

**Comment by Mattdevinit** [comment]
closing this as it was fixed when we did https://github.com/devinit/D-Portal/issues/273
