### ISSUE TITLE
Message for empty 2014 pie charts

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#191]
Now that we are showing IATI 2014 data only in the pie charts, some publishers have empty spaces where the chart would be (as they are not publishing 2014 data).  They may be publishing data for others years (eg Germany) so we need a clear message where the pie chart would have been, directing users to click through as there may be other data for the publisher...eg

No 2014 data found - however there is data for this publisher for other years, please click here to explore further

**Comment by Mattdevinit** [comment]
This is still relevant for some publishers eg http://d-portal.org/ctrack.html?publisher=US-501c3-522318905&tongue=eng#view=publisher
so worth still putting this note up on pie charts

**Comment by notshi** [comment]
Yes.

**Comment by notshi** [comment]
We now show all years for pie charts and if data is missing, we do not display the charts.
