### ISSUE TITLE
US data - activities missing

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#216]
From this page http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=donor_activities&funder=US clicking on activities gives the message "This activity is missing or cannot be found." - there's issues with their N/A reporting, but that's not specifically why that is giving this message I don't think?  Do we know the reason in this instance?

**Comment by notshi** [comment]
Am classifying this as bad data examples as you shouldn't have terribly long ids like that in the first place.
