### ISSUE TITLE
Option to select currency

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#219]
Add in the option to select which currency you view in.  eg a dropdown on main page for (at least)
GBP
Euro
USD
(with indication of which currency the data was originally published in).

This for each page of d-portal, and a button on the generator.

**Comment by Mattdevinit** [comment]
looks good!  just adding some notes having had an initial poke round...

Quite a few revert to USD, presumably because they are obsolete and there's no data for the exchange rate date we are using (what is the date?) - can remove these from the list please

Portuguese Escudo
Austrian Schilling
Belgian franc
Deutsche mark
Kroon
Spanish peseta
Finnish markka
French franc
Italian lira
Luxembourg franc
Maltese lira
Netherlands guilder
venezuelan bolizar

**Comment by Mattdevinit** [comment]
I think there is a change in denomination for some currencies (when going from USD to these, the amounts get significantly smaller rather than larger) - into billions? (or it's not that the conversion is being done the opposite way round?).  Includes

Colombian peso
Indonesian Rupiah
Philippines peso
uruguayan peso
chile peso

**Comment by Mattdevinit** [comment]
When choosing a different currency, and then a different language, the currency defers to the default USD when selecting the language

**Comment by xriss** [comment]
Yup missing currency data.

I thinks its best if we add more exchange rate columns into

https://docs.google.com/spreadsheet/ccc?key=0AmauX4JNk0rJdHRWY1dRTkQ3dXJaeDk4RFZFWElaSHc#gid=13

for any currencies we have no other data on. This table is where I get approximate exchange rates as a fall back for currencies *not* in the IMF data.

I see it's missing french francs, FRF which is strange I thought we had that one, probably best to add it.

**Comment by Mattdevinit** [comment]
Some currency codes on pie charts remain as 'USD' after changing - in this case only in the recipient countries chart, whereas it's fine in the sectors one (eg showing 'CAD') http://d-portal.org/ctrack.html?publisher=CA-3&usd=CAD#view=publisher

**Comment by notshi** [comment]
Sorry, was a typo. Should be fixed now.

**Comment by Mattdevinit** [comment]
Thanks Shi!

**Comment by Mattdevinit** [comment]
re currencies in list...
I don't think we really need those missing currencies (as listed above) as they all stopped being used years ago?  I can delete them from ctrack (just delete the rows?) if so

and can we then choose which currencies to add to the dropdown, from the other (exchange) tab as and when required?

**Comment by Mattdevinit** [comment]
Updated list of currencies on ctrack
