### ISSUE TITLE
Individual recipient country financial year dates

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#221]
Interested to know your thoughts on how this might be done/how long it could take?  Would be great to do, having got this direct feedback from people in our target audience (via Wendy!)

"some of the partner countries were thinking about how they could use d-portal to compare the IATI data with what is provided to them locally by the donor local offices. However, in order to easily compare the data they would ideally need the annual data to be displayed in line with their financial or reporting year. Eg Nepal would want to specify that their financial year runs from jun 6 to jun5 and then the annual data to be calculated and displayed accordingly for that time span"

**Comment by xriss** [comment]
This is now in with a simple drop down, needs to be made pretty but you can play with it and see if the numbers seem to be coming out right.

There will of course be problems with placing budgets into the right year if they span the transition date from one year to the next. (it uses the budget end date)

**Comment by Mattdevinit** [comment]
thanks - will have a play around!
