### ISSUE TITLE
Location rules

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#223]
@latitude and @longitude deprecated since 1.04

http://iatistandard.org/activity-standard/iati-activities/iati-activity/location/coordinates/

include pos

http://iatistandard.org/activity-standard/iati-activities/iati-activity/location/point/pos/

**Comment by Mattdevinit** [comment]
looks good, thanks - noticed that the heat aspects here aren't clickable http://d-portal.org/ctrack.html?publisher=GB-1&tongue=eng#view=publisher
and http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=publisher 
http://d-portal.org/ctrack.html?publisher=44000&tongue=eng#view=publisher

I think (?) previously these included options for clicking through, on the main page?

**Comment by xriss** [comment]
The Heat Maps? Click the view all button to get a map with clickable pins.
