### ISSUE TITLE
Heights options - Savi window

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#225]
Could we add the options for certain heights, when choosing Savi in the generator - we got part of the way to sorting this before Christmas, and would be great to get these in place (to support Bond and VSO in using it).  
This can be done any time asap - should fit ok with the current remaining days we have - thanks

**Comment by xriss** [comment]
Added a drop down to optionally limit the height as well as the box to type in values, let me know if you want more values added or removed from it.

**Comment by notshi** [comment]
Fixed the layout issues with this.
