### ISSUE TITLE
Update document on Generator options with links to examples

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#228]

**Comment by notshi** [comment]
Yes, I'm mostly referring to this - https://github.com/devinit/D-Portal/blob/master/documents/ctrack_generator.md

Terribly out of date if you compare to the live site. And yes, definitely needs to link to that blog post :}

**Comment by Mattdevinit** [comment]
ah i see!  gonna do a big push on documentation and writing up some of our processes soon, and hopefully putting together as part of an FAQ

**Comment by notshi** [comment]
Sounds good!

**Comment by notshi** [comment]
add to documentation - detailed and specific guidance on SAVi queries

https://github.com/devinit/D-Portal/issues/263
