### ISSUE TITLE
Unique URLs for generator searches

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#229]
Was just trying to generate a table of all UN data, then use the part of the generated code to paste as a URL.  Think there were some fixes to do on this (removing spaces?)

<iframe scrolling="no" src="http://www.d-portal.org/ctrack.html?publisher=411124,41120,41111,41122,41114,41127,41AAA,41119,41140&amp;#view=frame&amp;frame=publisher_countries&amp;size=960" style="width: 960px; height: 10369px;" frameborder="0"></iframe> 

Also, how long would it take to generate these as separate URLs in the address bar once the selections had been made in the generator?  Might be very useful in helping others use the generator

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
