### ISSUE TITLE
Export savi to excel

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#230]
User request on whether this is a possiblity - interested to know how long this would take.  At the moment you can link through to the registry and get a CSV from there, but only gives you the whole of that activity file, which is usually much larger than one single activity.

**Comment by xriss** [comment]
Which bits? I think all the big tables have a CSV download option.

**Comment by notshi** [comment]
Q already does that. We've got a few examples listed on the About page (http://d-portal.org/about.html#que)  from when the site was first built but we haven't actually given it the focus it deserves.

Currently, you can get csv like so -
http://d-portal.org/q.csv?from=trans&aid=GB-1-201935-105

There are fields that need to be worked on and so forth (human-readable dates etc.), but in general, the data you see in there is the data used in d-portal (not SAVi).

What would you like to see in the CSV view?

**Comment by notshi** [comment]
xml to csv
