### ISSUE TITLE
xml links

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#231]
not sure if we've had something like this before (vaguely rings a bell) - just looking at a Canada project 
http://d-portal.org/ctrack.html?publisher=CA-3&usd=CAD#view=act&publisher=CA-3&lat=20.5&lng=1

and then going to view source http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=CA-3-D000047001

**Comment by notshi** [comment]
Sorry, possibly not understanding the question.

Do you mean the XML link next to the words, "VIEW SOURCE" (under the Project Title) on the SAVi link you sent?

**Comment by Mattdevinit** [comment]
yes - that's the one.  when i try the first link above it doesn't seem to work - but it's a savi arrived at from going through the Canada map http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=map&lat=27.297547242250154&lng=-3.0750000000000455&zoom=6

was just wondering why there wasn't much in the xml (I was going to see if the location data was point/pos or not)

**Comment by notshi** [comment]
Looks like the Datastore has failed to import it.

The information shows up on the Registry link.

**Comment by Mattdevinit** [comment]
ah ok, great - thanks

**Comment by Mattdevinit** [comment]
@Bjwebb @stevieflow do you have know why the datastore isn't importing in this instance (maybe others)?  eg this is a Canada DFATD activity http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=CA-3-D000047001

**Comment by stevieflow** [comment]
you mean this one?

http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=act&aid=CA-3-D000047001

**Comment by Bjwebb** [comment]
Not had chance to investigate this yet, but I think this is the same issue that @markbrough reported https://github.com/IATI/iati-datastore/issues/211

**Comment by notshi** [comment]
Closing as not relevant anymore.
