### ISSUE TITLE
dropdown list searches

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#233]
On the d-portal front page...
I guess this is linked to #186 in that if you search for 'Germany' or 'Canada' there you don't get results, whereas they appear in the list below on the front page.  But it's maybe because of the mismatch of names in the dropdown, and the actual list on this page - eg if you type 'bmz' in the search, you get Germany but it's under the name bmz.  

The correct way round to fix this is to have the dropdown list of names (I think this is the names from the Registry, as opposed to the names in the data itself?) matching the list already existing further down on the front page.  This is already how the publisher dropdown list is on the generator, so just needs unifying across the site.

On the generator dropdown (publishers)
This works really well, only thing I think is that a search for 'DFID' gets no results, as in the org name in the list it is '(DFID)'.  Is it easy to ignore brackets in the searching process?  see #208

**Comment by notshi** [comment]
Use the same one as Generator.

**Comment by xriss** [comment]
I think this is now fixed, or at least changed :)

The front page now populates both lists from live data and uses the names from the registry for both.

Currently this exposes a bad publisher ID of 47134 (I think it should be 47135) at the top of the list due to the alphabetical sort.

**Comment by Mattdevinit** [comment]
thanks - starting to take shape!!  a couple of thoughts

the non-dropdown list of publishers on front page is duplicated completely I think (starts again after 'sacu')
will need to look at how to address the bad data that's showing up some org ids (there's a couple of XM-DACs and a few others) - although it's a problem with the data, it looks like it reflects badly on d-portal, I might need to do something on that.
there's about 10 names that start with lowercase letters, can these be put in the alphabetical list (in the right place)?

**Comment by Mattdevinit** [comment]
and on the publisher full list on front page, stretch the names further across that column maybe?  and limit the actual IDs there to one line

**Comment by xriss** [comment]
I've hidden the bad data here as well and fixed the other bits.

Only publishers with published data using their correct IDs will show up...

**Comment by notshi** [comment]
Have changed the layout of the list now and rearranged where the dropdown is along with the wording, just in case people can't see it above the "Compare all" buttons and that you can lookup searches by typing, instead of just selecting.
