### ISSUE TITLE
Relationship between sector pie charts and subsequent tables (publisher view) 

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#234]
not sure if there's any link with #193 
looking at the pie chart of sectors for Canada, http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=publisher
the top two sectors (material relief assistance & services, and emergency food aid) don't feature in the subsequent table http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=publisher_sectors - and similarly with the fourth highest on the pie chart.

It's not the case for all publishers, but another example is the top sector for EC DEVCO (general budget support) http://d-portal.org/ctrack.html?publisher=EU&tongue=eng#view=publisher
is not on the subsequent table http://d-portal.org/ctrack.html?publisher=EU&tongue=eng#view=publisher_sectors

Any thoughts on this?  There might be an obvious reason that I'm just not seeing?

**Comment by notshi** [comment]
You're right. That's strange, will have a look. Might have something to do with Sector groupings.

**Comment by notshi** [comment]
Bug fixed - leftover code where lists were limited to 100.
