### ISSUE TITLE
Changes to currency list

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#235]
I made a few changes (removed some, added a couple from 'exchange' tab, and changed the order) last week to the list of currency countries in the 'IMF Currencies' tab - but they haven't come through on the site, just checking I've not done something wrong?

**Comment by notshi** [comment]
Hi Matt,

I've just republished the site. Is it better now?

**Comment by Mattdevinit** [comment]
yes - great, thanks Shi!

**Comment by Mattdevinit** [comment]
hi - could you re-do this please?  I just found out it's being demo'd at UN foundation tomorrow to lots of partner country people, so have added the currencies of those we know are going...thanks
warning ... one of the currencies is quite long, and includes accents!  Communauté Financière Africaine Franc

**Comment by notshi** [comment]
yup, sure thing.

**Comment by Mattdevinit** [comment]
thanks - i can see them in the dropdown list, but haven't got any of them to work yet when selecting them - just stays on USD?  they look like they are in the ctrack 'exchange' tab?  (i've marked up which ones it is in the 'IMF currencies' tab) - thanks

**Comment by xriss** [comment]
I was still fixing it, sorry, should be there now?

**Comment by Mattdevinit** [comment]
oh sorry!  yes, looks great - thank you very much!
