### ISSUE TITLE
Zaire - country code

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#236]
This African Dev Bank activity has ZR as the recipient country code http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=46002-P-ZR-BA0-001 and the description in the xml is 'ex Zaire'.  

The recipient country appears as 'Zaire' on savi http://d-portal.org/ctrack.html?publisher=46002&tongue=eng#view=act&aid=46002-P-ZR-BA0-001 but can't see that or ZR as a country code on ctrack, is there somewhere else to look for the list of country codes we're using (ZR is not an active code any more)?

**Comment by xriss** [comment]
There is no public version of ISO_3166 available, there used to be but now it is all hidden behind a pay wall.

So the codes/names are scraped from http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 including old/expired IE as much data as possible.

We could switch to another table in the google docs if you want more control but this is where the names are coming from.

**Comment by notshi** [comment]
Country code being used in the above examples is ZRCD, which is invalid?

**Comment by Mattdevinit** [comment]
As these are technically valid for projects in the past when this country code was valid, use in addition the codes from here http://en.wikipedia.org/wiki/ISO_3166-3

**Comment by robredpath** [comment]
The UK government is now maintaining a country register at https://country.register.gov.uk/ (currently in alpha) that might be of use. They also welcome feedback from people who do or could use the register to find out about needs/concerns etc

**Comment by notshi** [comment]
Thanks, @andylolz - thing is, we're holding out for as long as we can until it becomes unbearable - then see which of these services still exists. And then make a decision.
