### ISSUE TITLE
Missing projects - criteria

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#237]
It would be useful to clarify how activities are determined as having "missing dates", as a number listed for AfDB, for example, do have dates...

http://d-portal.org/ctrack.html?publisher=46002&tongue=eng#view=missing

**Comment by xriss** [comment]
Invalid data might be a better term its either missing/invalid dates or they started some time after they ended.

**Comment by Mattdevinit** [comment]
whereabouts does it says missing dates?  we should change where it does, as you say the term is misleading if dates do exist - but it's 'missing projects' on a country/publisher home page (as in, missing from the charts on that page)?

**Comment by stevieflow** [comment]
Ah yes, my mistake - invalid dates is not the label.  It's just that for AfDB this was the reason, I think.

**Comment by Mattdevinit** [comment]
added to list - for updating documentation (add explanation of what counts as a 'missing project')
