### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#238]
Locations seems off for the main maps in the few examples I looked, namely:

1. Afghanistan - http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=main
2. Bangladesh - http://d-portal.org/ctrack.html?country=BD&tongue=eng#view=main
3. Honduras - http://d-portal.org/ctrack.html?country=HN&tongue=eng#view=main

Can't find any new updates from Google Maps API blog or issue tracker to suggest changes that might cause this.

Could this be part of the recent `<pos></pos>` inclusion?

**Comment by stevieflow** [comment]
Something seems to be amiss with IADB data: http://d-portal.org/ctrack.html?publisher=IADB&tongue=eng#view=map

I've done some random checks, and in some cases the latlong seems to be fine: http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=IADB-AR-L1033 ...

**Comment by notshi** [comment]
Thanks, @stevieflow . I found that the data is fine. It's our end that's rendering badly and it was from the recent `<pos></pos>` inclusion on our end where @xriss got the lat/lng backwards.

Have changed it the right way round but will need to check and see if that fixes it after a proper update.

**Comment by stevieflow** [comment]
Great to hear, thanks @notshi

**Comment by notshi** [comment]
Looks like this has been fixed.
