### ISSUE TITLE
Working with recipient-region activities

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#239]
Hi

Just a query, but how does d-portal deal with activities that _only_ have a `recipient-region` value?

I cant see a region list, alongside the country list, for example.

**Comment by Mattdevinit** [comment]
We were talking about this just recently - they aren't included in the country breakdown, but we were considering if it's feasible to apportion them to countries within that region...not sure how to go about weighting per country etc though, even if this is a good idea.  A region list in the meantime might be a better solution

**Comment by stevieflow** [comment]
Remember - the purpose of ``recipient-country`` and ``recipient-region`` in IATI is to describe where the activity takes place.  

eg: 

- activity A takes place in country B
or 
- activity C takes place in region D

In 1.0x the two should not be mixed.  If you know about country B, then there is no need to report the region.  Most certainly, the two should not be used to declare that country B *is in* region D.
 
In 2.01 it's possible to mix country and region, but that is also applicable to where the activity is taking place, not in terms of expressing a relationship

Hence, it would probably be unwise to try and apportion regions into countries, or vice versa

**Comment by Mattdevinit** [comment]
Maybe the best solution is to add the regions in addition to the list of countries at some point (to show activities with region only reported), to ensure all data is shown somewhere whilst avoiding overlap with country data

**Comment by notshi** [comment]
Thanks, @andylolz - at the moment, we ignore regions as we are unsure how to deal with them.

We could display them in SAVi as a first step and then a separate region list filter on the landing page as the next step.

Trivia - dportal was originally called Country Tracker, so only focused on countries!

**Comment by andylolz** [comment]
> at the moment, we ignore regions as we are unsure how to deal with them.

Oh sorry, I realised I should have flagged @stevieflow’s other comment here, too:
https://github.com/IATI/IATI-Extra-Documentation/issues/355#issuecomment-369369209

So for v2.0x, `recipient-country/@percentage` + `recipient-region/@percentage` should equal 100. So to accurately reflect the data, the screenshotted pie chart in Steven’s comment shouldn’t just show `recipient-country` – for v2.0x, it should mix `recipient-country` and `recipient-region`.

**Comment by notshi** [comment]
Thanks, @andylolz.

Yes, we will be treating regions separate to countries but that will come much later.

The ```recipient-region``` element is now being displayed in SAVi and live on d-portal.
![screenshot-20180927155538-924x162](https://user-images.githubusercontent.com/1515961/46155353-007ab400-c26f-11e8-9b0f-f92022d0f584.png)

It supports version 2.01 and above.

@stevieflow Please raise a different issue for ```activity-scope```, thank you!

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
