### ISSUE TITLE
Reword "Make" Tab on the landing site

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#240]
This has gone through a few iterations and it still doesn't quite explain what the link (the Github page)  is for so I've changed it to the current - "Feedback: Send us your thoughts." and linked it direct to the issues page.

Hopefully this makes more sense and send people over. If you have other suggestions, do chirp in. Thanks!

**Comment by Mattdevinit** [comment]
good change!
i think some people might be overawed by immediately going to a github page - maybe there could be a landing page with three big links, like

Email us
Raise Github issues
Join Google group

?

**Comment by notshi** [comment]
I suppose so. Maybe a small popup-like thing with those links as buttons is better than loading a new page.
