### ISSUE TITLE
'Select a recipient country' dropdown

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#241]
on the front page - in this dropdown there's a load of weird codes/descriptions (from bad data) appearing in this list.  can we restrict this dropdown list to just the countries in the full list below it on that page please?

**Comment by xriss** [comment]
hidden the bad data from the front page

**Comment by notshi** [comment]
Really need a disclosure somewhere that states this. D-portal was supposed to show bad data so this seems a little meandering. Maybe we need a "dirty" d-portal version for comparison, possibly Dash can accommodate this!
