### ISSUE TITLE
Multiple latlongs

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#242]
This may be related to https://github.com/devinit/D-Portal/issues/238 - but might be different

How does d-portal deal with activities that have multiple ``location`` elements, each of which has a different latlong?

eg: http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=IADB-AR-L1033

**Comment by xriss** [comment]
It just has multiple locations, same as say multiple countries, so you will have the same activity appearing more than once on a map when looking at activities on a map.

The heatmap will give it a bit more weight than other activities but the heatmap is not very useful as far as data goes anyway, just gives an idea of which locations are reported on.

So it should all be fine.

**Comment by stevieflow** [comment]
ok thanks @xriss for the clarificiation
