### ISSUE TITLE
CRS columns to publishers tables

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#243]
Is it feasible with the current CRS data we use to add in the 'latest CRS' columns to the (obviously only CRS!) publisher tables?

eg to have the CRS column as in this table http://d-portal.org/ctrack.html?country=AR&tongue=eng#view=donors
added to all CRS publisher tables like this one http://d-portal.org/ctrack.html?publisher=US&tongue=eng#view=publisher_countries

**Comment by Mattdevinit** [comment]
@xriss to check if we need additional CRS data

**Comment by xriss** [comment]
This should be in, but remember one CRS publisher may map to multiple IATI publishers.
