### ISSUE TITLE
issues 26 Feb 2015

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#245]
- [x] change recipient country dropdown list to become alphabetical (front page)
- [x] fix Firefox bug which messes up order of publisher dropdown, and publisher full list (front page)
- [ ] remove publishers with 0 activities (publisher dropdown in generator)
- [x] in CSV download from tables, change 'org id' field to 'org name'
- [x] confirm whether current CRS data we have is enough to do #243 
- [x] re #219 when choosing a different currency, and then a different language, the currency defers to the default USD when selecting the language
- [x] removed brackets (in generator publisher dropdown) a search for 'DFID' gets no results, as in the org name in the list it is '(DFID)'. Is it easy to ignore brackets in the searching process?

**Comment by Mattdevinit** [comment]
re Firefox bug on list of publishers on front page - just had a look for something in Internet Explorer, and the list is the same there (so maybe it's me?!)

**Comment by notshi** [comment]
Currency now stays when changing language.
