### ISSUE TITLE
Updating Macedonia

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#246]
@notshi @xriss  I've just added the updated name for Macedonia in ctrack, as that's the only country not showing the CRS data right in the table.  Might need a couple of goes at this, as not 100% sure what the new name is - but could you refresh please and I'll see if this has worked?  Thanks

**Comment by notshi** [comment]
Hi @Mattdevinit , is this what you mean - http://d-portal.org/ctrack.html?country=MK&tongue=eng#view=main

**Comment by notshi** [comment]
Done. Had to remove the brackets in the ctrack spreadsheet for it to work.

**Comment by Mattdevinit** [comment]
great - thanks!
