### ISSUE TITLE
UNFPA - country / sector chart not populated

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#247]
Hi

I noticed that this pie chart is not populated: http://d-portal.org/ctrack.html?publisher=41119#view=publisher

On clicking through, we can see some data for 2013.  Obviously, there is a label on the overview page to say (2014) - but this might need further text/context - could simply be about suggesting people click through....

**Comment by Mattdevinit** [comment]
yep - thanks @stevieflow ... see also #191

**Comment by stevieflow** [comment]
Thanks @Mattdevinit - ok , you are on it.  Closing this as duplicate
