### ISSUE TITLE
UN data not showing

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#249]
From the full list of publishers on front page, if you choose UNOCHA their graphs/tables are empty http://d-portal.org/ctrack.html?publisher=41127&tongue=eng#view=publisher
Not sure if this is something to do with change to org ID I made in ctrack last week (although I think it was showing ok after that)...on the front page the publisher ID for UNOCHA is 41127, which is the old one...maybe there's something else I should have done in ctrack?  Their data seems to show up ok in country view, eg http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=donors

Also, I can't see UNDP (UN development programme) in the list on front page - again it's one that has changed org ID recently, so maybe similar issue?

**Comment by xriss** [comment]
UNOCHA has transactions but none of them are C or D type so nothing to show
http://d-portal.org/q?reporting_ref=41127&select=trans_code&from=trans%2Cact&limit=-1



I think UNDP is missing because of a publisher ID mismatch (so filtered out of the front page)

41114
XM-DAC-41114

so the data exists, but should be using just 41114 according to the registry

http://www.d-portal.org/ctrack.html?publisher=XM-DAC-41114&tongue=eng#view=publisher
http://d-portal.org/ctrack.html?#view=dash_quality&pub=XM-DAC-41114

**Comment by Mattdevinit** [comment]
re OCHA - there's some transaction code '3's (disbursements) in these files from the registry which I checked randomly?
http://fts.unocha.org/api/v2/iati/emergency/id/16424.xml
http://fts.unocha.org/api/v2/iati/emergency/id/16529.xml

**Comment by xriss** [comment]
Bad publisher IDS then?

http://d-portal.org/ctrack.html?#view=dash_quality&pub=41127

only one dataset found, neither of the ones listed which have a reporting org of XM-OCHA-FTS

http://www.d-portal.org/ctrack.html?publisher=XM-OCHA-FTS&tongue=eng#view=publisher
http://d-portal.org/ctrack.html?#view=dash_quality&pub=XM-OCHA-FTS

Again this is filtered from the frontpage.

**Comment by xriss** [comment]
Which reminds me, because of the frontpage filtering you are going to need to go here and do a search (ctrl f) to see what publisher names are in the data.

http://d-portal.org/ctrack.html?#view=dash

and we should include stats of bad reporting IDs on that page (similar to bad countries) as well

**Comment by Mattdevinit** [comment]
So there's one activity (with only incoming funds) under the old ID 41127 http://d-portal.org/ctrack.html?#view=dash_quality&pub=41127
and then 100 activities with the new ID http://d-portal.org/ctrack.html?#view=dash_quality&pub=XM-OCHA-FTS
(and 101 activities on the Registry).  Is it not just that we (I) have not mapped these two together properly, and so we're still showing the old ID data on d-portal (eg no data, as it only contains Incoming Funds)?  

And then maybe there's an issue to raise with the tech team about the activity with the old Org ID in?

**Comment by xriss** [comment]
Yup, it looks like a reporting org ID problem, so a miss match between the IATI registry and the IDs used inside activities. Which ID are they supposed to be using?

This is all the data we pull in from the registry (all in one big file so easy to search)

https://raw.githubusercontent.com/devinit/D-Portal/master/dstore/json/publishers.json

Can be worth doing some searches for ids/names in there to see what we are expecting.
Only 41127 seems to be the ID used.

**Comment by Mattdevinit** [comment]
thanks - so it's XM-OCHA-FTS (the new ID, which it should be) in the data, but looking at that json file it's still 41127 in the Registry?  (whereabouts in the Registry is that from - I couldn't see an org file for them?)

**Comment by xriss** [comment]
First I visit 

http://iatiregistry.org/api/rest/group

to get a list of slugs and then for each slug ( examples below use unocha ) we visit here the actual data

http://iatiregistry.org/api/rest/group/unocha

This is the same data you would get from

http://iatiregistry.org/publisher/unocha

**Comment by Mattdevinit** [comment]
great - thanks.  I think...the following...(mainly because you've just told me!)

UNOCHA is a separate publisher to OCHA-FTS
UNOCHA is publishing one file, with IF transactions only - hence, their data's not in d-portal

OCHA-FTS has a mismatch of publisher IDs, and they need to update their ID in the Registry (which I couldn't find, but apparently you can only see someone's ID if you're logged in - will raise an issue on the Registry GitHub about that)

UNDP also has a mismatch on IDs, and need to change in their publisher profile on Registry, as above

Will get back to them, and let you know any progress on their changes - thanks!

**Comment by Mattdevinit** [comment]
The Org ID has now been changed in the Registry too, for the FTS data (to XM-OCHA-FTS).  I added that as a new publisher to ctrack last night, but it hasn't come through (the FTS data)...could you give me a hand please?  I didn't change the UNOCHA details (41127) in ctrack as that's a separate publisher account to OCHA-FTS.  Any ideas @xriss @notshi ? Thanks

**Comment by Mattdevinit** [comment]
Data now showing - only thing to check is sectors now http://d-portal.org/ctrack.html?publisher=XM-OCHA-FTS&tongue=eng#view=publisher (currently blank, but was showing fine a couple of weeks ago).  In the data there are DAC 5 digit sector codes and the relevant sector vocabulary, and also 'RO' as a sector vocabulary.  Have suggested OCHA adds percentages to each sector vocabulary.  
@xriss to look into whether this is the reason sectors not showing on FTS data.
General rule in d-portal should be to just use DAC sectors if present, when multiple sector vocabularies are published.

**Comment by notshi** [comment]
Looks like the import bug has fixed the sectors showing. Can you check if all is ok, @Mattdevinit ?

**Comment by Mattdevinit** [comment]
all good - thanks a lot
