### ISSUE TITLE
Currency list update

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#250]
Could you update please?  Have just added Ghana to the list of currencies in the dropdown, in advance of meetings next week there

**Comment by notshi** [comment]
Hi @Mattdevinit , have just updated but can't see any changes. Unless I've missed it!

**Comment by Mattdevinit** [comment]
hmm, no, nor can I!  maybe user error?!  I thought it was in ctrack (IMF currencies tab) but maybe I've not done that part right?

**Comment by notshi** [comment]
Hmm very strange. I can change the currency in the URL and it shows fine but it's not showing up in the dropdown. Looking into it.

**Comment by notshi** [comment]
Ok, all good. Was an error on my part, should be done now :}

**Comment by Mattdevinit** [comment]
great - thanks @notshi !
