### ISSUE TITLE
Dropdown menus blank

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#251]
Just looking today at the site generally today and it looks like (although the info is there) the dropdowns at the top of the pages with data on have blanks (until you hover over them)?
![blank dropdowns](https://cloud.githubusercontent.com/assets/3502991/6666041/3ce9267e-cbd8-11e4-9c44-ba9b007f0f23.PNG)

**Comment by notshi** [comment]
Hi @Mattdevinit, sorry about that. Should be fixed now.
