### ISSUE TITLE
action aid 

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#252]
hi @xriss @notshi - any ideas on this please?

Looking for root of this (bad) recipient country with multiple codes http://d-portal.org/ctrack.html?publisher=GB-CHC-274467&usd=GBP#view=publisher 
leads to this file in d-portal http://d-portal.org/ctrack.html?publisher=GB-CHC-274467&usd=GBP#view=act&aid=NL-KVK-27264198-PJ-00082 and the associated xml http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=NL-KVK-27264198-PJ-00082

Obviously the recipient IDs are bad in the xml...but can't find the same xml in the Registry?  This is their file from there http://www.aidstream.org/files/xml/aauk-activities.xml - searching 'ready for anything' here, and it looks like the recipient country codes are individual?

**Comment by xriss** [comment]
This is the file from the registry

http://www.actionaid.org.uk/sites/default/files/IATI/1417538174.19.xml

goto

http://d-portal.org/ctrack.html?publisher=GB-CHC-274467&usd=GBP#view=act&aid=NL-KVK-27264198-PJ-00082

click "dataset" link at the top and then download to get to that file

BTW

http://d-portal.org/q.csv?reporting_ref=GB-CHC-274467&from=act,country&select=aid,slug,country_code&limit=-1

might help to find problems, it shows countries with activity ids and slugs (registry ids) for that publisher.

**Comment by Mattdevinit** [comment]
thanks @xriss 
So to clarify, the file we get from the registry http://www.actionaid.org.uk/sites/default/files/IATI/1417538174.19.xml
is different to the file you get if you click 'download' on this page?  http://iatiregistry.org/dataset/aauk-activities

**Comment by stevieflow** [comment]
Is this not related to the fact that ActionAid UK and Action Aid International are two different publishers on the IATI Registry, but tend to mix up their identifiers?

So - the activity with those country codes is actually in:

http://iatiregistry.org/dataset/aai-dfidglobal2013 (Action Aid International file):

with:

``<reporting-org ref="GB-CHC-274467" type="21">ActionAid United Kingdom</reporting-org>
<iati-identifier>NL-KVK-27264198-TM12MYM-PJ-001000</iati-identifier>``

cc/ @danmackenzie

**Comment by Mattdevinit** [comment]
yep, makes sense, thanks all. 
in addition, the activity that AAUK report (raised by @danmackenzie) for the same project is in d-portal (here under 'active projects' http://d-portal.org/ctrack.html?publisher=GB-CHC-274467&tongue=eng#view=act&aid=GB-CHC-274467-5GBR-PJ-00082) but not here on AAUK's page http://d-portal.org/ctrack.html?publisher=GB-CHC-274467&tongue=eng#view=publisher simply because there's no transactions related to that activity.

So (I think) what we've got is the same activity (ending PJ00082) reported by both AA's, but bizarrely in AAUK's d-portal homepage the only version that shows there is actually AAI's (due to their bad IATI identifier), and AAUK's doesn't, because there's no transactions.

**Comment by stevieflow** [comment]
I'd agree.
