### ISSUE TITLE
Clarify - use of activity-status

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#253]
Hi 

Just wanted to clarify how ``activity-status`` is used in d-portal - specifically in terms of the "active projects" / "closed projects" segmentation provided on the organisation / country homepages.

Thanks

**Comment by xriss** [comment]
It ended up getting ignored as it was often "wrong".
Activity start/end dates are used instead to work out which projects are active or ended or planed for the future.

**Comment by stevieflow** [comment]
ok thanks for the quick clarification @xriss 

One additional question - how do you qualify something as being planned (start dates in the future, I guess?)?

**Comment by xriss** [comment]
Yup.

**Comment by stevieflow** [comment]
Thanks
