### ISSUE TITLE
List of projects csv

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#255]
Had a request for being able to download the data on a list of projects page eg http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=donor_transactions&year=2014&funder=US to a csv

**Comment by notshi** [comment]
list of activities to csv

**Comment by notshi** [comment]
CSV download link is now live.

US has changed their id so that link doesn't work right now so this is the same list of projects with their new id:

http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=donor_transactions&year=2014&funder=US-USAGOV

**Comment by Mattdevinit** [comment]
just re-opening...could we also add the csv option to the lists that come from the projects boxes here http://d-portal.org/ctrack.html?country=BI&tongue=eng#view=main eg this list which is Burundi's Active projects http://d-portal.org/ctrack.html?country=BI&tongue=eng#view=active

**Comment by notshi** [comment]
These should all now be live on their respective pages; Active, Planned, Ended, Total, Other, IATI Publishers.
