### ISSUE TITLE
UNDP missing from dropdown list?

### ISSUE THREAD

**Issue by MichaelMedley** [devinit/D-Portal#258]
I can't find UNDP (or United Nations Development Programme) in the dropdown list of publishers.

**Comment by xriss** [comment]
Looks like they are using the wrong publisher ID and getting filtered out (the front page has some bad data filtered out)

http://d-portal.org/ctrack.html?publisher=XM-DAC-41114#view=publisher

So they are pubishing with XM-DAC-41114 but in http://iatiregistry.org/api/rest/group/undp it is set to just 41114 so they need to be synced before it will show up on the front page.
