### ISSUE TITLE
Display results in Savi

### ISSUE THREAD

**Issue by Jaspermid** [devinit/D-Portal#261]
I've had this issue before but did not follwo up (sorry for that). 

Results do not show up in D-portal widget generator. For instance in the Partos programme we have output results (the number of participants that com to our meetings). 

For instance: http://d-portal.org/ctrack.html?publisher=NL-KVK-34214586&#view=act&aid=NL-KVK-34214586-1 in my opinion should show the participants of all our meetings.

**Comment by notshi** [comment]
Thanks, brought up here - https://github.com/devinit/D-Portal/issues/179#issuecomment-101294935

**Comment by notshi** [comment]
```<result>``` should now show up. The layout will be a work in progress until I fully understand how publishers are publishing data under this element.

**Comment by Jaspermid** [comment]
@notshi results do show up but the actual result indicator does not. This is in the - Period:
Actual: [value="25" ] section of the result field

**Comment by notshi** [comment]
Yes, it's currently just showing things text that are published within sub elements but not any attribute values. This is looking more and more bespoke so I might have to omit the child elements for the moment.

**Comment by Mattdevinit** [comment]
think this is worth considering in the medium term, thanks @Jaspermid for raising!  it's quite a complex one, and often adds large amounts of text to the savi page.  it's quite time consuming too, so would probably need additional funding to do this properly (we are currently very limited with amount of dev time we can spend on d-portal overall).
