### ISSUE TITLE
Canada project amounts

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#265]
Not sure why this is - if you click Canada from this table http://d-portal.org/ctrack.html?country=SL&tongue=eng#view=donors (from the NAME column) you get this table http://d-portal.org/ctrack.html?country=SL&tongue=eng#view=donor_activities&funder=CA on which all projects are 0.  Looks like there's commitments and disbursements on these projects, so not sure why the zeroes?  

Seems to be an issue persisting in Canada data (from other country tables eg http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=donors), and looks like it is working ok for other publishers when clicking on them from these tables - any ideas?

**Comment by xriss** [comment]
Sorry, this is a bug in the import (only happens with 2.01+ data) where it doesn't cache the correct transactions to work out the total spend and commitments for each activity.

fixed in github and a reimport tonight will fix the server side data so the numbers should be correct tomorrow.
