### ISSUE TITLE
Displayed year on list of projects page

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#266]
When clicking on a name in a table http://d-portal.org/ctrack.html?country=SL&tongue=eng#view=donors it takes you to a page listing all projects like this one http://d-portal.org/ctrack.html?country=SL&tongue=eng#view=donor_activities&funder=CA - just need to remove the year reference completely (eg (IATI 2014) in the speech bubble here, as this is projects across all years, rather than year-specific.  And then change text
 	Active projects for Canada and current spend (USD) 
to     All active projects for Canada and current spend (USD)

**Comment by notshi** [comment]
Done.

**Comment by Mattdevinit** [comment]
thanks for removing from project list pages eg http://d-portal.org/ctrack.html?country=WS&tongue=eng#view=donor_activities&funder=AsDB-Special-Funds
has this also removed the (IATI 2014) from these homepages?  http://d-portal.org/ctrack.html?country=WS&tongue=eng#view=main
could we re-instate the (IATI 2014) on the text for both pie charts those homepages, as useful to show what the pie charts relate to

**Comment by notshi** [comment]
Done.
