### ISSUE TITLE
Currency conversion - same currency

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#270]
Look at way to keep currency conversion for a non-USD currency to a minimum when showing in that currency, eg

activity reported in GBP currently gets converted to USD and then back to GBP on different dates (depending on date of activity/date of publishing) resulting in difference in amount published compared to on d-portal, due to currency conversion rate changes between those dates.

**Comment by notshi** [comment]
https://github.com/devinit/D-Portal/issues/262

**Comment by notshi** [comment]
Backend is done, needs to reflect on front end.
