### ISSUE TITLE
Variations on charts and maps view

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#274]
request for other viewing options as follows
- option to select different years on (home page) charts view
- filter map data by year

**Comment by notshi** [comment]
You can currently do this by adding ```&year=``` for example, http://d-portal.org/ctrack.html?&publisher=44000&year=2010#view=publisher

**Comment by Mattdevinit** [comment]
thanks - our of interest is there a variation on the query to show all years, or a range of years, here too?

**Comment by notshi** [comment]
Nope, don't have that. It just sets the base year.

**Comment by notshi** [comment]
Closing this due to insufficient funding.
