### ISSUE TITLE
Activities With A Start Date and No End Date Should Not Be Treated as Missing

### ISSUE THREAD

**Issue by iatisupport** [devinit/D-Portal#279]
My current understanding is that activities with a start date but no end date are currently included in the count of missing projects. However, I'm thinking that this need not be the case as we can assume that these projects are in 'Implementation' . Also V2.01 of the IATI Standard that now includes mandatory fields only requires at least one start date (see - http://iatistandard.org/201/upgrades/integer-upgrade-to-2-01/migrating/#mandatory-fields-in-activity-standard) so there is likely to be a lot of activities for many publishers where maybe only one date is initially available. In addition, some publishers report their programmes as activities that are essentially on-going and may not have an end date for a very long time?

**Comment by Mattdevinit** [comment]
Think this is worth updating - add rule that when an activity has a start date (before today's date) and no end date, that it is Active rather than Missing (eg here http://d-portal.org/ctrack.html?publisher=DE-1&tongue=eng#view=publisher)

**Comment by notshi** [comment]
Hi,

Missing just means the activity is missing from the table and not from the rest of the site. We could probably reword, "missing" to something else as that was a wip term for activities that could not be filtered under the other terms.

**Comment by iatisupport** [comment]
Hi @notshi could the number of activities that have start dates but no end dates be included in the total count of 'active' projects in the table or is that not possible? Thanks in advance

**Comment by Mattdevinit** [comment]
I think on balance this logic makes sense, and that we should do both...rename 'missing' to 'other' (and I'll add a note to the bottom to explain that), and count any projects with a start day (before today) as Active, if no end date

**Comment by notshi** [comment]
Missing is now changed to 'Other'. Still looking at changing the code as that will have a big impact on the portal so we'll be making a local copy for you to check before we push the changes live.
