### ISSUE TITLE
Result titles are presented with label "Project title"

### ISSUE THREAD

**Issue by rolfkleef** [devinit/D-Portal#281]
On a project page [such as this one](http://d-portal.org/ctrack.html?publisher=NL-KVK-20093733&tongue=eng#view=act&aid=NL-KVK-20093733-GH1NR121) the result titles are presented with the label "Project title", and the description is labelled "Result".

I would propose to just put the label "Result" above the title, and remove the label for the description.

**Comment by Mattdevinit** [comment]
Agreed - will do.  thanks @rolfkleef !

**Comment by notshi** [comment]
Result titles are now fixed.
