### ISSUE TITLE
Pull together all 'missing' activities in Dash

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#282]
For review, before amending methodology to include these as Active

**Comment by xriss** [comment]
I've added some stats, regarding how many activities are missing end dates

you can find them on http://d-portal.org/ctrack.html#view=dash_quality

currently we have.

Activity State	Activities
Total	438162
Ended	313309
Planned	1805
Active	73640
Missing or bad dates so it can't be classified.	49408
Missing end date only	17752


so there are 17752 activities that will be reclassified as active or planned if we accept missing end dates you can take a look at them here.

http://d-portal.org/ctrack.html?#view=list_activities&day_start_not_null=1&day_end_null=1

**Comment by xriss** [comment]
BTW looking at the code, I think this can actually be switched on easily.

But.

It involves a small change at the time of import. So would have to be run over night and then we would see the new site in the morning and its not easy to "test" without doing this overnight change.

So its a bit of a change on the live site only unless you want me to do a full import locally and let you have a look at it before going live.

**Comment by Mattdevinit** [comment]
yep please, a review on a local instance would be great

**Comment by Mattdevinit** [comment]
go for it @xriss !

**Comment by notshi** [comment]
Projects with a start date but no end dates are now no longer filtered as "Others".
