### ISSUE TITLE
API Errors

### ISSUE THREAD

**Issue by rory09** [devinit/D-Portal#285]
Hi all, the api is behaving quite strangely at the moment.

### Terminal XML request

Trying to access XML data through shell is returning unexpected data, with the reporting-org reference being wrong a fair amount of the time, and pausing mid-way through the download. On `wget http://d-portal.org/q.xml?reporting_ref=GB-COH-06368740` (Development Initiatives), the resulting file begins:
  
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/art/activities.xsl"?>
<iati-activities xmlns:dstore="http://d-portal.org/dstore">
<iati-activity dstore:slug="finland_mfa-002" dstore:idx="2477" default-currency="EUR" last-updated-datetime="2014-12-19T11:03:42" xml:lang="en" >
<reporting-org ref="FI-3" type="10" >
Ministry for Foreign Affairs of Finland</reporting-org>
<iati-identifier >
1988880044</iati-identifier>
<title >
NGO Support / Yangon Film School</title>
<!-- clipped -->
```

Similarly `curl http://d-portal.org/q.xml?from=act,trans&reporting_ref=GB-1` returns

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/art/activities.xsl"?>
<iati-activities xmlns:dstore="http://d-portal.org/dstore">
<iati-activity dstore:slug="undp-global" dstore:idx="2" last-updated-datetime="2015-07-09T15:59:36" default-currency="USD" xml:lang="en" hierarchy="2" >
<reporting-org ref="XM-DAC-41114" type="40" >
United Nations Development Programme</reporting-org>
<iati-identifier >
XM-DAC-41114-OUTPUT-00063997</iati-identifier>
<related-activity type="1" ref="XM-DAC-41114-PROJECT-00051408" >
</related-activity>
<recipient-region code="998" >
Africa</recipient-region>
<title xml:lang="en" >
Energy Proj.for Poverty Reduct</title>
<!-- clipped -->
```

And where `http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119` returns [this](http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119) through a browser, `curl http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119` returns this in bash:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/art/activities.xsl"?>
<iati-activities xmlns:dstore="http://d-portal.org/dstore">
<iati-activity dstore:slug="finland_mfa-002" dstore:idx="2477" default-currency="EUR" last-updated-datetime="2014-12-19T11:03:42" xml:lang="en" >
<reporting-org ref="FI-3" type="10" >
Ministry for Foreign Affairs of Finland</reporting-org>
<iati-identifier >
1988880044</iati-identifier>
<title >
<!-- clipped -->
```

With all of these, the download never completes. `wget` demonstrates this. If I try to do the same, but with `wget http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119`, the download pauses here like this: 
![image](https://cloud.githubusercontent.com/assets/7805169/10104161/f5af6ee8-639f-11e5-8ec6-bbb697ba6911.png)

### XML query through browser is halting

When entering `http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119` into a browser, the SAVI marked-up XML is displayed. However, when doing the same for `http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=GB-COH-06368740` or `http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=GB-1`, a blank screen is returned.

I'm aware that some of this may be down to my use of the q syntax, so please let me know if I've made any mistakes there. 

Many thanks,
Rory

**Comment by notshi** [comment]
Hi, @rory09

You'll need to put quotes around the url when it contains & in the query, like so:

```wget "http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119"```


We're also in the process of updating the way the XML gets returned  so after a full update tonight, the XML returned should hopefully be IATI-compatible XML.

**Comment by rory09** [comment]
Hi, @notshi - thanks for getting back to me so quickly, and for the changes to the way the XML gets returned, it looks great from what I've seen so far!

I've retried some of these with quotes, and that has fixed the Finland problem, but I think I'm still missing something with the query syntax. For example:

```sh
wget "http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119" -O select_verbose.xml
```

Returns a file that is 1.14MB in size, whereas:

```sh
wget "http://d-portal.org/q.xml?from=act,sector,country&reporting_ref=41119&country_code=CG" -O select_verbose_congo.xml
```

Returns a file that is 1.21MB, but I'd expect a much smaller file for the latter, or a much larger one for the former - is there something I need to do to page through results, or increase the size limit?

Also, I'm not sure if it's relevant, but I'm still noticing what seems to be a halted download. If I use wget with quotes to download the IATI standard organisations schema, the shell prints this:

![image](https://cloud.githubusercontent.com/assets/7805169/10169314/61797c9c-66c8-11e5-9862-e9877b39c9eb.png)

However, the wget from D-Portal is still halting like this:

![image](https://cloud.githubusercontent.com/assets/7805169/10169338/81c79d30-66c8-11e5-9558-3df6705b95a1.png)

Thanks again,
Rory

**Comment by notshi** [comment]
Hi, @rory09 - the default limit is 100 so you'll only get 100 results. This is a quick/simple way to reduce server hits and accidental DOS.

We're thinking of changing the backend so it can cope with slightly bigger returns. At the moment, it's going to fail for huge returns (out of memory) as it wasn't a priority when building the interface.

Hopefully, after restructuring, queries will be faster.

For now, you can try &limit=-1 but that may crash the server, depending on the query :}

**Comment by rory09** [comment]
Hi @notshi  - thanks for this, that makes a lot of sense. I think I've crashed the server a few times by putting `&limit=100000` or something like that, so apologies! Luckily it's very quick to restart :)

For now I'll explain to people that it can offer representative xml, but not a complete download. Because of the woes we're having with the datastore, it would be good to increase the capacity, though I understand that this might take some time.

Thanks for your patience with this!

**Comment by Mattdevinit** [comment]
FYI - work on changing back end to help address this will be done in October
