### ISSUE TITLE
Sightsavers data

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#286]
Any idea why this data http://www.iatiregistry.org/publisher/ss-org isn't showing here? http://d-portal.org/ctrack.html?publisher=GB-CHC-207544#view=publisher

**Comment by xriss** [comment]
Looks like a date problem again

curl -I http://www.sightsavers.org/wp-content/uploads/2015/09/org_Sightsaversprojectdata.xml
HTTP/1.1 200 OK
Date: Fri, 25 Sep 2015 17:17:07 GMT
Server: Apache/2.4.6
Last-Modified: Wed, 23 Sep 2015 14:44:43 GMT
ETag: "21773b-5206b27b30cdb"
Accept-Ranges: bytes
Content-Length: 2193211
Vary: Accept-Encoding,User-Agent
Content-Type: text/xml

I last downloaded the data for that file

Sep 24 01:21 ss-org-projects.xml

So I think I have the most recent version and it wont update until the full weekend import.


I'll try and add some more logic (we can easily test the file size as well) so this becomes less of a problem when it comes to picking up changed files.

**Comment by notshi** [comment]
This is now fixed.
