### ISSUE TITLE
XML error due to namespaces not being declared

### ISSUE THREAD

**Issue by Bjwebb** [devinit/D-Portal#288]
http://d-portal.org/q.xml?aid=US-1-UA-20-AID-121-IO-13-00004

In chrome I see:
![d-portal-xml-error](https://cloud.githubusercontent.com/assets/634/10112057/3b4d6272-63d0-11e5-951b-4a3ecf31c54a.png)

The IATI datastore adds the namespace declaration to the `iati-activity` element - http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=US-1-UA-20-AID-121-IO-13-00004, which avoids this problem.

**Comment by notshi** [comment]
I'm not seeing this right now in Chrome so it may be something we have changed recently.

Is this still doing this for you?

**Comment by Bjwebb** [comment]
Seems to be fixed now for me too.
