### ISSUE TITLE
Data doesnt look right

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#289]
I'm looking at this page:

http://www.d-portal.org/ctrack.html?publisher=GB-COH-1364201&tongue=eng#view=publisher_countries&year=2015 

AFAIK, this organisation only publish one activity file:

http://www.plan-uk.org/assets/Documents/iati/iati-data/plan_uk-dfid-activities.xml

It has 36 projects:

http://dashboard.iatistandard.org/publisher/plan_uk.html

However, d-portal says something different.  

There is a long list of countries, most of which are not in the source data:  Tanzania (TZ), Tuvalu (TV)

There are regions cited (198; 998) - but no region codes are in the source data

And - some countries are listed (Turkey) - with a 2015 budget 

Turkey
0
0
0
0
858,661,936

**Comment by stevieflow** [comment]
OK - on clicking around on other pages, it now seems that ALL publishers have this long list too, with the same values in the "2015 available" column - eg:

http://www.d-portal.org/ctrack.html?publisher=GB-CHC-326859&tongue=eng#view=publisher_countries

http://www.d-portal.org/ctrack.html?publisher=ZA-NPO-025-359&tongue=eng#view=publisher_countries

What is this?  It doesnt look like it is useful within these pages....

**Comment by xriss** [comment]
data is coming from the org files and is a recent request/addition

https://github.com/devinit/D-Portal/issues/273

Possibly something broken, will have a look into it and check why so many zeros which doesn't sound right.

**Comment by stevieflow** [comment]
Thanks @xriss 

OK - can understand the function ( @Mattdevinit - it probably needs documenting and a blog post etc)

But - something must be astray, as Plan UK (http://www.d-portal.org/ctrack.html?publisher=GB-COH-1364201&tongue=eng#view=publisher_countries&year=2015) dont have *any* country budgets in their org file: http://www.plan-uk.org/assets/Documents/iati/iati-data/plan_uk-organisation.xml

**Comment by xriss** [comment]
I think it should be better now, it was failing to restrict the data to the right publisher.

**Comment by stevieflow** [comment]
Thanks again @xriss !

Ill leave this open for @Mattdevinit to check.  Would be good to get some narrative / guidance out about this for people ....

**Comment by Mattdevinit** [comment]
thanks @stevieflow - @notshi will put note up on News page shortly, and have posted on Google group about this update.  We'll be adding the search function soon (after user testing) and as part of that will redesign the front page to make FAQs, news etc more prominent (and there'll be more news there!)

**Comment by notshi** [comment]
News page updated :}
