### ISSUE TITLE
US agencies not accessible via homepage

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#290]
Via http://www.d-portal.org/ there's a link to http://www.d-portal.org/ctrack.html?publisher=US&tongue=eng#view=publisher, which aggregates the data where ``reporting-org="US"`` (I think)

However, the US agencies actually report via a number of reporting orgs: http://dashboard.iatistandard.org/publisher/unitedstates.html

> Reporting Org(s) in Data	US US-1 US-10 US-13 US-18 US-2 US-6 US-7 US-8 US-USAGOV

Hence, I can manipulate d-portal URL to get:

http://www.d-portal.org/ctrack.html?publisher=US-USAGOV&tongue=eng#view=publisher - which is more populated / useful

I had understood that some mapping between reporting-org references and names was taking place behond-the-scenes, but wanted to ask if any aggregation of multiple reporting-orgs was planned/possible?

And/or - how could we get the multiple reporting-orgs listed above on the d-portal homepage?

This may be an outlier, as at the IATI Registry the reporting-org should be singular per publisher, but pur issue is that this is very useful data that is easily missed!

**Comment by stevieflow** [comment]
US-USAGOV is listed here: http://www.d-portal.org/ctrack.html?tongue=eng#view=publishers though

**Comment by xriss** [comment]
I think the US has been changing its ID recently so suspect that data on the iatiregistry is still not in sync with what is actually getting used right now. I think US-USAGOV seems to be what is used now maybe not listed on the iatiregistry?


The main list of publishers on the d-portal front page should be the same as this list as it is built the same way, IE publishers registered on the iatiregistry that have published some data.

http://iatiregistry.org/publisher

It used to just run off of publisher IDs that could be found in the published data however it was changed to run only off of registry meta data and present a more curated front page.


Some other links of interest are.

http://www.d-portal.org/ctrack.html#view=dash

which should list all the publishers along with number of activities in d-portal database.

**Comment by Mattdevinit** [comment]
Think there's a couple of issues with the data - the Registry ID was 'US' which didn't match anything in the data as it should.  Also that one Registry profile includes data for all US agencies, so one Registry ID to multiple IDs in the data - I think this should be one publisher per profile?
The ID in the Registry profile has now been amended to US-USAGOV, so that data now shows here http://www.d-portal.org/ctrack.html?publisher=US-USAGOV&tongue=eng#view=publisher and I think the IATI tech team are following up on the multiple agency issue, so hopefully that will be sorted soon

**Comment by stevieflow** [comment]
Thanks @Mattdevinit -

**Comment by markbrough** [comment]
There appear to be other issues with the US data - nothing is now appearing:
www.d-portal.org/ctrack.html?publisher=US-USAGOV&tongue=eng#view=publisher

It would be helpful if it were somewhere shown what the issues are with the data.

**Comment by Mattdevinit** [comment]
hi @markbrough we had an unforeseen issue with import overnight, and it's still re-populating which is why that (and others) are currently empty...hope it will all be back within the next couple of hours

**Comment by Mattdevinit** [comment]
The full update was finished on Friday and data is in for US http://d-portal.org/ctrack.html?publisher=US-USAGOV&tongue=eng#view=publisher (it does take a little while to load US page first up, as there's a lot of data - will look at how we can speed it up)
