### ISSUE TITLE
Participating-org role refs in 2.01

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#293]
There's a couple of things with WFP data here http://www.d-portal.org/ctrack.html?publisher=XM-DAC-41140&tongue=eng#view=act&aid=XM-DAC-41140-200040 that are making the participating roles show as blank in d-portal Savi - have added a support desk ticket to suggest adding the actual org refs which should help https://iati.zendesk.com/agent/tickets/2944

But just wanted to check, the participating role in the data (1, 2 or 4) http://d-portal.org/q.xml?aid=XM-DAC-41140-200040 looks ok, but is from an IATI Standard 2.01 codelist - are we picking that up in d-portal?

**Comment by notshi** [comment]
We are now picking up role refs as well as text in the field so they should now show up.
