### ISSUE TITLE
Filter out list of projects when clicking on numbers in table

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#294]
eg table here http://d-portal.org/ctrack.html?publisher=GB-COH-06368740&tongue=eng#view=publisher_countries&year=2014 clicking on '2015 allocated' figure for UK brings up list of all projects with any budget data http://d-portal.org/ctrack.html?publisher=GB-COH-06368740&tongue=eng#view=list_budgets&year=2015&country_code=GB (eg last project on list has only 2013 budget info).  Need to restrict to only projects relevant to the number clicked on in previous table

**Comment by notshi** [comment]
This is now fixed and live.
