### ISSUE TITLE
BRC data not displaying

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#295]
This org:  

http://dashboard.iatistandard.org/publisher/gb-chc-220949.html

have new data in the registry/dashboard,but nothing in d-portal:

http://www.d-portal.org/ctrack.html?publisher=GB-CHC-220949&tongue=eng#view=publisher

afaik there are transactions in 2014, but d-portal doesnt seem to be working with any data,  

It's 2.01. but that isnt an issue, I assume

The only thought was that there might be something not quite synched between the registry and reporting-org references, although cant see what....

**Comment by stevieflow** [comment]
NB: BRC are using the three digit DAC sector codes, so wary that that wont render a visualisation in d-portal.  However, I dont think that is the issue !

**Comment by xriss** [comment]
Checking the logs etc, it looks like the package information it saw last night was not as up to date as the package information I can see today.

in fact 4 days ago was the last change I see on the registry so maybe it was different last night or maybe something strange is happening.

If its not urgent I'm just going to let it just run again tonight and see how it behaves now that I know the data has changed and then I can check up on what it does.

**Comment by stevieflow** [comment]
Thanks @xriss - let's see what tomorrow brings

**Comment by Mattdevinit** [comment]
Hi @stevieflow - I didn't get round to looking at this yesterday, but checking to link today it looks good - is this what you were expecting now?

**Comment by stevieflow** [comment]
Thanks @xriss @Mattdevinit all seems to have imported now
