### ISSUE TITLE
Changes for 2016

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#297]
At start of Jan we'll need to 
Add new CRS data (when available)
Amend which data we are showing in charts/tables (by moving all forward one year)
Update text where referring to certain years

**Comment by bill-anderson** [comment]
@xriss could we get this from DDW? Manually this time around , but by 2016 there will be a public api straight into DDW (i.e. not via DDH)

@Mattdevinit this is project cross-over (as in joined-up data in practice)

**Comment by Mattdevinit** [comment]
@bill-anderson great, look forward to joining that data up then

**Comment by stevieflow** [comment]
HI - any chance to know of the timescales  for this ?

Related: https://github.com/devinit/D-Portal/issues/300 ?

**Comment by Mattdevinit** [comment]
hi @stevieflow - generally these changes will be done much more quickly than it has been this year, but unfortunately due to some delays internally with a new system for pulling latest CRS data being set up we're not quite there yet...but all this should be updated within next 2 weeks

**Comment by iatisupport** [comment]
Are we still on schedule for these changes Matt? Do we have a go live date yet? Thanks

**Comment by Mattdevinit** [comment]
Yep, hoping to check these updates tomorrow/Monday on a test version, and update to live on Tues (earlier if poss)

**Comment by stevieflow** [comment]
@Mattdevinit @iatisupport  that'd be great - thanks

**Comment by Mattdevinit** [comment]
Just a quick update to say this is a little bit delayed due to illness!  will be asap and will update again shortly, thanks

**Comment by Mattdevinit** [comment]
@stevieflow @iatisupport this is updated now, so charts are showing 2015 data and tables have moved on a year, and include the latest (2014) CRS data...if you spot anything that looks out of place do give us a shout!

**Comment by stevieflow** [comment]
Great, thanks @Mattdevinit 

Just checking - DFID seems to missing 2015 countries (2.01?): http://www.d-portal.org/ctrack.html?publisher=GB-1&tongue=eng#view=publisher cc/ @johnadamsDFID

**Comment by stevieflow** [comment]
@Mattdevinit @iatisupport @johnadamsDFID: Think the lookup for DFID needs to be updated - this page is more realistic: http://www.d-portal.org/ctrack.html?publisher=GB-GOV-1&tongue=eng#view=publisher

**Comment by Mattdevinit** [comment]
thanks @stevieflow. DFID's publisher ID in the Registry has been updated today - there was previously a mismatch with that (GB-1) and the ID within the data (GB-GOV-1).  hopefully we can update overnight tonight, and picking up the new Registry ID means d-portal will be able to match them up and show DFID correctly again

**Comment by Mattdevinit** [comment]
just following up - this has updated on d-portal following the amend to Registry ID in DFID profile http://d-portal.org/ctrack.html?publisher=GB-GOV-1&tongue=eng#view=publisher

**Comment by stevieflow** [comment]
Thanks @Mattdevinit
