### ISSUE TITLE
Issues with dates in data? 2014 showing as zero values

### ISSUE THREAD

**Issue by SJ-bond** [devinit/D-Portal#298]
We've had reports from two organisations that they are seeing zero values in the visualisation for their projects on d-portal. Any advice or is this a known issue? I don't want to name orgs here but happy to do this offline.

**Comment by bill-anderson** [comment]
support@iatistandard.org

**Comment by Mattdevinit** [comment]
As Bill says, please route this through the iatistandard helpdesk.  This is most often due to some issues with the publisher's data - we'll put up a list of the common reasons for this/things to check in the data shortly on the FAQs http://d-portal.org/faq.html

**Comment by SJ-bond** [comment]
I did route it through the iatistandard helpdesk as well, but the link for feedback on the d-portal site comes through to github so I raised an issue here as that's what I assumed you wanted. You might want to give clearer information on the site what that feedback link should be used for.

**Comment by Mattdevinit** [comment]
that's great,  thanks. either here or the email is fine, we're just pointing to the email address so that you can discuss which orgs this relates to offline
