### ISSUE TITLE
IATI 2.02 Compatibility: Incoming Commitment

### ISSUE THREAD

**Issue by rory09** [devinit/D-Portal#301]
A user just pointed out that on [one of their activity pages](http://d-portal.org/ctrack.html?publisher=NL-KVK-41208813#view=act&aid=NL-KVK-41208813-DCIID056GA_Africa), a transaction type has been listed as `11`, which should resolve to "Incoming Commitment" [since the 2.02 upgrade](http://iatistandard.org/202/codelists/TransactionType/).

**Comment by xriss** [comment]
Should be fixed now. We where still using a 201 code list.
