### ISSUE TITLE
Traceability versus aggregation: most information unreliable

### ISSUE THREAD

**Issue by rolfkleef** [devinit/D-Portal#302]
In the guidelines of the Dutch MFA, organisations are advised to use parent-child relations to link overall programmes and underlying projects. Also, in partnerships, activities of partners as part of a programme are funded from a programme activity.

This seems to lead to two "acute" problems:

1) If an organisation publishes budgets for both the overall programme and for the child projects in that programme, it appears that those budgets are added twice.

2) If one organisation managing the programme published budgets and sectors or countries at the programme level, and either their own projects or those of another partner, also publish budgets and sectors or countries, are those numbers added for sector or country-level overviews?

This basically means that d-portal pages give a wrong picture unless organisations tweak their data for d-portal.

(Maybe somewhat related to the open issue #232 on hierarchies)

**Comment by Mattdevinit** [comment]
Thanks @rolfkleef - d-portal was/is set up just to show all IATI activities aggregated by recipient country or publisher, so if activities have different IDs the data within both will both show up in d-portal (this is the reason we don't then total up the data in tables).  
I think other publishers use hierarchies in a similar situation - where the rule is that you publish the budget at only one level of hierarchy, so there is no duplication.  We can consider a rule in d-portal which only uses either the budget at the parent or child level - but if it's feasible this would obviously only address the issue in d-portal...interested to find how other data users show this.

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
