### ISSUE TITLE
Search results feedback

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#303]
See note from Ben Parker here on 31st May) http://discuss.iatistandard.org/t/full-test-search-including-narrative/469/3 including screenshots of issue

**Comment by notshi** [comment]
Thanks, Matt. That's been very useful.

I've changed the placement of the button for now so it won't be covered by the list.

However, we still need it to be obvious that when a user selects an item from the list, they are just adding a filter to the current search and not actually doing a search.

Possibly a visual clue / feedback or just add the words, "Added 'Human Rights' to Search Filter" after the filter has been chosen. Another option is to add a header to the filter list so it's clear what the list is about.

By the way, we've still not designed the results page. Presently, it is using the default d-portal template but this shouldn't be the case for these requirements.

**Comment by notshi** [comment]
Thanks, Matt.

We're currently using the simplest search functionality for the moment which seems to serve its purpose. Adding real search is a much bigger job and will naturally require a lot more development time.

What Ben wants is proper indexing which is building a separate database which you can query; this requires a complex and much bigger job on our end. What we are doing right now is querying the database directly, a simple hack that works like a search.

The database is currently at about 3GB of data which accounts for its speed - not as fast and efficient as we'd like it.

By the way, I've updated the search page again to hopefully be less confusing - http://d-portal.org/ctrack.html?#view=search

**Comment by benparkergit** [comment]
I notice you don't have a /robots.txt - maybe you could encourage Google to index the site more deeply with one?

Best wishes

Ben

**Comment by xriss** [comment]
Thanks, Ben. Problem is, Google won't index most of the pages as they are all generated client side, so they don't really exist until viewed.

Even when it does index it we get penalised for republishing text which is available elsewhere (the original xml activity files). This flags us as a machine generated spam site, one that just republishes content found elsewhere, Google tries to push these sort of sites as far down search results as possible.

There is the same reason modern online journalism consists primarily of rewording press releases (or just content from other sites) to make it look like new content to search engines.

Essentially we are creating something that is indistinguishable from a machine generated spam site and search engines try really hard to filter these sites out of results.

**Comment by Mattdevinit** [comment]
Aiming to make using plus sign in search (eg World+Humanitarian+Summit) work in search function in November (when it will be made more prominent on d-portal)
