### ISSUE TITLE
How are you pulling the organisation-xml-data?

### ISSUE THREAD

**Issue by anjesh** [devinit/D-Portal#305]
I don't see where the script is pulling the organisation-data from the registry. However the agency page shows the organisation budget from the organisation data http://d-portal.org/ctrack.html?publisher=XM-DAC-41114&tongue=eng#view=publisher_countries 

Can you point to the script which pulls the organisation data and stores in the database?

**Comment by xriss** [comment]
The data is stored with all the other budgets budgets and read in from the org files (same time as activity files)
 
They are stored without an activity id and have a budget=type and priority=0 so they are not selected by mistake in the other queries and can be selected by type.

https://github.com/devinit/D-Portal/blob/master/dstore/js/dstore_db.js#L171

so

http://d-portal.org/q?from=budget&budget=org

will get only "recipient-org-budget" budgets
