### ISSUE TITLE
Click through for a year doesnt filter

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#306]
From this (example) page:

http://d-portal.org/ctrack.html?publisher=GB-CHC-1075920&tongue=eng#view=publisher_countries

On the first line:

> South Africa  370,676  254,680  167,662

The first figure links to this page

http://d-portal.org/ctrack.html?publisher=GB-CHC-1075920&tongue=eng#view=list_transactions&year=2014&country_code=ZA

However, the total value for  this page is 1,015,707 - not 370,676

**Comment by andylolz** [comment]
It looks as though the `year` URL param is ignored i.e.:
http://d-portal.org/ctrack.html?publisher=GB-CHC-1075920&tongue=eng#view=list_transactions&year=2014&country_code=ZA

…is the same as:
http://d-portal.org/ctrack.html?publisher=GB-CHC-1075920&tongue=eng#view=list_transactions&year=9999&country_code=ZA

**Comment by notshi** [comment]
Hi both, many thanks for reporting and your patience!

This is now fixed.
