### ISSUE TITLE
Title in French Are Being Truncated and Spaces Removed

### ISSUE THREAD

**Issue by wendyrogers** [devinit/D-Portal#307]
When displaying a list of projects titles in French the titles appear to be truncated see http://d-portal.org/ctrack.html?publisher=FR-6#view=list_transactions&year=2016&country_code=BJ

Also when viewing details of a project in French the title appears to have lost its spaces between some words see - http://d-portal.org/ctrack.html?publisher=FR-6#view=act&aid=FR-6-BJ-BEN%2012-02

**Comment by xriss** [comment]
Looks like an XML entity decoding bug.

Things are getting decoded badly, will take a look at the code, it might be a bug in one of the node libraries used for XML parsing.

**Comment by notshi** [comment]
Hi @wendyrogers, this looks to be fixed. Is this the case? Thanks.

![french](https://cloud.githubusercontent.com/assets/1515961/22691881/58ddbeb0-ed34-11e6-8199-750bff204341.png)

**Comment by wendyrogers** [comment]
Looks good @notshi  and @xriss . Many thanks
