### ISSUE TITLE
Are provider-org activities "linked" in transactions?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#313]
I noticed in this activity:

http://d-portal.org/q.html?aid=GB-COH-03580586-GEC-Fund-A1

-- that the receiver-org activities become links thru to the relevant activity - eg: 

http://d-portal.org/q.html?aid=GB-COH-03580586-GEC-Recipient-5136

The XML is marked up as follows, which seems to support this
`
<transaction ref="FMFR002"><provider-org provider-activity-id="GB-COH-03580586-GEC-Fund-A1" ref="GB-COH-03580586-GEC">Girls Education Challenge  Fund Manager PwC</provider-org><receiver-org receiver-activity-id="GB-COH-03580586-GEC-Recipient-5136" ref="GB-COH-03580586-GEC">Girls' Education Challenge (GEC) (Fund)- Fund Manager PwC</receiver-org><value value-date="2013-04-09" currency="GBP">2514149</value><transaction-date iso-date="2013-04-09">09/04/2013</transaction-date><transaction-type code="D"/><description>INTERNAL ALLOCATION TO PROJECT(WUSC (World University Service of Canada))</description></transaction>`

However, it doesn't seem to be active for the Incoming Funds / provider-org activities.  In this example, the funds are provided by DFID, from this activity:

http://d-portal.org/q.html?aid=GB-1-202372

The XML in GB-COH-03580586-GEC-Fund-A1 illustrates this:
`
<transaction ref="FMFR005">
<provider-org provider-activity-id="GB-1-202372" ref="GB-1">DFID</provider-org>
<receiver-org receiver-activity-id="GB-COH-03580586-GEC-Fund-A1" ref="GB-COH-03580586-GEC">Girls Education Challenge  Fund Manager PwC</receiver-org>
<value value-date="2013-05-17" currency="GBP">1381068</value>
<transaction-date iso-date="2013-05-17">17/05/2013</transaction-date>
<transaction-type code="IF"/>
<description>DRAW DOWN FROM DFID (FMFR005) TO PWC GEC FUND</description>
</transaction>`

(one complication - the *actual* transaction data for DFID is published in http://d-portal.org/q.html?aid=GB-1-202372-103 - I'm not sure if this is a factor for this query though)

**Comment by stevieflow** [comment]
Hopefully this screenshot illustrates it - http://d-portal.org/q.html?aid=GB-COH-03580586-GEC-Fund-A1 - the yellow links are active, whereas the provider-org links are not, despite the XML supporting it, it seems

![links](https://cloud.githubusercontent.com/assets/1209944/20063460/150cf638-a4ff-11e6-8e92-8c072f963eab.png)

**Comment by notshi** [comment]
Hi @stevieflow, thanks for this!

Looks like it was just a typo on our end - this is now fixed and live.

**Comment by stevieflow** [comment]
Thanks @notshi

**Comment by stevieflow** [comment]
Just following up on this

Here's an example of an activity that has transactions that have a link to another activity, but they are not active links in d-portal:

http://www.d-portal.org/ctrack.html?tongue=eng#view=act&aid=NL-CCI-20081098-GPAF-IMP-068

![linkgpaf](https://cloud.githubusercontent.com/assets/1209944/20395570/54091cca-acdb-11e6-9c80-f5dcff8c7541.png)

XML:

`<transaction ref="Expenditure-Q1-15"><transaction-type code="4"/><transaction-date iso-date="2015-06-30"/><value value-date="2015-06-30" currency="GBP">5774.59</value><description><narrative>Provision of quality primary education for 9000 out of school children in South Sudan</narrative></description><provider-org ref="GB-1-202035"><narrative>Global Poverty Action Fund (GPAF)</narrative></provider-org><receiver-org ref="NL-CCI-20081098 -GPAF-IMP-068"><narrative>BRAC INTERNATIONAL</narrative></receiver-org></transaction>`

Both receiver and provider elements lack the org ref , I think - is that a reason for these links not being active?

**Comment by notshi** [comment]
These are not turning into links because activity-id is not provided.

Questions:
1. Do you want to turn provider-org/receiver-org ref to links? Not sure how useful this can be or if this is a data issue.
2. Is this a data issue?

**Comment by stevieflow** [comment]
Nope - my bad.  What confused me (!) was that the actual ref in the example is an activity id!  

It's a data issue.  Apologies for re-opening.  Too many IDs :)
