### ISSUE TITLE
ActivityDateType code for 2.0x data is presented in 1.0x format?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#314]
I noticed this activity in the xml output from d-portal: http://d-portal.org/q.xml?aid=46002-P-MW-AAA-004

http://d-portal.org/q.xml?aid=46002-P-MW-AAA-004

```
<activity-date iso-date="2009-11-13" type="start-planned"/>
<activity-date iso-date="2010-12-20" type="start-actual"/>
<activity-date iso-date="2017-05-30" type="end-planned"/>
<activity-date iso-date="2017-05-30" type="end-actual"/>
```

Whereas in the source data (http://www.afdb.org/fileadmin/uploads/afdb/Documents/Generic-Documents/IATIMalawiData.xml)

```
<activity-date iso-date="2009-11-13" type="1"/>
<activity-date iso-date="2010-12-20" type="2"/>
<activity-date iso-date="2017-05-30" type="3"/>
<activity-date iso-date="2017-05-30" type="4"/>
```

Is there a reason for this output in d-portal?

(Or - is this a datastore thing @dalepotter @bjwebb?)

**Comment by Bjwebb** [comment]
I don't think this is likely to be datastore related.

**Comment by markbrough** [comment]
As far as I understand it, d-portal doesn't use the datastore at all and gets data direct from the Registry?

**Comment by Mattdevinit** [comment]
thanks @stevieflow - will check it out.   correct that d-portal doesn't use the datastore, so it's not that!

**Comment by notshi** [comment]
Fixed
