### ISSUE TITLE
Active link color for linked transactions - differs according to access route

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#315]
Here's an activity page I navigate to from the homepage:

http://d-portal.org/ctrack.html?publisher=NP-SWC-27693&tongue=eng#view=act&aid=NP-SWC-27693-NP

On this page the "link" to the related activity is not in an active color.  It;s difficult to spot this:

![asam-1](https://cloud.githubusercontent.com/assets/1209944/20171557/20c5ea08-a729-11e6-94bf-1e76ff66f4f7.png)

However, if I open the same activity via the ID link (provided at the top of the previous page): http://d-portal.org/q.html?aid=NP-SWC-27693-NP

The transaction link is then more obvious

![asam-2](https://cloud.githubusercontent.com/assets/1209944/20171558/20c67162-a729-11e6-8823-2c4cf350f8ff.png)

Worth a look / tweak?

**Comment by notshi** [comment]
Thanks, @stevieflow! Colours were not explicitly listed for all states of the links (eg. previously visited links).

This should now be fixed and live.
