### ISSUE TITLE
On Search function - when discovering results, maps to show data for all years

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#316]
Instead of showing data for 2015 only

**Comment by Mattdevinit** [comment]
@xriss will changing this to all years instead of just 2015 slow it down to any considerable degree?

**Comment by notshi** [comment]
Confirming that this is for the two graphs, not the map (since map already shows data for all years).

Also, no, it shouldn't slow things down by doing this.

**Comment by Mattdevinit** [comment]
Yes - correct, just for the two pie charts, thanks

**Comment by notshi** [comment]
Thanks, pie charts with all data is now live.
