### ISSUE TITLE
Search - remove initial results when loading page?

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#322]
Currently when loading the page it says "Found 636531 activities" and you can click 'Discover results' to see info on all activities.  Can we remove the search here so that it's not finding any activities/doesn't allow you to click the 'Discover results' button until having typed/added a filter?

**Comment by Mattdevinit** [comment]
This should prevent people just clicking 'Discover results' first off and getting a page which is quite slow (as it tries to load all activity info!)

**Comment by Mattdevinit** [comment]
Make Discover Results button inactive until a search is done

**Comment by notshi** [comment]
Done
