### ISSUE TITLE
Remove CRS column for Search results?

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#323]
when searching and getting through to the table of results, we could remove the CRS column in the table eg here
http://d-portal.org/ctrack.html?search&sector_code=31165#view=donors
Not essential!

**Comment by notshi** [comment]
This also holds true for Sector tables for Publisher portals since you need countries to sort the data.

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
