### ISSUE TITLE
Add facility for " searches

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#324]
I think the search currently works as if it included a + (eg it searches for Hurricane+Matthew if you type 'Hurricane Matthew'?)
Add " function to allow for searching a specific phrase only, eg only finding activities which include the phrase "Disaster Risk Reduction"

**Comment by benparkergit** [comment]
This doesn't seem very happy: http://d-portal.org/ctrack.html?search=%22World%20Humanitarian%20Summit%22#view=main

**Comment by Mattdevinit** [comment]
thanks @benparkergit - Search should be live on the main site next week and will include instructions on which search terms to use.  as described above and as your search shows, using "" at the moment doesn't work - but searching world humanitarian summit without the "" should give results?

**Comment by Mattdevinit** [comment]
this will be fixed with #320 so that "" can be used (will add note on the site explaining what the various functions do/what will be developed in future)
