### ISSUE TITLE
Show text search when going Back

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#325]
eg when typing a text search (without using dropdown filters) and clicking to 'Discover results' - if you then (in Mozilla at least) hit Back in the browser to go back to the main Search page it shows the amount of results but not the text you are searching in the text box...
![hm search empty](https://cloud.githubusercontent.com/assets/3502991/20486567/337fa378-aff8-11e6-9352-938dfd1ff84d.PNG)
should show as below 
![hm search text](https://cloud.githubusercontent.com/assets/3502991/20486615/54409a54-aff8-11e6-9cec-6f8e1e7f05d9.PNG)
(which is what you get if you then click in the text box and then on 'Found x activities')

**Comment by notshi** [comment]
This is down to Mozilla's Firefox design where it over-caches your previous pages. 

Since we now have the 'Refine Search' button for each search request, maybe this is of less importance.
