### ISSUE TITLE
D-portal titles of related-activities

### ISSUE THREAD

**Issue by Akerman** [devinit/D-Portal#332]
Please add activity titles in parenthesis for related-activity

**Comment by notshi** [comment]
Hi @Akerman, thanks for the feedback -

Could you give a link to an example activity?

**Comment by Akerman** [comment]
The same core activity from UNFPA as we were discussing before please.

-Martin

**Comment by Akerman** [comment]
http://d-portal.org/q.html?aid=41119-CORE-PROGRAMME

-Martin

**Comment by notshi** [comment]
Thanks for the link.

Looks like there isn't a title element attached to each related-activity. SAVi only displays data published in the activity itself so it is not designed to fetch and display external information.

![related-activity](https://cloud.githubusercontent.com/assets/1515961/20717520/a7275f2c-b64d-11e6-8899-23213b108762.png)

cc @stevieflow - is a title allowed in related-activity ?

**Comment by Akerman** [comment]
Time to step up data quality with a table that stores unique activity-id*, start date*, end date,  budget, impl status, title, description, total com, total disb, total exp. -- maybe the country data too...

-Martin

**Comment by stevieflow** [comment]
@shi - the ``related-activity`` element doesn't seem to have any ``narrative`` element : http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/related-activity/

**Comment by Mattdevinit** [comment]
@shi @Akerman thanks for this - there's a minor upgrade to the IATI standard planned for early next year and we've suggested this includes a narrative element for related-activity.  This would probably be a better solution as it would then be contained in the raw publisher's data as well as shown in visualisations like d-portal

**Comment by andylolz** [comment]
@notshi wrote:
> SAVi only displays data published in the activity itself so it is not designed to fetch and display external information.

Could SAVi fire off a bunch of async requests for this info? Obviously in this case that’s ~3,000 requests… 😕  but maybe they could be staggered, or load on demand or something?

**Comment by notshi** [comment]
@andylolz As you've noted, this is an expensive thing to do so unless this is of high priority / demand, then we'd rather not.

And **if** it is in demand, I'd probably preprocess the data and squirt it into the XML we're using so it doesn't hit so many requests.

**Comment by notshi** [comment]
Look into adding if/when narrative element approved for related-activity. Will create a fresh, new issue when that happens.
