### ISSUE TITLE
Update homepage text - Search, and notes

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#336]
1 - Add text at top introducing d-portal and new Search function
2 - Update text at the bottom of the page

**Comment by notshi** [comment]
Do we have text for the bottom of the page?

**Comment by Mattdevinit** [comment]
Just to amend this sentence please from
"Data in the dropdown menu is built from the database which updates everyday at GMT +0 with new data fetched from the IATI Registry. "
to 
"Data in the search function and dropdown menus is built from the database which updates everyday at GMT +0 with new data fetched from the IATI Registry."

**Comment by notshi** [comment]
Thanks, should be live now.
