### ISSUE TITLE
Numeric mismatches - Discover results and active projects

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#338]
Just checking through some numbers when using dropdown filter - comparing stated number of search results, with active projects on the subsequent page.  Is there any reason these would be different?  Tends to not be from Publisher list, where they match up exactly, and is for some not all in other dropdowns.
Some examples as follows -
Sector Category...
General Budget Support - 2393 activities found / 2536 Active projects
Humanitarian - 64422 / 101430
Recipient country...
Algeria - 1161 / 1373
Kenya - 12534 / 13241
Sector...
Low-cost housing - 938 / 998

**Comment by Mattdevinit** [comment]
these all seem fine now!

**Comment by notshi** [comment]
Thanks - this was due to double counting. Should be fixed now.

Btw - there was a data issue with the number of publishers listed in the stats where we were counting those with reporting-ref as "null". This is also now fixed.
