### ISSUE TITLE
Sector maps staying on same page (when clicking) instead of going to table

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#341]
Doesn't seem to happen for blue pie charts, but sometimes green ones just scroll back up to top of same page, instead of going to table
eg for me here
http://d-portal.org/ctrack.html?search&publisher=XI-IATI-OFID#view=sectors
and 
http://d-portal.org/ctrack.html?search&funder=AsDB-Special-Funds#view=sectors

**Comment by notshi** [comment]
Fixed.
