### ISSUE TITLE
Adding additional narrative info to Results in Savi

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#342]
There's an additional section of narrative within the Results element, need to add this in Savi underneath where the metrics (Target, Actual, etc) show on each Result (this narrative is often large chunks of text, but will add important context to the Results data).  eg on this page
![results data - further narrative](https://cloud.githubusercontent.com/assets/3502991/20719115/e7cee0f4-b652-11e6-9e21-97e60f1cdea4.PNG)
we would include the following highlighted text in the xml
![results - additional narrative](https://cloud.githubusercontent.com/assets/3502991/20719244/3bf7b05c-b653-11e6-9138-3765de254842.PNG)

**Comment by notshi** [comment]
Sure thing, could I get a link for the example?

**Comment by notshi** [comment]
Got it from search :} - is this it? http://d-portal.org/ctrack.html?search&publisher=GB-CHC-274467&year_min=2016&year=2016&year_max=2016&year=2016#view=act&aid=GB-CHC-274467-GB-XUKDU15001

**Comment by notshi** [comment]
Would be good to have a link to an activity that has a complete 'result' element (http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/result/title/) for some context to figure out the best way display this. If you find any, do send it my way, thanks!
