### ISSUE TITLE
Get feedback on usefulness of dropdown (from freetext search box)

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#346]

**Comment by benparkergit** [comment]
It's a nope from me...

**Comment by notshi** [comment]
@benparkergit Not sure if you've seen this but we have this option under the fold of the "Find out more" link where autosuggestion is also turned off.

http://d-portal.org/ctrack.html#view=freetext

**Comment by notshi** [comment]
How is this coming along?
