### ISSUE TITLE
Improve visuals when interacting with Discover

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#347]
ie. adding 'Filter Added!' as visual feedback when you select something from the dropdown, "2 filters added... 3 filters... etc".

**Comment by Mattdevinit** [comment]
- [ ] '{number} filters added' when selecting from dropdowns
- [ ] box out freetext search to make a bit more obvious where to type for new users

**Comment by Mattdevinit** [comment]
@notshi might be worth adding to the ... which shows when searching/having chosen filters, to show a bit more that the search is going on?

**Comment by Mattdevinit** [comment]
@notshi final tidying up/rounding of filter boxes on new search

**Comment by Mattdevinit** [comment]
@notshi the white box which drops down when typing the freetext search box has come a bit detached from the freetext box itself

**Comment by notshi** [comment]
@Mattdevinit 

Updated explore with various improvements, including tidied filter boxes, fixed detached box .
