### ISSUE TITLE
Displaying more information and stats when you press 'Enter' on Discover

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#349]
more than just 'Found xxxx activities' - include a small snippet below the fold 'Found xxx publishers, xxx active projects, xxx sectors' as user types. This will be on the same page so you can then filter further; eg. pick 'Active' from there and get directed to the page you want instead (one less click!)

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
