### ISSUE TITLE
Add 'clear all filters' button on Explore

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#350]
To remove all currently selected filters

**Comment by Mattdevinit** [comment]
@xriss using the 'clear filters' button is also currently killing the search in the new version (in same way 123/ABC button is)

**Comment by notshi** [comment]
@Mattdevinit This, as well as the ABC/123 toggle button, is now fixed.

**Comment by Mattdevinit** [comment]
@notshi great, thanks - only issue I can still see with this is in IE (IE version 11.0.9600), no probs in Chrome/Firefox, sometimes makes the dropdowns go blank
