### ISSUE TITLE
Titles with '&' are truncated in project overview

### ISSUE THREAD

**Issue by rolfkleef** [devinit/D-Portal#352]
As I am checking some projects at http://d-portal.org/ctrack.html?search&publisher=NL-KVK-41207989#view=active I see a couple of projects with titles truncated at the `&`:

![image](https://cloud.githubusercontent.com/assets/223935/22423996/c149c44e-e6f4-11e6-887f-5dd803cb4d0c.png)

These should be shown as different projects with titles like "PITCH H&O Uganda UNYPA", "PITCH H&O Uganda NAFOPHANU", etc.

**Comment by Mattdevinit** [comment]
thanks @rolfkleef for flagging that, not come across that issue before but will get this corrected

**Comment by Mattdevinit** [comment]
linked to use of '&' - @xriss to fix
