### ISSUE TITLE
Check code - sector searches

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#355]
To investigate @stevieflow query on Discuss...

For example, when I select these I get:

    Just category Ag & Food Security (311): 32,167 results
    Just sector Agricultural Development (31120): 6,469 results
    Both 311 & 31120: 6,447 results

I'm thinking that evidence of a sector code (eg 31120) means that a sector category (eg 311) is then inferred. d-portal is not checking/counting for instances of the explicit use of the 311 code? With this in mind, the slight discrepancy of the above numbers is worth checking - I wonder what the other 22 activities have!

**Comment by notshi** [comment]
Might have found out what's happening here - @stevieflow @Mattdevinit 

The [22 activities](http://d-portal.org/ctrack.html?search&sector_code=31120#view=list_activities&reporting_ref=XM-DAC-301-2) are all coming from one publisher - **XM-DAC-301-2** (Canada - International Development Research Centre/Centre de recherches pour le développement international)

Looking at the structure of their published sector elements, there seems to be a space before the actual sector codes. This is enough to create the slight discrepancy!

![sector_spaces](https://cloud.githubusercontent.com/assets/1515961/23129025/05b8639e-f779-11e6-9f86-b0a78996b718.png)

We have two choices -
1. Ignore the spaces for them
2. Inform XM-DAC-301-2 about this and ask them to republish without spaces

I recommend we do both.

**Comment by Mattdevinit** [comment]
thanks @notshi that's a great spot!  Yes, agreed that we should do both - are you ok to sort out ignoring the spaces for now, and I'll arrange for someone to contact them?

**Comment by notshi** [comment]
Sounds good @Mattdevinit - we will do just that.
