### ISSUE TITLE
UI does not display on slowed connection

### ISSUE THREAD

**Issue by hayfield** [devinit/D-Portal#356]
When hard refreshing a page on D-Portal with a very slowed connection, the UI does not display even after relevant data has loaded.

To test (in Chrome):

* Open the [Dev Tools](https://developers.google.com/web/tools/chrome-devtools/) and switch to the `Network` tab
* In the [Throttling drop-down](https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions#emulate_network_connectivity) select `GPRS`
* Hard-refresh the page (Cmd/Ctrl + Shift + R)

Watching the Network tab, the page will spend ~3.3 minutes loading `ctrack.min.js` with a white page (this isn't great - there should be at least some visual indication that the page is loading). Upon having loaded this script, whatever triggers the next step in page loading does not appear to activate, leaving an empty page.

If a soft refresh (Cmd/Ctrl + R) is then undertaken, the page will display correctly.

**Comment by notshi** [comment]
Thanks very much, @hayfield - will see what we can do to make this better.
