### ISSUE TITLE
Update pie charts to 2016 data

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#357]
Can move these on a year now from 2015 data

**Comment by Mattdevinit** [comment]
Getting CRS data for 2015 w/c 20th Feb, will update pie charts then

**Comment by Mattdevinit** [comment]
+ move on tables one year

**Comment by Mattdevinit** [comment]
CRS data now ready - updates to be done across site as follows

- [ ] Move all tables on one year

- [ ] Update CRS data to 2015 data

- [ ] Move all pie charts on one year to 2016

**Comment by notshi** [comment]
CRS data for 2015 is now live on the site. Please check if all looks ok and close, thanks!

**Comment by Mattdevinit** [comment]
Great - thanks!
