### ISSUE TITLE
failed while "Run the localhost server"

### ISSUE THREAD

**Issue by skanthb** [devinit/D-Portal#360]
Srikanth Boddupalli@DESKTOP-9UB1V3M MINGW64 ~/D-Portal (master)
$ ./serv -q http://d-portal.org/

> ctrack@0.0.1 build C:\Users\Srikanth Boddupalli\D-Portal\ctrack
> node js/bake.js && node node_modules/browserify/bin/cmd.js -r ./js/ctrack.js:ctrack -d -o jslib/ctrack.js && node node_modules/uglify-js/bin/uglifyjs jslib/ctrack.js -o jslib/ctrack.min.js

Adding cmn tongue
Adding eng tongue
Adding fra tongue
Reading text/general.html
Adding hin tongue
Adding jpn tongue
Adding spa tongue
Reading text/view_act.html
Reading text/view_active.html
Reading text/view_dash.html
Reading text/view_dash_cronlog.html
warning chunk name is used twice, css
Reading text/view_dash_quality.html
warning chunk name is used twice, css
Reading text/view_data_quality.html
Reading text/view_districts.html
Reading text/view_donors.html
Reading text/view_donor_activities.html
Reading text/view_donor_budgets.html
Reading text/view_donor_transactions.html
Reading text/view_ended.html
Reading text/view_frame.html
Reading text/view_generator.html
warning chunk name is used twice, css
Reading text/view_list_activities.html
Reading text/view_list_budgets.html
Reading text/view_list_publishers.html
Reading text/view_list_transactions.html
Reading text/view_main.html
Reading text/view_map.html
Reading text/view_missing.html
Reading text/view_planned.html
Reading text/view_publisher.html
Reading text/view_publishers.html
Reading text/view_publisher_countries.html
Reading text/view_publisher_sectors.html
Reading text/view_search.html
warning chunk name is used twice, crumbname_start
Reading text/view_sectors.html
Reading text/view_sector_activities.html
Reading text/view_sector_budgets.html
Reading text/view_sector_transactions.html
Reading text/view_test.html
Writing json/chunks.json
Writing json/tongues.js
Error: Cannot find module 'node-expat' from 'C:\Users\Srikanth Boddupalli\D-Portal\dstore\js'
    at C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at Object.oncomplete (fs.js:107:15)

npm ERR! ctrack@0.0.1 build: `node js/bake.js && node node_modules/browserify/bin/cmd.js -r ./js/ctrack.js:ctrack -d -o jslib/ctrack.js && node node_modules/uglify-js/bin/uglifyjs jslib/ctrack.js -o jslib/ctrack.min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ctrack@0.0.1 build script.
npm ERR! This is most likely a problem with the ctrack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node js/bake.js && node node_modules/browserify/bin/cmd.js -r ./js/ctrack.js:ctrack -d -o jslib/ctrack.js && node node_modules/uglify-js/bin/uglifyjs jslib/ctrack.js -o jslib/ctrack.min.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctrack
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! cwd C:\Users\Srikanth Boddupalli\D-Portal\ctrack
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm
Srikanth Boddupalli@DESKTOP-9UB1V3M MINGW64 ~/D-Portal (master)

How do I resolve this?

Thanks,
Srikanth

**Comment by notshi** [comment]
Hi @skanthb, thank you for this report!
```

Error: Cannot find module 'node-expat' from 'C:\Users\Srikanth Boddupalli\D-Portal\dstore\js'
at C:\Users\Srikanth Boddupalli\D-Portal\ctrack\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
```

This looks like an npm issue. Not sure if the code works very well on windows - we've not aggressively tested on the operating system so might have incompatibilities - apologies.

Making sure you have the latest version of node may help fix this.
