### ISSUE TITLE
Prevent autofill in freetext search when typing reduces options to 1 result

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#362]
eg when typing 'aas' then autofills in the search box for 'Aasaman Nepal' as the only remaining result.  Remove the autofill for all results (but for now keep the dropdown with suggestions - mixed feedback on this but as the search performs a different function to the dropdowns it seems to be worth keeping this for now)

**Comment by notshi** [comment]
We've disabled autofill for the search box - this is now live.
