### ISSUE TITLE
Remove duplicate dropdowns on front page

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#363]
These are now available in the main filters so can be removed from front page

![dropdowns to remove](https://cloud.githubusercontent.com/assets/3502991/23338474/3b4cb200-fc04-11e6-8371-1c226d4dcced.PNG)

**Comment by stevieflow** [comment]
+1 - esp now that https://github.com/devinit/D-Portal/issues/378 resolves to the same view
