### ISSUE TITLE
For Search results - reroute to publisher or rec country homepage 

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#366]
In order to provide more information when clicking the Search button, and to fix issue of sometimes seeing less useful pie charts on the subsequent results page (eg when searching on a publisher and getting the pie chart showing 'where does the money come from' - eg one publisher) ...
Add all 3 pie charts for all search results pages as follows (below the stats)
Where does the money go to? (recipient country)
Where does the money come from? (publisher)
Where does the money go to (sectors)

(but keep two pie charts as currently, for rest of site)

**Comment by Mattdevinit** [comment]
Amended - to reroute to existing publisher or recipient country homepages (to reduce confusion, following user feedback) if only one publisher or rec country is selected from dropdowns

**Comment by notshi** [comment]
This is now live. Search results now reroute to generic pages with expected graphs. Should probably add more information about specifics in the Search FAQ.
