### ISSUE TITLE
Use rounding on calculations so that total %s = 100

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#367]
eg http://www.d-portal.org/ctrack.html?publisher=XM-DAC-41140#view=publisher total on pie charts = 98%.  Change to using rounding so that these pie charts always = 100%

**Comment by xriss** [comment]
Switched to round so its a bit better, but, these percentages are always going to be off a bit eg.

Say we have 3 numbers all the same and we display them with percentages of there total like so.

1000 (33%)
1000 (33%)
1000 (33%)

We would need to pick one of these to be displayed as 34% if you want the percentages to to add up to 100%

I've added an accumulative rounding error so this happens...

**Comment by notshi** [comment]
Rounding is now updated and live on the site.
