### ISSUE TITLE
SQLite bug

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#369]
Number at top of page does not match number of activities; ie.
http://localhost:1408/ctrack.html?search&sector_group=311&publisher=GB-GOV-1#view=active

**Comment by robredpath** [comment]
We use SQLite as the database in OpenAgBox, so we may find things that have broken since the live d-portal has been switched to Postgres. @tobybatch

**Comment by notshi** [comment]
How goes the switch to Postgres?

**Comment by robredpath** [comment]
@tobybatch ^^

**Comment by notshi** [comment]
Closing as SQLite is deprecated and we will no longer support it.
