### ISSUE TITLE
Search for activity identifier

### ISSUE THREAD

**Issue by rolfkleef** [devinit/D-Portal#370]
As a user I want to search for an activity identifier so that I can quickly find all details of a project in an overview I downloaded.

It is possible to search for an organisation identifier. But when I download a list of projects after searching for (for instance) a country, I only have titles and activity identifiers. To then look up details, I can search for an activity title, but these often are not unique, and it's not possible to determine from the list which is the activity I'm looking for:

![2017-03-22_01](https://cloud.githubusercontent.com/assets/223935/24220454/93a67b9e-0f4a-11e7-8465-c86105597b25.png)

**Comment by rolfkleef** [comment]
As an afterthought: having a column with the d-portal URL for a project as an extra column in a spreadsheet download may be even easier for the user?

**Comment by notshi** [comment]
Hi @rolfkleef, many thanks for your thoughts. This is a great idea and is on the list of things to do for the search feature.

As for the extra column - we thought about adding extra information like d-portal specific URLs but decided against it to keep it consistent; ie. you just get what you see on the page.

Previously we did things like convert publisher names to publisher ids but that didn't go down well with users.

Instead advanced downloads that include extra columns should be an option via **q**. We might take a look at creating a friendly interface for users & analysts for such things next after we've stabilised the search feature.

**Comment by YohannaLoucheur** [comment]
+1 on this request.

**Comment by reidmporter** [comment]
+3 (James, Reid, and Aria) on this request.

**Comment by Mattdevinit** [comment]
@rolfkleef @YohannaLoucheur @reidmporter quick update - thanks for your input, as a first step on this the search will soon be widened to cover activity-id, which should mean that searching for an IATI identifier on the text search will find that specific activity as requested.  This is now part of our current phase of work updating the search function, so hopefully will have progress in the next couple of weeks

**Comment by Mattdevinit** [comment]
@rolfkleef @YohannaLoucheur @reidmporter it needs tidying up and we're still working on the aesthetics (including the 'found 0 activities' bit!) but you should be able to paste an activity ID into the search box and get option to see result now.  It'll be part of a fuller package of updates to the Search pushed live/publicised later in August - but flagging it for you now as although it's a bit unfinished I'm on leave after today so thought you might want to use it

**Comment by rolfkleef** [comment]
Thanks, great to see this!

BTW: I still think it also makes sense to have the URL in the spreadsheet download to remove a copy-switch application-open d-portal-paste-click sequence: in the overview on screen I can just click to open the details, would be nice to do that from the spreadsheet too :-)

This was brought up by one of the country delegates at the TAG when I was going over d-portal with him: he downloads sector-specific or organisation-specific lists of projects from d-portal to explore, but then has a hard time finding the project details from the spreadsheet overview. Having those details just a click away would lower friction considerably!

**Comment by reidmporter** [comment]
Cool! I'm sure you know this but it's still a bit strange...

1. Enter an IATI ID in text search
2. Click Discover Results
3. Return 0 results
or
1. Enter an IATI ID
2. Hit enter
3. Get "Found 0 activities" (as you mentioned) and a new button that says "View activities with this IATI ID" or whatever

But I do appreciate the heads up that the function is there even if the aesthetics are still a WIP:)

**Comment by Mattdevinit** [comment]
@xriss on new activity ID search, fix breadcrumb trail eg currently showing 
{crumbname_search2} > Activity

**Comment by Mattdevinit** [comment]
@xriss @notshi add URL to download spreadsheet throughout site

**Comment by notshi** [comment]
@Mattdevinit re:breadcrumb trail

This is only going wrong because that's a test page (hence, ..._search2). It should fix itself when the new search goes live.

**Comment by Mattdevinit** [comment]
@rolfkleef @YohannaLoucheur @reidmporter searching for an activity ID should now work just by pasting it in and hitting enter/clicking outside the box - this will take you directly to that activity rather than 'showing x activities' etc

**Comment by Mattdevinit** [comment]
@rolfkleef also URL has been added to CSV downloads as suggested, thanks
