### ISSUE TITLE
IATI identifiers are not correctly URL encoded

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#373]
The family tree of http://d-portal.org/q.html?aid=US-8-EG-30 lists an activity with identifier `US-8-EG-30-2.00201140947001E+15`. The href on the link is:
http://d-portal.org/q.html?aid=US-8-EG-30-2.00201140947001E+15

When it should be:
http://d-portal.org/q.html?aid=US-8-EG-30-2.00201140947001E%2B15

I.e. the ‘+’ is not URL encoded as ‘%2B’.

**Comment by notshi** [comment]
Thanks - we are aware of this.

Yes, we should escape it but there is also the bigger issue of publishers restricting characters in their ids.

Personally, I believe this is an IATI standard problem and they should be discouraging such practises.

**Comment by andylolz** [comment]
> but there is also the bigger issue of publishers restricting characters in their ids.

There’s a discussion about that very issue [right here](https://discuss.iatistandard.org/t/iati-identifiers-should-not-be-allowed-to-contain-special-characters/649). You can read the outcome of the discussion at standards day in [cell J76 of this spreadsheet](https://docs.google.com/spreadsheets/d/1RRE5IjyirIp-JFRF94JUNL6IEKnEU42uGzlWoj1yJ0A/edit#gid=0). But in sum: for better or worse, it probably won’t be addressed by the standard.

**Comment by notshi** [comment]
Well, of course they aren't. I guess it might take a while for us to fix this too.

*nudge nudge wink wink*

**Comment by notshi** [comment]
I guess it's been a while - this is now fixed.

**Comment by andylolz** [comment]
It’s true! :tada: :tada: :tada:
