### ISSUE TITLE
Sort 'Sector Category' dropdown by numeric code, or provide option to do this (currently alphabetical)

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#377]
Suggestion that DAC 3 digit codes are used as the prefix in this dropdown, so that sectors here are grouped more intuitively for those familiar with DAC data structure 

OR 

that this is an option for how to order this list (eg either alphabetically or by DAC code, for user to select)

**Comment by YohannaLoucheur** [comment]
The order in which the sectors are listed on D-Portal is really problematic.

The actual DAC codelist has a logic to its structure – codes are grouped by number. Listing codes alphabetically forces people to scroll down from eg 31120 Agricultural development to 31162 Industrial crops/export crops, when in fact these two codes should be very close to each other, as can be seen by their numbers.

Anyone working with DAC codes is familiar with their intrisic structure and would expect them to be presented in a similar way. 

Offering both options – by code or alphabetically – would be a neat solution indeed.

**Comment by stevieflow** [comment]
I support the default to be ordered by numeric code - as @YohannaLoucheur points out, the list then flows more reasonably / logically for the user

**Comment by Mattdevinit** [comment]
Thanks @YohannaLoucheur and @stevieflow - this issue is here in GitHub as we do plan to address it (and agree the best solution is an option for both alphabetical and DAC order), but it's not in as an urgent priority bearing in mind various other requests/updates/fixes and limited dev time.  The reasons for that are:-
More people are familiar with alphabetical than with the DAC structure, and we need to consider a wide variety of users on d-portal
All other dropdowns on the site are in alphabetical order, so provide consistency for users
Functionality to find a sector is there already, either by searching in the list or typing the DAC code in the dropdown box

**Comment by YohannaLoucheur** [comment]
Hi Matt

Sorry but I have to disagree with the reasoning here.   

Listing the sectors in alphabetical order actually makes it MORE difficult for people unfamiliar with DAC codes to find what they want. They need to know the exact name of the sector they (think they) want, and the names of the other sector(s) close to it (actually, they need to know these other codes exist in the first place).  This requires having the proper DAC code list close by, in print or on screen.  To use an analogy, if projects were coded with the Dewey system, we would not list the Dewey sections and divisions in alphabetical order, would we?

I would be curious to see the evidence that more people are familiar with alphabetical than with the DAC structure. Has their been user testing, consultations etc?

**Comment by Mattdevinit** [comment]
thanks @Yohannaloucheur 

As well as the list, users at any level can already type in the dropdown's box and very quickly get the sector they want if they know the name, or to a list of sectors from a more general keyword they are interested in (eg type in education and it gives you all sectors with education in).  Because that functionality already exists, this request is not seen as a higher priority than other user requests for features not currently available, such as #348 allowing selection multiple options from dropdowns or #364 to be able to filter by project status.

My feeling is we need to try and make the site (and IATI data generally) as open and usable as possible to any users across the world, including people who don't particularly know or care what DAC or IATI stand for but who want to see and explore development data for whatever reason (it's on that global basis that I think more people would know an alpha list than DAC codes). 

All that said ... this request is already cued up to be done in the current round of Search function updates, so we're only really discussing when rather than if!

**Comment by YohannaLoucheur** [comment]
As mentioned before, it's precisely to make the site more usable for everyone what we recommend respecting the hierarchy of the DAC list. It would much increase the chance that people will see a sector that is a better match to their needs than what they found initially by using some random word, especially something like "education" that appears in many sectors, or "health" that does NOT appear in some sectors from the health category.

Since a lot of the problems with the D-portal come from misunderstanding user needs, I would expect feedback provided by users to be taken more seriously.

**Comment by stevieflow** [comment]
I think it would be useful to keep this thread on the initial request, and not steer into issues of user needs or the usability of IATI data (which are no doubt important)

Therefore, I understand that the proposal looks like:

- to enable the sector and sector category drop downs to be ordered by the numeric code 
-- either by default
-- or via a function 

And that:

> this request is already cued up to be done in the current round of Search function updates, so we're only really discussing when rather than if!

It seems like our task is to just make sure the above is specific enough for implementation

**Comment by Mattdevinit** [comment]
@YohannaLoucheur @stevieflow there's now an ABC button in the filters box which you can click to toggle between alphabetical order for dropdowns, or numerical code order (eg for CRS codes)
