### ISSUE TITLE
"Where does the money come from" graph accessible via a publisher view is misleading people

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#378]
I have observed people selected their organisation from the publisher drop down in the filters - eg:

![2614](https://cloud.githubusercontent.com/assets/1209944/26236940/db065c50-3c6a-11e7-8f06-4cae98464a17.png)

This is different from selecting the publisher directly from the "search for a publisher" list/drop -down

The result is that the page http://d-portal.org/ctrack.html?search&publisher=XM-DAC-41301#view=main contains a pie chart for "where does the money come from", which seems to always be 100% for that publisher:
![pie](https://cloud.githubusercontent.com/assets/1209944/26236984/119cac92-3c6b-11e7-8fbd-f71157101943.png)

This has the potential to mislead people, as it seems this is really about the data source rather than the "money".

**Comment by Mattdevinit** [comment]
thanks @stevieflow - is the confusion around the numbers here then, or seeing something people didn't expect?  part of the current development is to show the more useful other pie chart in a search like this (eg in this case 'where does the money go') #366 although currently this would be in addition to showing this one

**Comment by stevieflow** [comment]
Thanks @Mattdevinit 

I think it's confusion of the unexpected.  For this use case, the money *doesn't* come from themselves. 

In the actual IATI data, it's probably also the case that the Incoming Funds

The same happens for other "publishers":

http://d-portal.org/ctrack.html?search&publisher=41122#view=main

On speaking to @notshi & @xriss about this - I think this is just a "glitch" in terms of the page you are provided when you "just" select a publisher from the filters.  In effect, this pie chart should be suppressed, or the user directed through to 

http://d-portal.org/ctrack.html?publisher=XM-DAC-41301#view=publisher

NB: The "where does the money from" graph *is* useful to publishers who look at their own data, I think - but this specific graph is more about data source than source of funds

**Comment by stevieflow** [comment]
Further to this, I also understand that this graph relates to the *publisher* (reporting-org) rather than the provider-org of a transaction.  This probably misleads people - as we're mixing data source with finance source?

**Comment by notshi** [comment]
Hi @stevieflow - the new update is now live on d-portal (https://github.com/devinit/D-Portal/issues/366).

Updated eg: http://d-portal.org/ctrack.html?search&publisher=XM-DAC-41301#view=main

Hopefully it alleviates the previous confusion.

**Comment by stevieflow** [comment]
That's great, thanks @notshi @Mattdevinit
