### ISSUE TITLE
Sort transactions for any activity

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#379]
As someone who uses d-portal to look at individual actitivities, I would like the function to be able to sort any of the columns within the transaction table (A-Z , Z-A) in order then by date, type, provider, receiver or value.  I would specifically like to do this so I can see all Incoming Funds together in one grouping, for example

**Comment by stevieflow** [comment]
bump.... !

**Comment by stevieflow** [comment]
The more I use d-portal, the more useful this would be

**Comment by stevieflow** [comment]
I'd really like to see this function!

**Comment by notshi** [comment]
Thanks, @stevieflow - this might take some time but for the moment, transactions are now grouped by type.

Example - http://d-portal.org/ctrack.html#view=act&aid=NL-KVK-40594571-WAI2016

**Comment by stevieflow** [comment]
Thanks @notshi - interesting

( I suspect some users will also value the chronological list of all transactions - it's a tricky one)

In terms of Incoming Commitments then I'd suggest to position them above the Incoming Funds, in this view.  This makes more sense, as *generally* an IC will link to some IF, as OC relates to D.  

The example activity you cite is very interesting for its completeness.

**Comment by notshi** [comment]
Thanks, @stevieflow.

We're currently ordering them by transaction type code according to the standard; [1 - 13](http://reference.iatistandard.org/203/codelists/TransactionType/).

If we are to move code 11 before code 1, how should the rest be ordered?

**Comment by stevieflow** [comment]
Thanks @notshi 

Yes, understood.  Transaction Type 11 (Incoming Commitment) was added in a later version of the standard, hence why it has a latter code.  It "pairs" well with Incoming Funds, so I think it's an isolated case to reposition

NB: There is also the Incoming / Outgoing Pledge types, added in a later version of the standard.  However, I think it'd be OK to leave those to 12 & 13, for now

**Comment by notshi** [comment]
Closing this as resolved.
