### ISSUE TITLE
Download csv file - adding data

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#382]
The csv download function is very useful

For example: http://d-portal.org/ctrack.html?search&sector_code=31165#view=list_activities

To get these 179 activities into a single file is great

It seems that the data points covered in this file are:

> aid	
> title
> reporting
> commitment
> spend
> currency

These are useful - I wonder if they could be renamed though:

> aid	--> activity-identifier
> title
> reporting --> reporting-org
> commitment --> total-commitment
> spend --> total-spend (does this equate to D + E?)
> currency

Additionally, it would be great to also include:

> country-code
> region-code 
> sector-code
> start-date (planned)
> start-date (actual)
> end-date (planned)
> end-date (actual)
> activity-status-code

This would enable someone to grab a file and undertake more analysis and filtering  , for example

NB: a complication on the above is where an activity may have multiple countries, regions and/or sectors

**Comment by YohannaLoucheur** [comment]
In addition to the above, which I fully support, a couple of additional things would turn the csv download function from nice to awesome:
 
- enable user to select fields to exclude from download (eg I may not care about end-date today). These can be hidden/removed once the data is downloaded, but it would be better to do it at source (if only to make a smaller file)

- add **planned disbursements** to D-Portal and then to download. This data is very important to many users, it has enormous potential added value, so it must be accessible via the D-Portal (and datastore for that matter)

**Comment by stevieflow** [comment]
(I've pushed the planned-disbursements issue into a new specific ticket #383

**Comment by stevieflow** [comment]
> enable user to select fields to exclude from download (eg I may not care about end-date today). These can be hidden/removed once the data is downloaded, but it would be better to do it at source (if only to make a smaller file)

I think this would be useful - perhaps also a separate issue, as it covers functionality rather than data.  Shall I do that @notshi ?

**Comment by xriss** [comment]
The CSV downloads are a what you see on the page download, we don't want to change that.

For more detail you can try converting to a query, not overly complicated and I think we have talked about some sort of magic button, for now you can try things like this.

EG, your example

http://d-portal.org/ctrack.html?search&sector_code=31165#view=list_activities

becomes

http://d-portal.org/q.csv?from=act,sector&sector_code=31165&limit=-1

and this country query 

http://d-portal.org/ctrack.html?search&country=AG#view=list_activities

becomes

http://d-portal.org/q.csv?from=act,country&country_code=AG&limit=-1

This is all coming out as it is named and stored in the internal database but should be useful?

**Comment by stevieflow** [comment]
@xriss ok thanks. 

> The CSV downloads are a what you see on the page download

Do we see the total-spend on screen though?  I can only see the commitment

 So the issue isn't so much about *getting* more data in csv format, but the ways and means to export it?

Agree magic button sounds good :)

I have a user story in that I would a group of staff about to go on delegation for a donor.  I'd have 20 minutes to show them how "useful" d-portal is. They value getting data in spreadsheets.  I'd like to get from the button we have now, to a way to export more detail.  Is it - put simply - another button "full data" (or something)

Thanks for answering so quickly

**Comment by xriss** [comment]
> Do we see the total-spend on screen though? I can only see the commitment

There should be a progress bar, comparing spend to commitment but a bug a while back caused problems with it so it got hidden quickly rather than fixed.

**Comment by notshi** [comment]
> Do we see the total-spend on screen though? I can only see the commitment

Looks like we'll need to merge pages again. You should be able to see the total-spend on screen here - http://d-portal.org/ctrack.html?search&sector_code=31165#view=donor_activities

There's plenty of tidying up on d-portal to do to streamline the expected views of certain pages.

> Is it - put simply - another button "full data" (or something)

Going for the latter here. One of the things we want to do is a query builder type thing for d-portal so you can do queries as well as download csv in specified formats (select/choose fields). This will be a big job as it's going to be mostly user interface design and decisions. The functionality is all there, it's just not documented at all.

**Comment by notshi** [comment]
@stevieflow 

Re: http://d-portal.org/ctrack.html?search&sector_code=31165#view=list_activities

Have updated this view to include the total-spend percentages and renamed the csv headers when you download the csv. This is now live.

Added 'activity-status-code' query to the csv download to this view as well.

Did notice a couple of things:

1. ```activity-identifier``` is listed as ```iati-identifier``` in the standard. Does this matter?
http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/

2. ```activity-status-code``` is listed as ```activity-status``` in the standard. Does this matter?
http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/activity-status/

**Comment by stevieflow** [comment]
Thanks all

So - I think I can respond to the latest comment from @notshi 

> activity-identifier is listed as iati-identifier in the standard. Does this matter?
> http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/
> 
> activity-status-code is listed as activity-status in the standard. Does this matter?
> http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/activity-status/

Yes, it would seem good practice to align columns with the standard, where possible (note, ``total-spend`` isn't in the standard, so doesn't need such alignment)

The access to advanced data via the comment from @xriss https://github.com/devinit/D-Portal/issues/382#issuecomment-308211788 is really interesting. I'll create a new ticket for this

**Comment by notshi** [comment]
Updated csv headers to align with the standard.
