### ISSUE TITLE
Add planned-disbursements to d-portal

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#383]
The ``planned-disbursements`` element isn't utilised in d-portal, it seems

@notshi is this the case?

@YohannaLoucheur suggest this in #382 

> add planned disbursements to D-Portal and then to download. This data is very important to many users, it has enormous potential added value, so it must be accessible via the D-Portal (and datastore for that matter)

.. so creating a new issue to investigate / discuss

**Comment by xriss** [comment]
planed disbursements are considered budgets, if budgets are missing for an activity the we use planed disbursements instead.

EG, here are all the planned disbursements from B&MGF publisher as a csv, its a budget with a flag set to plan.

http://d-portal.org/q.csv?from=budget,country&publisher=DAC-1601&budget=plan&limit=-1

So generally when it comes to tables, etc, all the budgets data might include planed disbursements with a bit of logic to stop double counting.

I think they might be missing from the SAVI display, @notshi is taking a look at that, as we should display that.

**Comment by YohannaLoucheur** [comment]
> planed disbursements are considered budgets, if budgets are missing for an activity the we use planed disbursements instead.
> 

I'm talking about this element: http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/planned-disbursement/

In the standard it is not part of budgets, so it's really not clear to me why it would be used in lieu of budgets, especially without warning users.  

Interestingly, when I raised this issue previously, I was told planned disbursements were part of transactions...  

In any case, this rests Stephen's case that the actual element names should be used in downloads.

**Comment by stevieflow** [comment]
I think we should ask @bill-anderson about any decisions taken to treat planned-disbursements as budgets ...

**Comment by notshi** [comment]
Thanks all for inputs - planned-disbursement is now viewable on SAVi.

Examples:
1. http://d-portal.org/ctrack.html?&tongue=eng#view=act&aid=GB-CHC-1092236-GPAFIMP043)
2. http://d-portal.org/ctrack.html?#view=act&aid=NL-KVK-27108436-A-04846-02%3AXG

The decision to treat it as budgets was from @bill-anderson back then when d-portal was first built so this is legacy code.

In any case, we need more context about this element as it is used now. I've kept it basic so it only shows period start, period end and a value.

**Comment by YohannaLoucheur** [comment]
Great, thanks!  This could be a game changer in terms of our staff, and potentially partner country officials, using the D-Portal.

**Comment by stevieflow** [comment]
So - ``planned-disbursements`` now display for relevant activities.  That was the ask of this ticket.  I'm minded to leave open in terms of any budget-related clarification @bill-anderson can add...

**Comment by Mattdevinit** [comment]
thanks all - quick reminder that information about this kind of thing is available, including the current logic for [using planned-disbursement](http://d-portal.org/faq.html#tech1) if no budget data present, in the [FAQs](http://d-portal.org/faq.html) - we've recently made these more prominent generally.

> Interestingly, when I raised this issue previously, I was told planned disbursements were part of transactions...
@YohannaLoucheur was that in relation to d-portal?

**Comment by markbrough** [comment]
I think it is fine to show planned-disbursements if budgets don't exist. We did this in Bangladesh, because in practice donors are using the two fields interchangeably (i.e. some donors use budget and some planned-disbursements for the same sort of data). I think it is good to merge the two when presenting the data as it reduces the burden of having to interpret the data for users.
