### ISSUE TITLE
Listing activities - order by hierarchy?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#384]
Linking to #232 

http://d-portal.org/ctrack.html?search&country=AO&publisher=XI-IATI-EC_DEVCO#view=list_activities

In this instance, the activities from this publisher are listed, but hierachy 1 and 2 and mixed together in the list.  For this publisher. hierarchy 1 activities are the "programme", whereby 2 are the "contracts" underneath each.  Hence, it is useful to see more "important" activities together / at the top of any list, rathe than the multiple small ones

I guess to understand this issue, the first question would be: what informs how the activities are ordered in a list such as http://d-portal.org/ctrack.html?search&country=AO&publisher=XI-IATI-EC_DEVCO#view=list_activities ?

**Comment by robredpath** [comment]
See also #232

**Comment by notshi** [comment]
This relates to [@hierarchy](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/#iati-activities-iati-activity-hierarchy).

Thanks for looking at this - this page needs work! Looks like the list of activities is listed from earliest actual start date at the top.

**Comment by notshi** [comment]
Closed as we are not currently accepting feature requests.
