### ISSUE TITLE
Activity list - make sortable?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#385]
The list of activities - such as http://d-portal.org/ctrack.html?search&country=AO&publisher=XI-IATI-EC_DEVCO#view=list_activities -

Is there a chance to be able to sort this list.  Currently, this would be by the two facets currently listed - title and value.  

#384 could also include an option to include the hierarchy in the list, potentially making this sortable

**Comment by Mattdevinit** [comment]
thanks @stevieflow good idea - we'll default these lists by highest value to low, and allow sorting by those two facets as you suggest.  Added to the list of things to do!

**Comment by robredpath** [comment]
This could be useful for AgBox users who are likely to be viewing lists in the order of 100s-1000s of activities and therefore are likely to want to sort lists!

**Comment by stevieflow** [comment]
I'd like to ping this - I think it would be really useful

**Comment by stevieflow** [comment]
Can I bump this again?

**Comment by stevieflow** [comment]
I'd really like to see this function!

**Comment by Mattdevinit** [comment]
@stevieflow noted, and sorry for the silence!  we'll make it happen shortly

**Comment by notshi** [comment]
Closed as we are not currently accepting feature requests.
