### ISSUE TITLE
Using https for d-portal

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#386]
Change to https to enable wider use of Generator content, poss use free certificates https://letsencrypt.org/

**Comment by notshi** [comment]
HTTPS is now enabled on d-portal.org

**We still support non-https so you can visit the site either or.**

This should let users on secured domains to use Generator content.

Just make sure you go to the secure site:

https://d-portal.org/ctrack.html#view=generator

**Comment by notshi** [comment]
Note: We should add this somewhere on the main site for those who want to use the widgets on their 'secured' internal sites, maybe on the Generator page - @Mattdevinit
