### ISSUE TITLE
Put search box in a box?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#387]
I have observed a number of users completely miss the free text search box on the homepage, possibly because it can look like a underlined title.  This is further compounded by the drop downs below, which cite the term "search"

Suggestion:

- Make the freetext search box visibly obvious by putting this into a box, with no background information.  

An example might be from http://grantnav.threesixtygiving.org/ - although a different context.  Just using to illustrate that the search box is very obvious:

![search](https://user-images.githubusercontent.com/1209944/27370883-4e619d72-5656-11e7-8424-503b41df8b81.png)

**Comment by Mattdevinit** [comment]
thanks @stevieflow - we have one in for this on #347 "box out freetext search to make a bit more obvious where to type for new users" - but very useful to have further confirmation of this need!  
#347 is in the current plan for work being done on the Search function, so will have some progress soon

**Comment by stevieflow** [comment]
Ah, excellent, thanks @Mattdevinit .  Ill close this as duplicate

**Comment by notshi** [comment]
Thanks @stevieflow - just for reference: previous versions of the search included a box but the page, in its entirety looked cluttered with boxes.

![boxes](https://user-images.githubusercontent.com/1515961/27383611-a49b3e64-5683-11e7-90ad-346e92b8a7ef.jpg)

I went with 'not-a-box' with a mind that when we streamlined the page, the box will make its return.

When I designed the grantnav search box example you provided, it was relative to the simplicity of the landing page :}

**Comment by Mattdevinit** [comment]
will help that we're removing the two search boxes below shortly, as in #363
