### ISSUE TITLE
Improved mapping display

### ISSUE THREAD

**Issue by robredpath** [devinit/D-Portal#389]
In the OpenAg Box, we're adding a geocoder which will likely mean that Box users will want to see how their data looks on a map. Everyone loves a map! d-portal should display both the location and the level of granularity - paying attention to the feature designations as well as the points.

**Comment by robredpath** [comment]
This applies on both the aggregate level and the single activity view

**Comment by robredpath** [comment]
And kinda relates to #161

**Comment by notshi** [comment]
Can we have a **live** example activity to work with? This will set context and a direction to head towards.

We are already listing the ```<location>``` element in SAVi ([example](http://www.d-portal.org/ctrack.html?#view=act&aid=44000-P096572)) - could you explain further what is needed by level of granularity?

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
