### ISSUE TITLE
Chrome's 'translate to' function does not work

### ISSUE THREAD

**Issue by VincentVW** [devinit/D-Portal#391]
Kind of a practical flaw; I tried to use Chrome's auto translate to read French descriptions on http://d-portal.org/q.html?aid=46002-P-BF-AAD-006 . It made all content disappear from the page.

This is due to the css line;
`
iati-activity *	{
display:none; 
color:#fff;
}
`

The translate function apparently adds `<font>` dom elements. A simple fix could be;

`
iati-activity font{
    display: inline-block;
}
`
Doesn't seem to mess with the design, and I guess there's some users that use this translate functionality.

**Comment by notshi** [comment]
Hi @VincentVW - many thanks for this.

This is a design choice for SAVi (hiding elements) as it is the original XML pretending to be a webpage.

Translate-to should now be ok on those pages.
