### ISSUE TITLE
Support search and drill-down via additional vocabularies

### ISSUE THREAD

**Issue by timgdavies** [devinit/D-Portal#393]
The search currently appears to auto-complete with DAC sectors.

With the introduction in the Open Ag Funding project of additional supported vocabularies for sector codes, we need to enable search, and drill-down by these additional vocabularies.

Given vocabularies such as AGROVOC are hierarchical, and have some very specific terms in them, this will require some design work to identify whether:

* Search should auto-complete with **all** the possible terms, or just terms from a high enough level of the hierarchy, or with enough activities tagged against them;
* How the option to drill-down to more granular terms is displayed to users;

There will also be a need to consider whether the search (or import process) will expand hierarchical classifications. So - for example, if something is tagged only with 'Runner beans' which, in the vocabulary is a kind of 'Legume', would a search for 'Legumes' return the activity focussed on runner beans? 

Assigning to Rob to triage for the Open Ag Funding development work.

**Comment by notshi** [comment]
Closed as we are not currently accepting feature requests.
