### ISSUE TITLE
Pull in and use French language codelists

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#394]
There’s now complete French language versions of various codelists, including the 5 digit sector codelist:
http://iatistandard.org/202/codelists/downloads/clv3/json/fr/Sector.json

…so presumably it’s feasible to pull that in and use it in the dropdown on [the French language homepage](http://d-portal.org/ctrack.html?&tongue=fra#view=search).

NB [this suggestion comes from tweets](https://twitter.com/andylolz/status/885553845992132608) with @YohannaLoucheur.

**Comment by xriss** [comment]
Should be possible yes, BTW looks like there are some missing bits?

the 920xx 230xx codes 

http://iatistandard.org/202/codelists/downloads/clv3/json/fr/Sector.json

Honestly these codelists do not fill me with confidence, might be worth some sort of push to publish a set of complete codes in multiple languages?

Preferably without RANDOM CAPITALS as seen here http://iatistandard.org/202/codelists/downloads/clv3/json/en/SectorCategory.json

**Comment by YohannaLoucheur** [comment]
Sorry, my computer doesn't know how to open .json files so I can't see what you refer to.  Are you saying the French translation is missing for some codes?  

Do you know if they are in the source (ie DAC) list? If not, it's something to signal to DAC Secretariat to fix asap. French labels have to be available at the time of approval, so there's no reason why they should be missing from the list.

**Comment by markbrough** [comment]
It looks like the 920xx and 230xx codes are missing French-language names because they are withdrawn codes. The great work from @andylolz (which brings codelists up to date and incorporates translations from the latest version of the DAC CRS codelists) would need to be supplemented by IATI by going back and getting names of the remaining codes from older versions of the DAC CRS codelists.

**Comment by andylolz** [comment]
You beat me to it, @markbrough!

**Comment by andylolz** [comment]
@YohannaLoucheur: Apologies! You can view the equivalent XML or CSV:
 * http://iatistandard.org/202/codelists/downloads/clv3/xml/Sector.xml
 * http://iatistandard.org/202/codelists/downloads/clv3/csv/Sector.csv

**Comment by andylolz** [comment]
As mentioned elsewhere, the random capitals are in the source data :'(

**Comment by YohannaLoucheur** [comment]
thanks Andy.  The xml link works, but csv one doesn't (404 error) for some reason

**Comment by andylolz** [comment]
Gah I am bad at URLs. CSV URL fixed now!

**Comment by YohannaLoucheur** [comment]
Should have realized earlier that these are the English codelists.  I assume you meant to provide the French ones?

**Comment by andylolz** [comment]
Gahhhhhh I am even worse at URLs. Actually fixed now:
http://iatistandard.org/202/codelists/downloads/clv3/csv/fr/Sector.csv

But anyway – what @markbrough says: https://github.com/devinit/D-Portal/issues/394#issuecomment-317743116

**Comment by notshi** [comment]
Closing - duplicate #452
