### ISSUE TITLE
Explore - selecting year range affects total projects

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#400]
eg selecting Agriculture and year range 1961-1963 gives stats as 
total projects = 3 
ended projects = 3 
active projects = 4109
https://d-portal.org/ctrack.html?search&sector_group=311&year_min=1961&year=1961&year_max=1963&year=1963#view=main
seems to replicate much higher active projects number when using the year range filters

**Comment by xriss** [comment]
Ahh, yes,

when using a year range the active/ended/planed stats are a bit of a problem because they also use the year range to work out which is which.

So one test gets replaced with the other when we need to do something smarter.
