### ISSUE TITLE
Remember selections when using back / create URL

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#401]
when making selections create URL (for sharing)

and then when clicking to explore results, if clicking back, retain the chosen selections

**Comment by Mattdevinit** [comment]
works great in Firefox, but not yet in Chrome / IE

**Comment by Mattdevinit** [comment]
and if possible remember text from freetext box when using Back?

**Comment by xriss** [comment]
This should be live and working now.

The search url will be updated as you search and can be used to share searches.
There is now a history of searches with browser back working correctly.

Looks good to me but could do with some double checking and stress testing to make sure it is all as expected.

**Comment by notshi** [comment]
Added a 'Refine Search' button to result pages so you can go back to the original search page with the filters remembered.

**Comment by notshi** [comment]
![refine](https://user-images.githubusercontent.com/1515961/34162483-cc91d258-e4cb-11e7-8e9f-617d72776577.png)

That button should work even when the link to that search page is shared around; ie. http://d-portal.org/ctrack.html?search&sector_group=311&publisher=CA-3&status=3#view=main
