### ISSUE TITLE
Savi - use ref rather than activity

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#402]
(link to publisher portals)

**Comment by notshi** [comment]
Related to 'Who's involved?' section in SAVi for [participating-org@ref](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/participating-org/#attributes)

**Comment by notshi** [comment]
@Mattdevinit  This is now live - should we update the footer to include this new change?

[Example] http://d-portal.org/ctrack.html#view=act&aid=GB-CHC-1062638-NPL-Nepal-2015
