### ISSUE TITLE
Amend table column name from 'donor' to 'publisher'

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#403]
In tables such as this http://d-portal.org/ctrack.html?search&country=AO#view=donors can we change the column name from Donor to Publisher (poss issues with new width of column!)
Also to change the tooltip on those cells from 'Source of Funds' to 'Publishing organisation', and amend 'Donor' for 'Publisher' in the explanation text at the bottom of the page

**Comment by notshi** [comment]
This is now live on the site - have also replaced all instances of 'donor' to 'publisher' throughout the site.
