### ISSUE TITLE
Link to FAQ when issues with data quality

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#404]
For example where data doesn't show in the 'Active projects' and 'Ended projects' section below the map (eg https://d-portal.org/ctrack.html?publisher=BE-BCE_KBO-0410644946&tongue=eng#view=main) change the text from 'Read more about data quality' to 'See common reasons for data not showing' and link it to this FAQ http://d-portal.org/faq.html#gen13

**Comment by notshi** [comment]
This is now live on the site.

**Comment by Mattdevinit** [comment]
Thanks @notshi !
