### ISSUE TITLE
Using activity-status for activity status calculations

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#405]
I can see via http://d-portal.org/faq.html#tech8 that the status of an activity in d-portal is determined from the ``activity-dates``

Would it also be prudent to call in the ``activity-status`` field in this too.  It could be that the dates have remained static, but the status field is updated by a publisher.  There might exist a possibility to combine both fields, but place emphasis on status > date

Any thoughts, or previous design decisions, welcomed

**Comment by Mattdevinit** [comment]
Thanks @stevieflow - this came up recently via the support desk too.  The original reason for doing it like this was the opposite of what you mentioned - that originally the dates were used (and updated) by publishers more consistenetly than the status field, but appreciate that this might have changed and that there's potential value in something like a a combination of the two.  There's a bit more discussion (re using Pipeline) on this IATI [tech support issue](https://github.com/IATI/Tech-Support-Q-A/issues/11).   Be interesting to know how well used/maintained the data in Status is.

Another option is somehow giving the user the choice of toggling between using start/end, and status

**Comment by notshi** [comment]
Hi both,

We've got some figures for this -

http://d-portal.org/ctrack.html?search&status=1#view=main

For example, there's a total of 4269 activities that have "Pipeline" as ```activity-status```.

Out of those, only 78 have the 'right' dates and if you choose a random activity from the 3141 ended projects, there are activites that have not updated or used the ```activity-status``` correctly; ie. some of these show transactions that suggest their ```activity-status``` are incorrect.

eg, http://d-portal.org/ctrack.html?search&status=1#view=act&aid=FR-6-MR-744

Majority of the time, ignoring the ```activity-status``` puts them in the right category so if we start honouring the ```activity-status```, we'll put them in the wrong category.

**Comment by stevieflow** [comment]
I think this is still an issue, both in terms of how d-portal calculates this and of course in how publishers maintain their data

One *possible* action could be to revise the logic for how activities are calculated to be in the "Other" category.  For example:

- if a project has status=closed (or post-completion) but an end-date (active or actual) that is in the future, then declare as "Other"
- if a project is in status Implementation, but has an end date (active or actual) that is in the past, then declare as "Other".

**Comment by notshi** [comment]
Closed as data is too unreliable.
