### ISSUE TITLE
Start local dportal

### ISSUE THREAD

**Issue by tobybatch** [devinit/D-Portal#406]
What is the correct way to start dportal listing on a specified server port?

I want to start my docker instance listening on port 8011.

**Comment by xriss** [comment]
You can use the environment by setting DSTORE_PORT=8011 or the command line option --port=8011

https://github.com/devinit/D-Portal/blob/master/dstore/js/argv.js#L31

See link above for the other options that can go in here which let you move the cache and sqlite directories around or switch to the postgres backend.

**Comment by tobybatch** [comment]
@xriss That's excellent thanks,  so I start it with:

    /opt/D-Portal/bin/serv --port=8011

Is that enough?

**Comment by xriss** [comment]
Probably safer to avoid all the bash scripts so you can be sure what is going on, so from within the dportal folder run

	node js/serv.js --port 8011

**Comment by notshi** [comment]
@tobybatch - If this is resolved, can we close this?
