### ISSUE TITLE
Accessing csv output via web interface

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#409]
Re: https://github.com/devinit/D-Portal/issues/382#issuecomment-308211788

> For more detail you can try converting to a query, not overly complicated and I think we have talked about some sort of magic button, for now you can try things like this.
> 
> EG, your example
> 
> http://d-portal.org/ctrack.html?search&sector_code=31165#view=list_activities
> 
> becomes
> 
> http://d-portal.org/q.csv?from=act,sector&sector_code=31165&limit=-1
> 
> and this country query
> 
> http://d-portal.org/ctrack.html?search&country=AG#view=list_activities
> 
> becomes
> 
> http://d-portal.org/q.csv?from=act,country&country_code=AG&limit=-1
> 
> This is all coming out as it is named and stored in the internal database but should be useful?

Accessing this data is really really useful for the users I work with.  It might be possible to explain face-to-face with people how to do this, but that can't scale!

I would therefore advocate strongly for some way to get this data from the web UI.

**Comment by notshi** [comment]
Closed as we are not currently accepting feature requests.

However, one should be able to use [dquery](http://d-portal.org/dquery/) to achieve this.
