### ISSUE TITLE
No fallback for non-javascript browsers

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#410]
I’m just testing the waters with this issue!

Here’s d-portal with javascript disabled:

![screen shot 2017-10-02 at 15 11 28](https://user-images.githubusercontent.com/464193/31085233-7c44a408-a78e-11e7-8ed4-ebc37faaff7b.png)

I’m curious if this has been raised as an issue before? I checked the issue tracker but drew a blank.

**Comment by xriss** [comment]
There used to be some preload content, a long long time ago but it got removed as it would flash up before the js loaded.

I figure People who go around disabling JavaScript know that they are going to break everything and don't really get to complain when that happens, right?

**Comment by andylolz** [comment]
Thanks @xriss! Going to close this one, since it’s pretty clearly a `wontfix` :)
