### ISSUE TITLE
<tag> tags - link

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#412]
I noticed in the presentation of tag classifications that the link is through to the AGROVOC terms of the FAO website.  This might not be the best user experience!

Could it be possible that clicking this tag leads to search results of other activities that share this tag?

**Comment by notshi** [comment]
> This might not be the best user experience!

Might need a word with the FAO peeps about that :}

But yes, this is possible - when there is more data to support development for this.

Also, keep in mind that the presentation will change again as the current version is just a 'prototype'; iteration as more data is published and we know more about the context and how this data is being used.

**Comment by notshi** [comment]
It's been some time - just wondering, would you have some IATI data using the [AGROVOC tag](http://iatistandard.org/203/codelists/TagVocabulary/) to share?

Did a [quick search](http://d-portal.org/q.json?from=element&orderby=element_volume-&limit=10&element_name0=tag) and not seeing any but I may have missed something.

**Comment by k8hughes** [comment]
The AGROVOC tag was added as part of the 2.03 upgrade so only went live a month ago.  I don't think people are using it yet.

**Comment by notshi** [comment]
Thanks, both.

**Comment by andylolz** [comment]
> Just to clarify - the tag element was not specifically designed for AGROVOC

^^ Would you consider renaming this issue, @stevieflow? It’s a bit confusing currently!

**Comment by stevieflow** [comment]
yes, good point @andylolz !

**Comment by notshi** [comment]
Closed as resolved. Please re-open or create a new issue if you find data to support research for development.
