### ISSUE TITLE
Make the reported by field a link?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#414]
On any activity the ``reporting-org`` field is output as: 

![reported-by](https://user-images.githubusercontent.com/1209944/31778424-8796fc7c-b4e8-11e7-8644-1462f056d8aa.png)

Can this be made a link back to the reporting-org "page" on d-portal?

So - from : http://d-portal.org/ctrack.html?search&publisher=44000#view=act&aid=44000-P096965

The link for ``The World Bank`` would be to http://d-portal.org/ctrack.html?search&publisher=44000#view=main

In the XML, I guess this would take the ``@ref`` of the reporting org and insert it into the URL...

**Comment by notshi** [comment]
Yup, thanks - code is in for that earlier. Should be live the morrow.
