### ISSUE TITLE
1.0x participating-org/@role codes not supported / displayed?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#415]
See: http://d-portal.org/q.html?aid=GB-CHC-288701-RW999

![wateraid-org](https://user-images.githubusercontent.com/1209944/31829038-08e311aa-b5b4-11e7-9f3e-f525dd465da3.png)

In this example, the role of each org is missing from the UI - even though it is in the XML:

```
<participating-org role="Funding" ref="GB-CHC-288701" type="21">WaterAid</participating-org>
<participating-org role="Implementing" ref="" type="22">Bugesera District Local Government</participating-org>
<participating-org role="Implementing" ref="" type="22">Kigali Health Institute</participating-org>
<participating-org role="Implementing" ref="" type="22">Les Compagnons Fontaniers du Rwanda</participating-org>
<participating-org role="Implementing" ref="" type="22">Ministry of Health Rwanda</participating-org>
<participating-org role="Implementing" ref="" type="22">Nyamata Hospital CBEHPP</participating-org>
<participating-org role="Implementing" ref="" type="22">Water&amp;Sanitation Corporation</participating-org>
<participating-org role="Implementing" ref="" type="22">Water&amp;Sanitation Secretariat</participating-org>
<participating-org role="Implementing" ref="GB-CHC-288701" type="21">WaterAid</participating-org>
```

Something to do with:

 `version="1.04"` ?

**Comment by notshi** [comment]
Not quite.

There are measures to display the roles regardless of the standard version. Except in this case, the role reported is capitalised so it doesn't show up (only lowercase was supported).

As the [standard only lists capitalised code names](http://iatistandard.org/104/codelists/OrganisationRole/), I've added those in as well.

This addition should now be live on d-portal.

**Comment by stevieflow** [comment]
Thanks @notshi !

Just to check - would "IMPLEMENTING" be accepted, too?

**Comment by notshi** [comment]
It does - now.

However, is this ok practise against the standard? Considering, identifiers and other code elements are case sensitive and _code_, is not the same as _name_.

**Comment by stevieflow** [comment]
It might be useful - to the end user - to provide some support.  Some publishers are still providing strange interpretations of these "codes": http://dashboard.iatistandard.org/codelist/1/participating-org_@role.html

Alongside d-portal helping the user, there would need to be publisher support for getting the underlying data fixed up , by IATI Tech Team, for example
