### ISSUE TITLE
Include both name and ref for Org on screen

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#417]
Follow on from discussion on #413 via https://discuss.iatistandard.org/t/data-use-observation-a-reference-for-an-organisation-alone-is-not-enough/1091/6

> Now, I would prefer to see both Ord ID and name on the D-Portal. The ID conveys useful information, like which country the org is from.

This might present a slight UI challenge, but would be welcome

**Comment by notshi** [comment]
Thanks, @stevieflow - yes, still thinking about how best to do this as it will also be reflected in the transaction and planned-disbursement tables further down.

**Comment by notshi** [comment]
Ref attribute is now displayed on ```participating-org``` sections and in transactions (```provider-org``` and ```receiver-org```).

Example - http://d-portal.org/q.html?aid=GB-COH-04105827-AIDDIRECT
