### ISSUE TITLE
For document links, display the document category

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#418]
See: http://d-portal.org/ctrack.html?publisher=GB-CHC-1076497#view=act&aid=GB-CHC-1076497-CSCF-440

I want to look at the results documents (category A08)

It's quite a long list, and I have to decipher the titles to try and guess which one it is

In the XML:

```
<document-link url="http://www.senseinternational.org.uk/data/files/GPAF-IMP-009-logical-framework-Revised-200812.pdf" format="application/pdf">
<category code="A08"/>
<title>GPAF-IMP-009-logical-framework-Revised-200812.pdf</title>
</document-link>

```
It would be really useful if d-portal can help me, via displaying the category code

NB / UI consideration: it's perfectly possible for any document to have multiple categories !

**Comment by notshi** [comment]
Hmm, if it's just a category code - this should be feasible.

Thanks for linking that particular example! There's a few bugs to be squashed in that one in terms of displaying the title.

**Comment by stevieflow** [comment]
> Hmm, if it's just a category code - this should be feasible.

To be clear - it'd be the name rather than the code: http://iatistandard.org/202/codelists/DocumentCategory/

devtracker is a good example to check: https://devtracker.dfid.gov.uk/projects/GB-1-202493/documents

**Comment by notshi** [comment]
This is now live on d-portal.

**Comment by stevieflow** [comment]
:+1:
