### ISSUE TITLE
Display a count of the number of documents

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#419]
This example (thanks @Mattdevinit !):

http://d-portal.org/q.html?aid=SE-0-SE-6-7100174403-BIH-15150

Lots and lots of documents!  But - how many?  Would d-portal be able to display a count?

(I think it's 533 in this case)

**Comment by notshi** [comment]
Ahh, yes - I sent Matt that link to show an extreme example of document-links.

In fact, [here's a list of them](http://d-portal.org/q.json?from=element&orderby=element_volume-&limit=10&element_name0=document-link) - all in the 500++ range (yikes) and mostly from 1 publisher (SIDA).

This is on my list of things to do for SAVi but was not a priority - until now :}

**Comment by stevieflow** [comment]
Thanks!

@Mattdevinit did ask me if I could manually count the docs on pages, and submit via a form.  Just let me know :)

**Comment by notshi** [comment]
No worries - this is now enabled on d-portal, along with the other collapsible elements.

Do let me know if something doesn't seem quite right!
