### ISSUE TITLE
participating-org section links to publisher page instead of organisation page

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#420]
I guess this is a known fudge, and I guess it’s because organisation pages don’t exist?

So for example:
http://d-portal.org/q.html?aid=US-EIN-300108263-GGProj:11

The implementer here is “World Camp”, but when I click the link I go to [a weird view](http://d-portal.org/ctrack.html?publisher=US-GG-8#view=main). It took me a while to realise that’s because this is a publisher page, and World Camp isn’t a publisher (though it does exist as an `iati-organisation`, via an entry in global giving’s org file.)

That’s a weird example, though. More generally, it would be cool to have an organisation page that shows the project breakdown per org role, rather than just for the publisher role.

**Comment by andylolz** [comment]
> d-portal only has pages for country or publisher so this is out of our scope - at least for now.

Makes sense – that’s fair enough.

> What I can do is disable the link if the participating-org fails a lookup in the publisher list.

Well I doubt there are many instances of this… But still, that would be cool :) Thanks!

**Comment by notshi** [comment]
This is now live on d-portal.

I notice that this also fixed ```@ref``` that have been changed; ie. publishers with old id that previously ended up on a similar weird view :}

**Comment by notshi** [comment]
This is also updated for ```receiver-org``` and  ```provider-org```  in ```transaction``` and ```planned-disbursement```.
