### ISSUE TITLE
Progress bar doesnt work when switching currency?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#425]
This listing has the finance progress bar, but in USD as a default:

http://d-portal.org/ctrack.html?search&country=TZ&sector_group=311#view=list_activities

![list](https://user-images.githubusercontent.com/1209944/32404225-c0da266e-c143-11e7-92eb-08f654451ec4.png)

When I switch the currency on this page - these bars do not seem to populate:

http://d-portal.org/ctrack.html?country=TZ&usd=EUR#view=list_activities

![status](https://user-images.githubusercontent.com/1209944/32404248-50fd34de-c144-11e7-9d1b-a775c2d9480f.png)

**Comment by notshi** [comment]
Thanks, @stevieflow - this is now fixed and live on the main site.
