### ISSUE TITLE
Change currency setting loses sector filter

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#426]
I was on this page: 

http://d-portal.org/ctrack.html?search&country=TZ&sector_group=311#view=list_activities

![980](https://user-images.githubusercontent.com/1209944/32404259-822f286e-c144-11e7-8854-fceb0b669ac8.png)

If I change currency I am diverted to this page

http://d-portal.org/ctrack.html?country=TZ&usd=EUR#view=list_activities

![13002](https://user-images.githubusercontent.com/1209944/32404270-a2f14582-c144-11e7-9f01-cf2e6951335d.png)

**Comment by notshi** [comment]
Thanks, @stevieflow - this is now fixed and live on the main site.
