### ISSUE TITLE
Results - display units according to measureType code (esp %)

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#427]
See example: 

http://d-portal.org/q.html?aid=44000-P119308

In the standard there are two types of measures: http://iatistandard.org/202/codelists/IndicatorMeasure/ - unit or percentage

In the current SAVi the unit is not printed on screen:

This is an indicator with a Unit measure:

`<indicator measure="1" ascending="1">`

![unit](https://user-images.githubusercontent.com/1209944/32514892-3f8cd0ce-c3f6-11e7-8a6c-08aaa5a61565.png)

Whereas this is a percentage:

`<indicator measure="2" ascending="1">`
![percentage](https://user-images.githubusercontent.com/1209944/32514924-5a3c32ac-c3f6-11e7-84b4-096f2b4b667a.png)

Is it possible to indicate what the measure types are?  For % measures, perhaps we can include the % sign?

This is quite important to help users distinguish between different measure types

**Comment by stevieflow** [comment]
Suggestion: maybe the measureType code name can be printed beneath the number (as the baseline year is)?

**Comment by notshi** [comment]
Thanks, @stevieflow - the measure type is displayed at header level; ie. in your screenshots above, see 'INDICATOR UNIT' or 'INDICATOR PERCENTAGE'.

However, it looks like these headers are not obvious so I've displayed them beneath the values and added the % sign for % measures - this is now live on d-portal.

**Comment by stevieflow** [comment]
Thanks @notshi 

Yep - can see that now:

![fixed](https://user-images.githubusercontent.com/1209944/32978467-9762aa98-cc3a-11e7-982f-15c8a43f26bb.png)

**Comment by stevieflow** [comment]
FTR - I'm not sure we need to display "Indicator Percentage", as percentrage is just an attribute of the container-known-as-the-Indicator.  Does that make sense?  Now that you use the measureType in the data box, it is the intended place for this.  I'd just call the Indicator an Indicator!

**Comment by notshi** [comment]
Makes sense! Updated text is now live on the site.

**Comment by stevieflow** [comment]
Thanks
