### ISSUE TITLE
Results- baseline value not displaying correctly

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#428]
I have been contacted by DanChurchAid asking about how their baseline values are showing on d-portal.

At the moment, the IATI standard allows one [baseline value per indicator](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/result/indicator/baseline/).

You can see in the XML file that DanChurchAid have entered different values for each indicator, however, [d-portal](http://d-portal.org/ctrack.html?search&publisher=DK-CVR-36980214#view=act&aid=DK-CVR-36980214-Dutch-2016-2020-SouthSudan) is showing the same value for all indicators (see screenshots below).  Could you please check and let me know whether that is an error on how d-portal is currently set up?

![image005](https://user-images.githubusercontent.com/24607542/32737985-72f6abe6-c893-11e7-98fc-fb31572523a7.png)

![image002](https://user-images.githubusercontent.com/24607542/32737984-72d980c0-c893-11e7-8e54-456bce1976d1.jpg)

Many thanks!

**Comment by notshi** [comment]
Many thanks, @PetyaKangalova - this is definitely a bug.

This is now fixed and live on d-portal.

**Comment by PetyaKangalova** [comment]
Many thanks @notshi !
