### ISSUE TITLE
Strip whitespace before after activity ID?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#430]
This example:

http://d-portal.org/q.html?aid=NL-KVK-41198677-AFGO_PROJECTCLUSTER-1007009

The link to the parent project doesnt work:

http://d-portal.org/q.html?aid=NL-KVK-41198677-AFGO_FUND-GB-1-204343-105%20

That's because there is whitespace in the XML:

`ref="NL-KVK-41198677-AFGO_FUND-GB-1-204343-105 "`

The publisher will fix this, but I wondered if d-portal could strip whitespace regardless?

**Comment by notshi** [comment]
Could this be something for validators to check? Might be good to spot this higher up in the chain of the publishing process so it doesn't trickle down for visualising platforms to 'fix'.

The [standard](http://iatistandard.org/202/activity-standard/overview/iati-identifier/#considerations) seems to recommend the no spaces practise so might be good to get validators on the ball if they are not. 

As it stands, we're reluctant to add a fix as it might encourage publishers to leave it broken, though I do appreciate that this particular example will be fixed in the future. This issue is a non-breaking bug so I'll put this on low priority for now.

**Comment by stevieflow** [comment]
@rolfkleef mentioned something around this at the mini TAG this week

In the meantime, I do think it'd be useful if d-portal takes action, in terms of end user experience

**Comment by rolfkleef** [comment]
Thanks @stevieflow -- what I tried to refer to: many technical standards seem to have recommendations for both producers and consumers.

IATI only has producer-related rules and guidelines, but no rules for consumers.

The standard says producers **should** avoid leading and trailing whitespace. That means it's a warning or recommendation, not an error. (We warn about it in our validations.)

It would be useful to also (or instead?) specify that consumers **can** ignore leading and trailing whitespace. Until then, the whole identifier string including whitespace should be considered significant, I guess...

(There are more 'producer versus consumer' choices to be debated in the standard and the TAG.)

**Comment by stevieflow** [comment]
Thanks @rolfkleef. 

> It would be useful to also (or instead?) specify that consumers can ignore leading and trailing whitespace. Until then, the whole identifier string including whitespace should be considered significant, I guess...

I guess this isn't discussed anywhere yet?  Perhaps we could take this example, plus your work, and then post on Discuss ?

In the meantime, @notshi - do you think this is a routine d-portal **could** do?

**Comment by notshi** [comment]
Many thanks both.

Definitely agree with producer & consumer instructions.

Our standpoint is that standards should be strict to encourage clean, standardised data as a starting point. This will allow consumers to work with a good base and still be forgiving in places where the standard isn't entirely met.

However, this seems to be a work in progress with IATI but hopefully we'll get there.

Meanwhile, sure - we will do this as a routine for d-portal.

We are currently in the midst of changing servers so it might be a little while before a fix goes live.

**Comment by notshi** [comment]
This fix should now be live - please get in touch if anything seems out of place!
