### ISSUE TITLE
Lists not showing in filters when using "123" option

### ISSUE THREAD

**Issue by YohannaLoucheur** [devinit/D-Portal#431]
I tried using the D-Portal to find projects in a specific sector. I needed to see sectors by number (instead of alphabetical), but when I used the "ABC-123" toggle, all the lists disappeared from the filters. I could no longer see sector categories, sectors, countries, donors – nothing.  

They didn’t come back when I moved back to ABC option. I had to close the D-Portal and open it again to get the lists back (simply refreshing didn’t work). Tried it a few times, same result every time.

**Comment by YohannaLoucheur** [comment]
Tks @stevieflow 

Confirm that it works on Chrome here as well. 
But does not work on Internet Explorer 11.

**Comment by stevieflow** [comment]
> But does not work on Internet Explorer 11.

Ah ha ! Thanks for checking

**Comment by Mattdevinit** [comment]
thanks @YohannaLoucheur and @stevieflow - it seems like Internet Explorer is increasingly less supported (in favour of Edge)!  but we'll need to sort this still, so thanks for flagging it

**Comment by notshi** [comment]
Closing this for reasons explained here.
#554 (comment)
