### ISSUE TITLE
Handling whitespace in text box search

### ISSUE THREAD

**Issue by YohannaLoucheur** [devinit/D-Portal#432]
So, issue #431 happened because I could not find a specific CA-3 project on the D-Portal via the free text box. The Activity ID number did not yield any result. 

Turns out I accidentally brought a whitespace at the end of the number when I copied it from our website. Once I removed it, the search did yield the project I wanted. 

Could we make the text box search less sensitive to whitespace? 

This is not the same issue as #430, since the whitespace comes from the user typing (or pasting), not the xml data.

**Comment by Mattdevinit** [comment]
thanks @YohannaLoucheur that's really helpful - will be fixing this in the next few days to handle whitespace better

**Comment by notshi** [comment]
The search box has been updated to ignore whitespace before and after an activity id - this change is now live on the website.

**Comment by YohannaLoucheur** [comment]
Yeah, thanks!
