### ISSUE TITLE
Improvement - "Refine search" function

### ISSUE THREAD

**Issue by YohannaLoucheur** [devinit/D-Portal#433]
When using D-Portal to search for projects/activities, it's easy to get a long list of projects. It would be really nice to be able to refine the search, either by going back to the main page without loosing the filters already set, or by seeing relevant filters at the top of the results page. 

For instance, let's say I selected a given publisher and recipient country, and got a list of 144 activities; I could want to refine the search by activity status or by sector, and this would most naturally be done on the results page by selecting additional filters. Right now I have to go back to the home page and reselect the publisher and country, plus set the additional filters. If one's system is a bit slow, or some filters had more than one option, this is quite tedious.

**Comment by Mattdevinit** [comment]
thanks @YohannaLoucheur - useful to get this feedback.  we'll definitely add this to do but will take a bit of time, I think the first step in this is to do #401 which we'll address this month

**Comment by Mattdevinit** [comment]
@YohannaLoucheur #401 is done, so you should retain selected search options now when using back - this works ok for us, be useful to know if it works ok for you/helps in refining searches more quickly

**Comment by YohannaLoucheur** [comment]
Hi there
It seems to be working quite well on both (antiquated IE) and Chrome.  Thanks all for this!

However I found a couple other (unrelated, I think) issues as I tested it, which I will report separately.
