### ISSUE TITLE
Show progress bars with no Commitments (but with D or E) as 100%

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#434]
For progress bars on lists of projects, where there are no Commitments in the data, but there exist relevant Disbursements and/or Expenditure, instead of showing the bar as empty/0% as it is currently, show as a full bar/100% (eg equating to the total of D+E spent so far)

**Comment by notshi** [comment]
This is now live - please add this to the footer as well @Mattdevinit, thanks!
