### ISSUE TITLE
Sector not showing (or searchable)

### ISSUE THREAD

**Issue by bill-anderson** [devinit/D-Portal#435]
This [activity](http://d-portal.org/ctrack.html?search&country=MW&publisher=XI-IATI-EC_DEVCO#view=act&aid=XI-IATI-EC_DEVCO-2016%2F380-805) shows no sector (and is not searchable by sector)

xml contains

`<sector code="15110" vocabulary="1">`

**Comment by notshi** [comment]
Hi @bill-anderson, could you send a screenshot of what you see?

You should be able to see the sector as a graph below -

![sector](https://user-images.githubusercontent.com/1515961/33724042-33f3e982-db66-11e7-8739-c3e29e7c02e6.png)

This activity is also searchable via sector ```15110``` (I've included the other search terms you used).

http://d-portal.org/ctrack.html?search&country=MW&sector_code=15110&publisher=XI-IATI-EC_DEVCO#view=act&aid=XI-IATI-EC_DEVCO-2016%2F380-805

**Comment by bill-anderson** [comment]
Well, I see it exactly like you do now.
I'm not crazy. Really.
(I think?)

**Comment by notshi** [comment]
To be fair, this used to be a list but was recently converted into a graph so that could be it :}
