### ISSUE TITLE
IATI IDs with ampersands?

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#438]
This is probably the wrong place for what is essentially a support question. Sorry…!

I’m wondering whether it’s possible to view on d-portal the activity with the following IATI identifier:
`US-18-GTM-2750BXTHRD-MON & EVAL-16`

It’s from the following dataset:
https://iatiregistry.org/dataset/unitedstates-gt2

I wasn’t able to find it, and wondered if it was due to the ampersand in the identifier?

Thanks!

**Comment by xriss** [comment]
Might just need to wait for an update? or maybe we missed some escaping?

These are all the IDs that contain US-18-GTM-2750BX that we have

http://d-portal.org/q.json?select=aid&aid_like=%25US-18-GTM-2750BX%25

Is it possible that they have recently added some spaces as we have an US-18-GTM-2750BXTHRD-MON&EVAL-16 available and we might not have picked up a recent change yet?

**Comment by andylolz** [comment]
> Is it possible that they have recently added some spaces as we have an US-18-GTM-2750BXTHRD-MON&EVAL-16 available and we might not have picked up a recent change yet?

^^ YES! That looks like the right activity! Thanks!
