### ISSUE TITLE
Printing all related activity type names

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#439]
On 

http://d-portal.org/q.html?aid=NL-KVK-34106722-BEN

This activity has two related-activity types:

```
<related-activity ref="NL-KVK-34106722-STP" type="1"/>
<related-activity ref="NL-KVK-27189542-BEN16" type="5"/>
```

However, in d-portal, whilst the type 5 (Third Party) is displayed, the label is not.  

NB: I dont think "Third Party of [activity ID]" would work, though

**Comment by notshi** [comment]
Thanks, @stevieflow - have updated accordingly. This fix is now live on d-portal.

Looks like we were still picking up 1.04.

We're adding this manually as IATI does not have a standard 'latest' embedded codelist url to use which means we will have to keep looking to update this when there are new versions in the standard.

**Comment by stevieflow** [comment]
Excellent. thanks @notshi
