### ISSUE TITLE
Sector aggregations use three-digit codes - even when five-digit codes are published

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#441]
I noticed that aggregations on sectors use the three-digit code:

![d-portal 10](https://user-images.githubusercontent.com/1209944/35450812-0c81deca-02b9-11e8-8ea3-f6bff6ad34e0.png)

However, activities within this, will use the five-digit code - eg:

![d-portal 11](https://user-images.githubusercontent.com/1209944/35450954-8bc93890-02b9-11e8-95d8-0da84e7da04e.png)

I just wanted to double check this is the intended behaviour?

**Comment by notshi** [comment]
Yes, we convert 5 digit codes to 3 digit codes so we can give a simpler overview.

We do this as some publishers only produce data with 3 digit codes. Hence, by converting the 5 digit codes to 3 digit, we can unify the data to be visualised simply on d-portal.

**Comment by stevieflow** [comment]
Thanks for the clarification @notshi .  Is / should this be in the FAQs?

**Comment by notshi** [comment]
This is briefly brought up in the 'How is the data calculated?' section below (you could click on 'About this data' link top left to be directed there instead of scrolling down).

It's also in the same section when you click through to the Sector page.

But yes, we should put it in the FAQ as well.

**Comment by notshi** [comment]
Many thanks for waiting - this is now in the FAQ under 'Technical'.
