### ISSUE TITLE
Multiple results & indicators - numbering/ordering process

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#442]
This is in an interesting activity, from a results perspective:

http://d-portal.org/q.html?aid=NL-KVK-41198677-AFGO_PROJECTCLUSTER-1006719

In presenting this, d-portal has "decided" on the order, and applied numbering accordingly (1, 1.1, 1.2, etc)

Would it be possible to explain what process you undertake to apply this?

[ It so happens that this particular activity has a form of ID for the results and indicators, but in the narrative.  There's **_no_** expectation that d-portal should have recognised these btw!  Underneath all this issue is the lack of UID in results, indicators and periods: https://discuss.iatistandard.org/t/challenge-results-with-multiple-indicators-and-multiple-measures/1108 ]

**Comment by notshi** [comment]
Hi @stevieflow - the numbering process is the same done for all aspects of SAVi.

It's mostly just a convenience for users to see how many elements are listed on the page; eg. the numbers for 'Who's Involved'.

In this case, the number of indicators listed per results displayed; ie. 3.5 means there are 5 indicators for the 3rd result data.

Looking at the example you've provided - the added numbering system is only making it more confusing which was not the intended effect! Should we remove the indicator numbers (but leave the results) for now?

**Comment by stevieflow** [comment]
> Looking at the example you've provided - the added numbering system is only making it more confusing which was not the intended effect! Should we remove the indicator numbers (but leave the results) for no

I think so, yes

**Comment by notshi** [comment]
Fix is now live.
