### ISSUE TITLE
multiple references are not displayed out

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#444]
The example in #443 included:

```
     <reference vocabulary="1" code="3429" />
     <reference vocabulary="7" code="861" />
     <reference vocabulary="99" code="B1" indicator-uri="http://example.com/indicators.html" /> 
```  

When looking at this in d-portal, it looks strange!

![202](https://user-images.githubusercontent.com/1209944/36804924-e8511cb8-1cb3-11e8-9af5-941ce4b32fbe.png)

I removed the vocab-uri reference:

```
     <reference vocabulary="1" code="3429" />
     <reference vocabulary="7" code="861" />
     <reference vocabulary="99" code="B1" /> 
```

But - the multiple reference still seem to be laid out on top of each other:

![multi-reference - no uri](https://user-images.githubusercontent.com/1209944/36804958-087c250a-1cb4-11e8-8905-7295f661a2fa.png)

I *think* this might be two issues:

1 - layout when there are instances of multiple references per indicator
2 - how the vocab URI is used, when included: #445

**Comment by notshi** [comment]
Should be fixed with https://github.com/devinit/D-Portal/issues/443#issuecomment-370858171

**Comment by stevieflow** [comment]
Great, thanks @notshi
