### ISSUE TITLE
When a vocab URI is included for a result/indicator/reference, it overrides other values in the display

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#445]
Building on #443 & #444 

This example:

![singlevocab](https://user-images.githubusercontent.com/1209944/36805187-a23d9278-1cb4-11e8-9ace-2d673c62cf88.png)

Includes just one reference element in the indicator:

`     <reference vocabulary="99" code="B1" indicator-uri="http://example.com/indicators.html" />     `

It seems when this is the case, the vocab URL is displayed, but other data is lost to the viewer

**Comment by notshi** [comment]
https://github.com/devinit/D-Portal/issues/443#issuecomment-370858171

**Comment by notshi** [comment]
Should be fixed with https://github.com/devinit/D-Portal/issues/443#issuecomment-370858171

**Comment by stevieflow** [comment]
Great, thanks @notshi
