### ISSUE TITLE
Lots of activities are out of date

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#448]
* [this EC ECHO activity](https://d-portal.org/q.html?aid=XI-IATI-EC_ECHO-ECHO/-AF/BUD/2016/92038) has a `last-updated-datetime` of 2018-01-22. However, the relevant activity has a `last-updated-datetime` of 2018-02-26, and includes lots of `document-link`s that are missing from the d-portal activity
 * [this US activity](https://d-portal.org/q.html?aid=US-GOV-7-CO-CA87EFF2) doesn’t exist on d-portal, but it [does on the registry](http://preview.iatistandard.org/index.php?url=https%3A//www.foreignassistance.gov/assets/IATI/Developing_countries_unspecified_Department_of_Defense.xml) (`US-GOV-7-998-85CA8705`)

**Comment by xriss** [comment]
I think this is all the same bug ( https://github.com/devinit/D-Portal/issues/447 ) seeing a bump in number of activities and I'm guessing it will all be better in the next hour.

**Comment by notshi** [comment]
Many thanks, @andylolz for spotting this.

The missing activities should now be in d-portal. Do get in touch if you spot anything out of place.

**Comment by andylolz** [comment]
AMAZING! Thanks both!

We’re looking closely at donor data this week & next, so I’ll let you know if we spot anything untoward.
