### ISSUE TITLE
Layout is broken if there’s no result indicator period-start

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#450]
E.g.:
![screen shot 2018-03-14 at 12 39 41](https://user-images.githubusercontent.com/464193/37402841-ddf58ac0-2784-11e8-91f7-c0516bc9ea22.png)

**Comment by notshi** [comment]
Thanks for spotting! Could you give an example link? That would help tremendously, thanks.

**Comment by andylolz** [comment]
Of course, sorry! The example above is here:
http://d-portal.org/q.html?aid=46004-48078-003-LN3419

**Comment by notshi** [comment]
Thanks, @andylolz - this is now fixed and live on d-portal.

**Comment by andylolz** [comment]
Looks good! Thanks @notshi!
