### ISSUE TITLE
Heat maps not displaying

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#451]
Hi guys,

We've had a message in from USAID about heat maps not displaying when looking at their data for a specific recipient country.

However, when you click on the alert button the heat map then shows correctly - e.g, USAID activities happening in Colombia.

Do we know why this is the case and if it can be fixed?

(@dalepotter have we already discussed this....?)

**Comment by Mattdevinit** [comment]
thanks @amy-silcock could you provide any links and screenshots to the issue pls?

**Comment by amy-silcock** [comment]
Searching by USAID and Colombia (http://www.d-portal.org/ctrack.html?search&country=CO&publisher=US-GOV-1#view=main) you get:
![image](https://user-images.githubusercontent.com/27764077/37591294-f6d2d2d2-2b62-11e8-8c70-ad9d235a5560.png)

Then if you, click on the alert that says only 14% of activities have location data you get taken to a page with a working heat map (http://www.d-portal.org/ctrack.html?search&country=CO&publisher=US-GOV-1#view=map&lat=5.5921658056504135&lng=-75.2188680223532&zoom=6): 
![image](https://user-images.githubusercontent.com/27764077/37591340-233528fc-2b63-11e8-9c45-1e719d0cd653.png)

**Comment by amy-silcock** [comment]
Their data should now be fixed. So it should be fine to remove the hack.

Thanks @xriss!

**Comment by notshi** [comment]
Hi @amy-silcock, this is now fixed and live on d-portal.
