### ISSUE TITLE
Search behaving strange with non-ascii characters

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#454]
Searching for 'réfugiés' converts the search text.

Currently, we do this to keep the URL clean.

**Comment by k8hughes** [comment]
How long would it take to fix this?  If the fix is less than a day we should prioritise.

**Comment by andylolz** [comment]
Seems to work with a percent-encoded URL:
http://d-portal.org/ctrack.html?search=r%C3%A9fugi%C3%A9s#view=main

Chrome and firefox even convert these to display the URLs nicely.

**Comment by xriss** [comment]
I've taken out the code that strips non alpha-numerics from the search string. This fixes this issue but may cause other ones...
