### ISSUE TITLE
Show withdrawn DAC sector codes as such

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#455]
My colleague was looking into energy policy on d-portal, and was thrown by this:

![screen shot 2018-04-17 at 11 12 47](https://user-images.githubusercontent.com/464193/38863686-50afa224-4230-11e8-8c68-eecb0242bbf1.png)

What’s the difference between these?! It turns out the `230` codes are all withdrawn, so the usage of these codes is restricted to historical data.

[The IATI Sector codelist XML](http://iatistandard.org/203/codelists/downloads/clv2/xml/Sector.xml) shows that these codes are withdrawn, although the IATI website doesn’t (issue for that here: IATI/IATI-Standard-SSOT#142).

It might be useful to show these sector codes as withdrawn in this dropdown, and possibly elsewhere.

**Comment by notshi** [comment]
We pick the code list direct from the source - http://iatistandard.org/203/codelists/downloads/clv3/json/en/Sector.json

So once that issue you raised is sorted, it will be reflected on d-portal. Assuming the withdrawn codes are updated to reflect this; ie. (withdrawn) text after the sector name.

Question:  
Is the XML source prioritised and kept up to date above other formats?

If this is the case, we might have to switch to XML only codelists - we're currently using the JSON codelist and this seems inconsistent.

**Comment by andylolz** [comment]
> We pick the code list direct from the source - http://iatistandard.org/203/codelists/downloads/clv3/json/en/Sector.json

Great – I sent pull request(s) to fix the JSON: https://github.com/IATI/IATI-Codelists/pull/155

> Is the XML source prioritised and kept up to date above other formats?

They’re all updated at the same time, but the XML is more complete in the sense that it includes attributes that simply aren’t present in the CSV / JSON. I think it makes sense for IATI to fix the CSV / JSON to include status (unless they feel strongly otherwise) so I’d suggest holding off on switching to the XML.

**Comment by k8hughes** [comment]
Marking as block as we need to look at the linked github PR that is on our repo.  I will post an update here once that has been addressed.

**Comment by andylolz** [comment]
> Maybe we can revisit this in a month, if that hasn’t been done.

Good news – [the related pull request](https://github.com/IATI/IATI-Codelists/pull/155) has been merged! It hasn’t been deployed yet… But that’ll happen sooner or later 🌟

**Comment by andylolz** [comment]
This is now live on production! See for example: http://reference.iatistandard.org/203/codelists/Sector/

It’s present in the CSV ([e.g.](http://reference.iatistandard.org/203/codelists/downloads/clv2/csv/en/Sector.csv)) and JSON ([e.g.](http://reference.iatistandard.org/203/codelists/downloads/clv2/json/en/Sector.json)), too.

**Comment by andylolz** [comment]
This is now live on production! See for example: http://reference.iatistandard.org/203/codelists/Sector/

It’s present in the CSV ([e.g.](http://reference.iatistandard.org/203/codelists/downloads/clv2/csv/en/Sector.csv)) and JSON ([e.g.](http://reference.iatistandard.org/203/codelists/downloads/clv2/json/en/Sector.json)), too. So I think that means this ticket is no longer blocked 🙌 

> So once that issue you raised is sorted, it will be reflected on d-portal. Assuming the withdrawn codes are updated to reflect this; ie. (withdrawn) text after the sector name.

Ah, I didn’t do it in this way. Withdrawn status isn’t reflected in the code name in the JSON – codes are flagged as withdrawn via a `status` attribute. I’ve attempted a pull request (#502) to parse and reflect this.

**Comment by notshi** [comment]
Thanks, @andylolz - yes, I did get a chance. Not too happy with the way this looks - cluttered.

![withdrawn](https://user-images.githubusercontent.com/1515961/50601489-3356c880-0eac-11e9-8795-66bdb17716be.png)

I think we might put a tick box to show/hide withdrawn codes instead and hide withdrawn codes by default; the withdrawn codes will be greyed out, for example.

**Comment by andylolz** [comment]
Agree it looks cluttered! Was just an MVP, really.

Whatever you think! Would just be great to show this information somehow.

**Comment by notshi** [comment]
Currently looking at doing this for now. Not displaying the 'withdrawn' text made it unclear why it was greyed out. @k8hughes if this is ok, could we unblock this? Many thanks!

![withdrawn_updated](https://user-images.githubusercontent.com/1515961/50638040-30171780-0f54-11e9-8c97-afbea9c4e3b8.png)

**Comment by k8hughes** [comment]
Nice solution, I've removed the blocked lable.

**Comment by andylolz** [comment]
Original example:
![screenshot 2019-01-07 at 11 54 56](https://user-images.githubusercontent.com/464193/50772405-9322ea00-1285-11e9-8a12-de217b240ebb.png)

Looks good to me!

**Comment by notshi** [comment]
Withdrawn codes are now also displayed in SAVi.

![withdrawn01](https://user-images.githubusercontent.com/1515961/51160317-565a8280-1885-11e9-95f7-0f3f95685ff3.png)

**Comment by andylolz** [comment]
Ace! I’m happy for this one to be closed.

Loving the new graphical presentations on d-portal! Looks fantastic!
