### ISSUE TITLE
Sum of Country and sum of sectors don't en up to the same sum

### ISSUE THREAD

**Issue by svnor** [devinit/D-Portal#456]
Hi
Is it possible to add logic to sum up countries with regions so that the sum of countries in country - diagram will equal to the sum of sectors in sector - diagram
![countrires](https://user-images.githubusercontent.com/38461263/38866309-0767803c-4230-11e8-8050-b8c87c564a0b.png)

![sectors](https://user-images.githubusercontent.com/38461263/38866424-5af80442-4230-11e8-9ea4-5734c4d97eb1.png)

I seems to be logically that the sum should be the same disreagard of you are grouping by country/region or by sectors.

Best Regards
Sven Norlin
for Sida FWO Sweden

**Comment by k8hughes** [comment]
There is no direct mapping between countries and regions in IATI, so unfortunately at this time the standard doesn't allow us to do this.
