### ISSUE TITLE
Searching in D-Portal by policy markers

### ISSUE THREAD

**Issue by AriaGrab** [devinit/D-Portal#457]
Currently it is not possible to search for policy markers in D-portal.  It would be nice to be able to search for projects/activities by a specific OECD policy markers (ie Gender) as are in the IATI standard.  Ideally there would be a secondary search function or the ability to specify the significance of the specific policy marker  so that it is possible to search the policy marker to determine if it is marked as principal or significant or screened not targeted or a 2, 1, or 0.  This should be in addition to other filters if possible.  For example it would be ideal to search in a specific country for activities that are marked with the principal gender policy marker, or search for projects in a specific country and sector that are also labeled as a significant gender project.  While I am using the gender policy marker as the example, it would great to have it for all the policy markers in the standard (http://iatistandard.org/203/codelists/PolicyMarker/).

**Comment by notshi** [comment]
Thank you for raising this @AriaGrab, we are currently looking at implementing [policy-marker](http://iatistandard.org/203/activity-standard/iati-activities/iati-activity/policy-marker/) into d-portal.

These are the parts to enable this:

1. Display policy markers in SAVi
2. Add the data to the database
3. Connect the new data as parameters in d-portal URLs
4. Add these parameters to the search interface as filters
5. Testing and debugging

[This is the SAVi page](http://d-portal.org/ctrack.html#view=act&aid=CA-3-A033419001) of the example we will be using to display the ```policy-marker``` element.

![policy](https://user-images.githubusercontent.com/1515961/39318610-784db2d8-4976-11e8-8711-1af48faecf99.png)
*This will be the same SAVi page with ```policy-marker``` displayed*

I've worked through various layouts of how best to display the section and have decided on the above design. There will be edge cases that may break this layout, eg. activities with ```vocab``` 99 that are published without ```vocabulary-uri``` or ```narrative``` so we will need to look out for those and adjust the code accordingly.

The secondary search function to specify significance adds a layer of complexity to the process.

Consider these two examples you mention:
1. > For example it would be ideal to search in a specific country for activities that are marked with the principal gender policy marker,

2. > or search for projects in a specific country and sector that are also labeled as a significant gender project.

To make this work, we will need to tightly couple the attributes, ```policy-marker code``` and ```policy-marker significance``` so the results of the search will make sense.

**Comment by notshi** [comment]
Hi @AriaGrab - just letting you know that we are now working on steps 4 & 5.

The policy-markers are already being displayed in SAVi but it's going to take some time before they show up on the front page as filters.

Example page - http://d-portal.org/ctrack.html#view=act&aid=CA-3-A033419001

**Comment by stevieflow** [comment]
It's great to see this.  I had similar feedback from participants in a workshop.  Thanks to @AriaGrab for raising, and for @notshi for implementing !

In terms of the filters, then one suggestion might be to just start with a filter of the Policy Markers, regardless of significance, for now.  That might just help people filter, which I think is an important use case.

**Comment by AriaGrab** [comment]
Hi @notshi I am curious if there is any update on including this search filter on d-portal?  I am hoping to get someone to do work that needs this search feature first, and I understand its a bit more complicated and you have a lot of others things on your plate, but any kind of estimate would be helpful.  I really appreciate it!

**Comment by notshi** [comment]
Hi @AriaGrab, many thanks for your patience.

Policy marker search filter is now live on d-portal. There may be teething issues and bugs - if you or your colleague finds them, do let us know so we can make it better.

**Comment by notshi** [comment]
Hi @AriaGrab - this bug is now fixed on the site. Many thanks for sending that in.

**Comment by stevieflow** [comment]
This looks interesting, thanks @notshi 

@AriaGrab in turn, this might create a number of "results issues" - maybe wrapped up in the specifics Policy Markers/Significance, and how they are used/defined.

For example - of the [MILLIONS](https://www.aidtransparency.net/news/explore-one-million-activities-published-to-iati) of IATI activities, only 57 have gender equality as the explicit objective.  

![gender](https://user-images.githubusercontent.com/1209944/42260445-5ddca758-7f5c-11e8-96f8-09c55251f67e.png)

There are, however, 28,960 that have Gender equality as a principle objective

![gender2](https://user-images.githubusercontent.com/1209944/42260473-75ce8f84-7f5c-11e8-83a1-fd9fdb9c71bf.png)

What's the difference between explicit and principle objectives?  I'd have to know about the IATI codelist on [PolicySignificance](http://iatistandard.org/203/codelists/PolicySignificance/) (which lacks a description for Explicit objective) and then maybe hunt around [OECD DAC documentation](http://www.oecd.org/dac/gender-development/dac-gender-equality-marker.htm) (there's no reference to Explicit here?).  What would we expect someone less forgiving to do?

Whilst we should not shy away from this, I think there some thought needed about the impact this can have on data users (or casual browsers).  Shall we start a thread on IATI Discuss?

**Comment by k8hughes** [comment]
As there have been no further comments I am closing this issue.
