### ISSUE TITLE
XDR conversion doesn't work?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#459]
When I convert the list of projects from USD (the default) to XDR, the values remain the same

I've tried this for a few publishers (a couple of whom publish in XDR) and this seems to be consistent - in the active view, at least

IFAD:
http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=active (USD)
http://www.d-portal.org/ctrack.html?search=&publisher=XM-DAC-41108&usd=XDR#view=active (XDR)

AfDB
http://www.d-portal.org/ctrack.html?search&publisher=46002#view=active (USD)
http://www.d-portal.org/ctrack.html?search=&publisher=46002&usd=XDR#view=active (XDR) 

DFID
http://www.d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=active (USD)
http://www.d-portal.org/ctrack.html?search=&publisher=GB-GOV-1&usd=XDR#view=active (XDR)

**Comment by andylolz** [comment]
The USD values look accurate. It’s the XDR values that are wrong.

Looks to be true for lots of other currencies, too. Possibly all except USD, GBP and EUR.

**Comment by notshi** [comment]
Thanks, both - sounds like client-side is borked. Will take a look.

**Comment by andylolz** [comment]
Maybe it hasn’t been redeployed yet… But it’s still not looking quite right in production. Values in the following screenshots are the same, but currencies are different:

![screen shot 2018-05-11 at 10 48 36](https://user-images.githubusercontent.com/464193/39918641-0278db84-5509-11e8-9437-0f0f3e975666.png)
![screen shot 2018-05-11 at 10 49 01](https://user-images.githubusercontent.com/464193/39918642-0293e366-5509-11e8-8ebb-4dda9ae2bdda.png)

For reference, 1 USD = 0.700 XDR at today’s exchange rate ([source](https://xe.com/currencyconverter/convert/?Amount=1&From=USD&To=XDR)).

**Comment by notshi** [comment]
Thanks @andylolz - must have forgotten to redeploy at 2am last night!

Do the numbers look as expected now?

**Comment by andylolz** [comment]
> must have forgotten to redeploy

Aha!

> when we checked the code in at 2am last night!

Lolzomg. I hadn’t spotted the timestamp!

> Do the numbers look as expected now?

Looks good to me!

As always, I’d rate this as a :star::star::star::star::star: high quality d-portal customer service experience! I’d guess @stevieflow agrees!

**Comment by stevieflow** [comment]
Adding the twitter thread for posterity: https://twitter.com/stevieflow/status/994464809621090304

Great stuff - I can different numbers on the original links posted.  Thanks!
