### ISSUE TITLE
IUCN Nederlands Comité - data not showing in d-portal

### ISSUE THREAD

**Issue by jahnvidave** [devinit/D-Portal#460]
Hello,

IUCN Nederlands Comité have been in contact because their IATI data is not showing in d-portal. http://www.d-portal.org/ctrack.html?search&publisher=NL-KVK-41180885#view=main

They have published files to IATI (with 33 activities) and I have checked that their reporting identifier matches their IATI organisation identifier (NL-KVK-41180885). 

But d-portal is showing:
![image](https://user-images.githubusercontent.com/38503709/39987496-e2193266-575c-11e8-80a5-a66ff47845d4.png)

Please can someone look into this?

Thank you,
Jahnvi

**Comment by notshi** [comment]
Hi @jahnvidave - many thanks for reporting this.

We are looking into this right now.

**Comment by notshi** [comment]
Hi @jahnvidave - the fix has been added to the code so we will have to wait till tomorrow to check if the full import (at GMT +0 midnight) has been successful.

Many thanks for your patience.

**Comment by notshi** [comment]
Hi @jahnvidave - data is now showing in d-portal for IUCN Nederlands Comité.

http://www.d-portal.org/ctrack.html?search&publisher=NL-KVK-41180885#view=main

Do get in touch if the numbers are not what you expect, many thanks!
