### ISSUE TITLE
French data blank in donor view

### ISSUE THREAD

**Issue by markbrough** [devinit/D-Portal#461]
In the "Where does the money come from?" view, [e.g. for Madagascar](http://www.d-portal.org/ctrack.html?country=MG&tongue=eng#view=donors), no disbursements are appearing for French data in the "IATI Spend (USD)" column. 

However, the [AFD IATI data for Madagascar](https://www.data.gouv.fr/s/resources/donnees-de-laide-au-developpement-de-lafd-1/20180504-143801/fr-AFD-MG.xml) appears to be correctly structured and there are activities and transactions being imported, including disbursements. 

See the [list of activities for France in Madagascar](http://www.d-portal.org/ctrack.html?country=MG&tongue=eng#view=donor_activities&funder=FR)

I tlooks like there is something weird going on with the way that disbursements are being imported (though commitments are possibly fine). See for example the third activity, "Projet d'amélioration de la qualité de l'éducation", from the link above, and compare with the source IATI data. The bar chart is recognising the USD 81mn (EUR 60mn) committed but none of the disbursements (around EUR 4mn). The previous activity does have some disbursements shown against it, however.

The [data from MAEDI / Ministry for Europe and Foreign Affairs](https://baseprojets.transparence-aide.gouv.fr/api/iati/2.01/MG.xml) also looks ok, but still there is a blank showing for French disbursements.

**Comment by andylolz** [comment]
> is currently downloading as XLS

^^ It’s still TSV, it just has the wrong file extension. If you open it in a text editor, it’s definitely TSV.

**Comment by notshi** [comment]
OK - took an even closer look - if you blink, you'll miss it.

Turns out it wasn't the case of wrong file format - they had subtly changed the URL.

https://github.com/devinit/D-Portal/blob/master/dstore/js/exs.js#L240

**Previously**
`reportType=SDRCV`

**Now**
`reportType=CVSDR`

**Comment by notshi** [comment]
Thanks for the links, @markbrough! We will take a look about changing where we get exchange rates from.

It seems IMF not only changed the url, they also renamed the currency names; eg. `G.B. pound sterling` became `G.B. pound`

This meant our internal mapping to ISO currencies was affected and thus everything broke.

Till then, this bug has been fixed and data on d-portal should, hopefully, be the numbers you expect.
