### ISSUE TITLE
Participating Organization Filter - suggested enhancement

### ISSUE THREAD

**Issue by Michelle-IOM** [devinit/D-Portal#463]
I’d like to suggest that the d-portal include a filter which allows users to filter on the participating organization by both name and IATI reference number since not all have both and exact match on spelling may be problematic.  My logic is this.
 
1.	It would be nice to be able to see where we as an organization have been referenced in other publisher’s file.  We could check that they’ve used the right reference and name.  It could also help us find that publisher’s reference to same project which is something we are grappling with as we get money from countries from other UN agencies.  Being able to trace from donor country to OCHA or CERF through to us has become a requirement for us which we are challenged to pull off as it is challenging to know if and where the other organizations report their part of the chain. 
2.	It could help find IATI reference numbers for other organizations already included in another publisher’s file.  With no centralized repository of reference numbers, it takes a lot of effort to find these.  Being able to see what may already be out there could help speed the process for those coming behind.
3.	It would help to see how much goes to an individual participating org across publishers as opposed to simply where it comes from.
 
These are just my thoughts I thought might be worth considering when you look at future enhancements.

**Comment by k8hughes** [comment]
@xriss @notshi we can see the use case for this but worry about too many filters becoming overwhelming for users.  It would be good to know your thoughts.

**Comment by notshi** [comment]
Many thanks @Michelle-IOM for this request. We are definitely looking to improve the search function by allowing more filters but at the same time, as @k8hughes has mentioned, we will need to look at how to make this feasible and kept simple.

It could be that we have an 'advanced' button to reveal more filters for the seasoned IATI community so the basic search is still kept at its minimum without being overwhelming for a newcomer.

**Comment by k8hughes** [comment]
Yes, having an advanced searh option sounds like a good solution.  how much work would it be to implement?

**Comment by k8hughes** [comment]
We still think this would be a great thing to investigate, could you look into it in the next round of quarterly updates?  :)

**Comment by notshi** [comment]
Hi @Michelle-IOM we're currently testing new search filters for d-portal and have included participating-org as one of them. If you would like to have a look and tell me what you think, you can find the testing page here:

http://www.d-portal.org/ctrack.html#view=search2

You'll need to click on 'Advanced filters' to reveal the new filters.

**Comment by Michelle-IOM** [comment]
Dear D-Portal Dev Team,

I ran a search on where IOM is listed as a participating organization.  Here are a few of my observations.


  *   I extracted a CSV of each option where that was possible (active projects, ended projects, total projects, other project, planned projects, IATI publishers). I notice that in none of the CSV extracts does I explain the participating org role IOM has been listed as which I think would be helpful.
  *   I like the fact that a link to the project is included in the CSV extract so you can get straight to the project.
  *   Given that D-portal is generally used by non-technical people I wonder if it is possible to include the names to the codes and not just the codes in the CSV extracts.  I don’t mean the header row codes, although that would be nice, but where the CSV outputs code list references (see sample below) it would be helpful to use words next to the 1, 2, 3 and 4 or the 2, 1 and zero etc.
/activity-date@type

/activity-status@code

/collaboration-type@code

/conditions@attached



2

1

0


1


2


3


4


/default-aid-type@vocabulary

/default-finance-type@code

/default-flow-type@code

/default-tied-status@code

1

110

10

5



  *   Is it possible to have a way to extract full project details but rather than doing it project-by-project but rather for all projects in a given filter?  I know it would get messy looking at it in a CSV since there are multiple rows for a single project but for one to have to extract project-by-project is very time consuming.  This has been a frustration of mine with d-portal from the beginning.  Like many users of d-portal, I don’t have technical support to build APIs which can extract what I need so being able to get to full project details based on the filtered selections would be helpful.  I know I can see it in the data store now (what I want to filter on and what I want to see in the output) and while I don’t expect d-portal to have that same sophisticated selection capabilities, something a tad more robust would be helpful to us non-tech-y users.

I looked at a few of the other filters and tried using multiple filters.  Here are my observations:

  *   IOM as participating Org with max commitment of 10,000.  While it shows what appears to be a refined list of projects, it isn’t clear that the results match my filter again because when I click to the screens shown there are figures much higher than the 10K I listed as a filter.  And assuming they are the total and perhaps IOM is a subset there is no way to see what the IOM portion is.  Even clicking down on a project-by-project basis.  This may be because of bad published data but it does make it hard to know if the results are what I was looking for.
  *   The drop down for the commitment filters are not logical.  They jump from 1 billion, 1 million, 1 thousand, 1 dollar to 10 billion, 10 million.  They should be in value order not alphabetical order.
  *   The Humanitarian Activity filter show !1 and 1.  I believe development is 0 not !1.
  *   Most of the filters are looking for the default types (aid, tied status, finance) but I’m guessing that many publishers will use the types at the transaction level not necessarily just at the default level where they are talking about commitments and revenue and not the project as a whole.  Is there no way to pull in these types regardless of if they are listed as default or at the transactional level?
  *   The pre-existing sector filter only accommodates the DAC codes but there are a lot of other sector options so I wonder if an advanced filter can accommodate those as well.
  *   Given that the standard doesn’t allow us to list both a recipient country and a recipient region (it has to be one or the other) I strongly encourage that the filters include an option to pick by region too.

That is all that popped out at me in this review.  Please let me know if any of this doesn’t make sense or if you’d like me to look at something again.

Kind Regards,
Michelle




That was all I tested at this point.  If there are other things you’d like me to review please


Michelle Y. Levesque
Senior Project Manager
Department of Resources Management (DRM)
International Organization for Migration (IOM)<http://www.iom.int/>
Geneva – Switzerland (GMT +1)
Office: +41-(0)22 717 94 83
Mobile: +41 (0)78 647 31 86
Email/Skype: mylevesque@iom.int<mailto:mylevesque@iom.int>

www.iom.int<http://www.iom.int/>  I  Facebook<https://www.facebook.com/pg/IOM/posts/?ref=page_internal>   I  Twitter<https://twitter.com/unmigration>

[cid:image001.jpg@01D5B3FB.8A2D5E90]

**Comment by notshi** [comment]
Hi @Michelle-IOM , many thanks for this - we really appreciate the time it took! We will look further into your observations and suggestions - some of them are already listed as things to do and there is one possible bug raised (with the commitment threshold).
