### ISSUE TITLE
Label "Outgoing Commitments" is unclear/confusing in listing pages

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#466]
Taking [this example](http://www.d-portal.org/ctrack.html?search=&publisher=GB-CHC-326568&usd=GBP#view=active):

![fireshot capture 4 - d-portal_ - http___www d-portal org_ctrack html](https://user-images.githubusercontent.com/1209944/40230948-406fad68-5a91-11e8-9c5f-a8eb4eb1d406.png)

The first activity has £9,000 cited as the "Outgoing Commitment" in the list

When [looking at this activity](http://www.d-portal.org/ctrack.html?search=&publisher=GB-CHC-326568&usd=GBP#view=act&aid=GB-CHC-326568-1376023), it is partly clear that the 9k is made up from the two disbursements, but there is an actual Outgoing Commitment transaction for 10k.  This is confusing, when compared with the listing data....

![fireshot capture 6 - d-portal_ - http___www d-portal org_ctrack html](https://user-images.githubusercontent.com/1209944/40231146-d55fe6d6-5a91-11e8-9002-7064eb0148f8.png)

**Comment by andylolz** [comment]
NB this might seem related to #462, but I don’t think it is!

**Comment by notshi** [comment]
Thanks, both. That definitely does not look right - it shouldn't be a 100% bar either. Will look further.

**Comment by notshi** [comment]
This is now, hopefully, fixed.

For the record, it has nothing to do with #462.

It was cause by a bad mapping between new codes and old codes. We were using the ```name``` to map between the two but this stopped working at some point; if it ever worked at all during the changeover!

Thanks for spotting, @stevieflow.
