### ISSUE TITLE
VVOB- coordinates not showing correctly

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#467]
According to D-Portal, VVOB appears to have a project in the South Atlantic Ocean (see screenshot below); 
http://d-portal.org/ctrack.html?search&publisher=BE-BCE_KBO-0423616717#view=main

![image](https://user-images.githubusercontent.com/24607542/40540250-5d2886b8-600f-11e8-886f-b83cf228937f.png)

VVOB checked all the coordinates again for the 2017-2021 program and it seems that all coordinates are correctly inserted.

Moreover, it seems impossible to "click" on the location to see which project is involved so I am unable to check which activity it relates to.

![image](https://user-images.githubusercontent.com/24607542/40540310-9126a490-600f-11e8-86c2-d4895e8d94e9.png)

 Could you let me know if there is bug or the data has not refreshed properly?

I will then inform VVOB.

**Comment by andylolz** [comment]
Looks like the Ministerio de Educación - Quito (location 3) for this activity:
http://d-portal.org/q.html?aid=BE-BCE_KBO-0423616717-EC_TV_17-21_DGD

[If you hover over the map, a label pops up with the activity name. Then you can compare the co-ordinates of the point on the map with the co-ordinates of the locations on the activity.]

**Comment by PetyaKangalova** [comment]
@andylolz Many thanks for the quick response! Yes, this is correct. It seems that the langitude has been entered incorrectly in the XML.





![image](https://user-images.githubusercontent.com/24607542/40541827-62d7d022-6015-11e8-8f08-d5f676473868.png)

I will close this issue as there is an error with the data and get in touch with VVOB.
