### ISSUE TITLE
Main page for publisher showing different results

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#469]
A publisher just flagged that when navigating to their main page they get different results.

 If you search from the homepage you get the data for all years:
http://d-portal.org/ctrack.html?search&publisher=XM-DAC-41302#view=main

![image](https://user-images.githubusercontent.com/24607542/41042259-167ed012-6999-11e8-8ce7-35033d9ceda3.png)

If you get to ILO's main page via other pages (from a specific activity page for example), then it defaults to 2016:
http://d-portal.org/ctrack.html?publisher=XM-DAC-41302#view=main
 
![image](https://user-images.githubusercontent.com/24607542/41042355-5cb4d626-6999-11e8-8ee9-bb74b724cbb7.png)

Given that in both cases users are directed to the main publisher page it will make sense for them to be identical and show results for all years. Could you have a look and let me know whether this is a bug or the year has been hard coded?
Thanks!

**Comment by k8hughes** [comment]
How long would it take to fix this? If it isn't a massive job it would be good to have it default to all years as standard.

**Comment by jahnvidave** [comment]
Hi,

This has been raised by another organisation who has come across the same issue: The OPEC Fund for International Development (OFID) 

When they get to their main page on d-portal they see this, which only shows 2016, not their most recent data:
http://d-portal.org/ctrack.html?publisher=XI-IATI-OFID#view=main
![image](https://user-images.githubusercontent.com/38503709/50218284-47b2a580-0383-11e9-95fa-78b3b23348d1.png)


Their main page, via the homepage search, shows data for all years:
http://www.d-portal.org/ctrack.html?search&publisher=XI-IATI-OFID#view=main
![image](https://user-images.githubusercontent.com/38503709/50218332-792b7100-0383-11e9-98da-a931daf58449.png)

**Comment by notshi** [comment]
Many thanks, all. This is now fixed to display all years as standard.

**Comment by jahnvidave** [comment]
Thank you!
