### ISSUE TITLE
What determines the order of lists of activities?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#470]
Hi team

Please can you explain how the order of any list of activities is determined?  is it by the order in the original XML, for example?

This has a link to making these lists sortable #385

**Comment by stevieflow** [comment]
@notshi any feedback on this>?

**Comment by notshi** [comment]
Hi @stevieflow - it's currently random and not sorted at all. We'll have to look into getting a proper sorting table system to get this started and apply this to all lists in d-portal.

There are a few other things to prioritise before this can be worked on so it might be a while before we get started on this.
