### ISSUE TITLE
For participating-orgs display their OrganisationType 

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#471]
In the listings of organisation - eg: http://d-portal.org/q.html?aid=XM-DAC-41140-200447 we have a list of participating orgs, and their role

![page](https://user-images.githubusercontent.com/1209944/41094605-ba42edb6-6a46-11e8-9fa6-eb313cb0ae76.png)

The USA example is relevant here.  The onscreen information makes this seem like it is a duplicate

However, in the XML, the differential is that the type attribute indicates that one is a government (10), whilst the other represents a foundation (60).  This is from the [OrganisationType](http://iatistandard.org/203/codelists/OrganisationType/) codelist

```
<participating-org role="1" ref="USA" type="60"/>
<participating-org role="1" ref="USA" type="10"/>
```

It would be useful to print the name for the type code on screen, to help users understand any difference

Of course, those publishing data should also take care in terms of the names they provide, but I still think the case for an addition to the d-portal UI is justified

This also has some relation to other data we may wish to display: #417

**Comment by notshi** [comment]
This is now live - there may be a need to look at this again when published data provided isn't as expected.
When that does happen, do let us know when you spot them, thanks!
