### ISSUE TITLE
humanitarian-scope element not displayed on activity page

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#473]
As of 2.02 there's a new element to detail humanitarian activity - ``humanitarian-scope`` - http://iatistandard.org/203/activity-standard/iati-activities/iati-activity/humanitarian-scope/

I dont think any data published using this element is displayed in d-portal - it'd be useful to enable it , perhaps similar to the recent addition of ``policy-marker`` : https://github.com/devinit/D-Portal/issues/457

**Comment by stevieflow** [comment]
Thanks!

I'd suggest to put it above results, as it is more in line with documents and sectors.  Would be more logical to situate it around those two elements, if possible....

**Comment by notshi** [comment]
Thanks, @stevieflow - the element is now displayed under the participating-org so it doesn't look out of place.
