### ISSUE TITLE
Location data - display all narrative elements on screen (and on map marker?)

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#474]
This example: 

http://d-portal.org/q.html?aid=GB-1-204227

![location](https://user-images.githubusercontent.com/1209944/41856915-238345aa-788e-11e8-9dab-40940bbf4f47.png)

But the XML includes:

```
<location>
<location-reach code="2"/>
<name>
<narrative>Zimbabwe</narrative>
</name>
<description>
<narrative>Representation of country-level for Zimbabwe</narrative>
</description>
<administrative vocabulary="A4" code="ZW"/>
<point srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
<pos>-19.0004310607910010 29.8720226287842010</pos>
</point>
<exactness code="2"/>
<location-class code="1"/>
<feature-designation code="ADM1"/>
</location>
```

For d-portal display, it would be very useful to include the description narrative onscreen - as this can often clarify the name

NB: there's also another description in location - activity-description/narrative

**Comment by notshi** [comment]
This is now live - do let us know if things don't look as expected.

**Comment by notshi** [comment]
Hi @stevieflow - yes, this is regarding to the element on SAVi.

Am unsure what you mean by map pins?

**Comment by stevieflow** [comment]
(this might be best in a new issue @notshi )

Map pins - http://d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=map&lat=30.737611482740075&lng=36.21614999999997&zoom=9

![map](https://user-images.githubusercontent.com/1209944/41922018-19353a76-795c-11e8-9dac-18d5f42bfcb4.png)


When you hover over a pin, the help text seems to be the name of the _activity_ - no info about the specific **_location_** is provided.  

As I say, this might be more work / readjustment of how things are currently setup, so just let me know

**Comment by notshi** [comment]
Hmm, this might be best in a new issue as it's a considerable amount of work (we'll need to add the narratives to the database to display it) and at some point, we might also drop Google Maps (Google is changing the ways things work with their maps) and replace it with another option which will need researching.

**Comment by stevieflow** [comment]
Done: https://github.com/devinit/D-Portal/issues/476
