### ISSUE TITLE
Is d-portal refreshing?

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#478]
Hi,

we've received the following message from Rolf. Is there a reason we know of why the new and updated activities are not displaying on d-portal?

---------------------------------------------------------------
Hi,

I'm trying to figure out why the latest datasets we published are not 
"seen" by the Registry.

For these (new) datasets, the "IATI data updated" field remains empty:

https://iatiregistry.org/dataset/concern_worldwide-activities

https://iatiregistry.org/dataset/concernuk-activities

https://iatiregistry.org/dataset/decp-activities

For an updated dataset, it remains at the older value:

https://iatiregistry.org/dataset/lftwnl-activities

In all of these cases, downloading or previewing the data via the 
Registry shows the correct version, and the latest data is in both 
Andy's and my own snapshots.

But d-portal also doesn't show the new data (perhaps they check the 
"last update" date?).

Before the weekend, I updated the download links to the www2 subdomain, 
because I suspected a change in our DNS records might have interfered, 
but that doesn't seem to have solved the issue.

Is there a way on your end to find out why the new datasets are not 
recognised?

Thanks,

~~Rolf.

**Comment by xriss** [comment]
Just had a look at the logs and it seems a change of url from http://iatistandard.org/ to http://reference.iatistandard.org/ has broken the import step so it never got around to picking up any new changes from the registry.

Have fixed it and it should pick up any new data tonight.

**Comment by amy-silcock** [comment]
Thanks @xriss
