### ISSUE TITLE
Country list not showing

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#479]
![country_down](https://user-images.githubusercontent.com/1515961/42939036-4546f468-8b4c-11e8-8924-ba47f671f116.png)

The country list is not showing up on d-portal - could be an import issue.
We're currently investigating what happened.

**Comment by notshi** [comment]
Looks like Google errored when fetching csv (Google downtime during import).

To prevent this in the future, we will test and not empty the data if it is unavailable; ie. if Google hiccups, we will keep the old data.

**Comment by andylolz** [comment]
> Google errored

https://www.google.com? Or Google App Engine? Or something else?

**Comment by notshi** [comment]
@andylolz - The ctrack data import from [Google spreadhsheet](http://d-portal.org/about.html#sources) returned an HTML error page instead of the data; eg. [country list replaced with ```display:-moz-inline-box```](https://github.com/devinit/D-Portal/commit/b92fa25daac7ea6aff6c94f0ae5a83708e99c933#diff-e61ff464133447910bc7a2809f655fb8L2).

**Comment by andylolz** [comment]
ahhh! Gotcha, thanks for clarifying!

**Comment by andylolz** [comment]
> Country list is now back on d-portal.

Hmm… Looks broken again :\

**Comment by notshi** [comment]
Ok - looks like this is happening daily so we'll have to scrap Google sheets.

**Comment by andylolz** [comment]
You’re using [this, right?](https://docs.google.com/spreadsheets/d/1jpXHDNmJ1WPdrkidEle0Ig13zLlXw4eV6WkbSy6kWk4/pub?single=true&gid=7&output=csv) Maybe you [could try this?](https://docs.google.com/spreadsheets/d/1jpXHDNmJ1WPdrkidEle0Ig13zLlXw4eV6WkbSy6kWk4/export?id=1jpXHDNmJ1WPdrkidEle0Ig13zLlXw4eV6WkbSy6kWk4&gid=7&format=csv)

**Comment by notshi** [comment]
Thing is, we don't trust this source anymore as it's now seen as unreliable. Might move it to Github and pick it up from there.

For the moment, we've turned import for this data off - the data used to be updated frequently but recently, it's only ever updated once a year, at best.

**Comment by andylolz** [comment]
> we don't trust this source anymore

Fair enough, but the URL I sent is a different endpoint. It’s the one the “download as” dialogue in google sheets uses. I think the one you’re using currently is maybe an older version. Would be good to find some documentation to figure out the official route, but I haven’t succeeded so far!

**Comment by notshi** [comment]
Aye, I notice the different endpoint and like you, wasn't able to find any documentation to figure out the same thing. Thanks for looking out for us, @andylolz :}

**Comment by andylolz** [comment]
Haha! Well, I’m just being defensive here because I know lots of organisations (including a former employer of mine) use google spreadsheet CSV URLs extensively, so I’d be surprised if there isn’t a quick fix here that means you could continue to use them. But I don’t mind, really – I have no particular affiliation to google spreadsheets!

**Comment by notshi** [comment]
No worries - we feel the same way. Google spreadsheet is very accessible and would be a shame to stop using but the problem lies in the service (Google) and not the software. Will stew on this proper and see if we can find a compromise when we have more development time.
