### ISSUE TITLE
DHSC data not showing

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#483]
Hi,

The UK Department of Health and Social Care's newest activity file isn't showing on d-portal: https://www.iatiregistry.org/publisher/dhsc. It's their Global Health Research Activities file.

They published a few weeks ago so their data should have been pulled in by now. Their data is appearing in other systems e.g. Datastore and Dashboard.

Please can you have a look into what's causing the error on d-portal? 

Best wishes,

Amy

**Comment by xriss** [comment]
The problem is lots of this sort of thing

<related-activity ref="GB-GOV-10-16_136_102" type="Sibling"/>

where we expect type to be a number not "Sibling".

We should catch this and keep going so I've patched the code to deal with it and it should fix itself in the nightly import.

**Comment by stevieflow** [comment]
Yep - we need some validation on codes, somewhere, somehow.... 

I've posted something in the CoVE repo: https://github.com/OpenDataServices/cove/issues/1051

**Comment by stevieflow** [comment]
(and credit to @andylolz for joining the dots and telling me about this thread)

**Comment by notshi** [comment]
Thanks, all - this is now fixed on d-portal.
