### ISSUE TITLE
https://iatiregistry.org/api/rest/group

### ISSUE THREAD

**Issue by xriss** [devinit/D-Portal#484]
looks like

https://iatiregistry.org/api/rest/group

is no longer working?

So we may have trouble related to this until it starts working again or we find another way of getting all publisher information out of the iati registry?

**Comment by andylolz** [comment]
Erk. Seems worth raising on https://github.com/IATI/ckanext-iati.

Possibly relates to IATI/ckanext-iati#179? Or IATI/ckanext-iati#168? I’m guessing.

**Comment by andylolz** [comment]
Ahh, [according to this](http://docs.ckan.org/en/latest/api/legacy-api.html):

> ## Note
> 
> The REST API was deprecated in CKAN v2.0 and removed starting from CKAN v2.8.

**Comment by notshi** [comment]
Thanks, @andylolz - was in the midst of raising it there when you posted.

**Comment by xriss** [comment]
Looks like

	https://iatiregistry.org/api/3/action/group_list

will get you all the publisher ids and then

	https://iatiregistry.org/api/3/action/group_show?id=........

will get information about the given publisher id

this information is in a slightly different format to what we used to get and lacks some of the previously data.

Fun fact, this API is rate limited or maybe just really slow and since I can not see a way to batch it we must perform a separate request for each publisher which takes forever.

**Comment by andylolz** [comment]
Okay but:
https://iatiregistry.org/api/3/action/help_show?name=group_list

…says:

> Warning: This API request is deprecated. Please use the equivalent one
> on version 3 of the API:
> http://iatiregistry.org/api/action/organization_list

(NB I think that link should actually be http://iatiregistry.org/api/3/action/organization_list !)

Err yeah I would check with the registry people about this, too… I suspect there might be a hidden, speedier way to do the thing you want to do.

**Comment by notshi** [comment]
Yeah, see - the same API request is **not** deprecated on the official CKAN demo site.

https://demo.ckan.org/api/3/action/help_show?name=group_list

And the registry people have little to no documentation.

Fun fact, the 'API' link from the Registry website points to the About page which then points to the latest (unstable and not the version used for the Registry) CKAN API doc site at the bottom of the page.

Rather obscure for new users, I should think.

Unless this gets turned off, we're going to stick with ```group_list``` for now as that is being recommended on the CKAN API doc site.

**Comment by andylolz** [comment]
> Yeah, see - the same API request is not deprecated on the official CKAN demo site.

Demo is running v2.6.6: https://demo.ckan.org/api/3/action/status_show

> And the registry people have little to no documentation.

Agreed. They should absolutely update the README, it is really out of date.

> Fun fact, the 'API' link from the Registry website points to the About page which then points to the latest (unstable and not the version used for the Registry) CKAN API doc site at the bottom of the page.

You’re right – Good point :\ I’ve raised an issue here: IATI/preview-website#239

**Comment by notshi** [comment]
Thanks, @andylolz - hopefully we hear something back from the Derilinx peeps for advice on the right link to use but for the moment, will be sticking to the currently still working url recommended on the CKAN site instead of running around and second guessing.

**Comment by k8hughes** [comment]
We've pinged this issue again:  https://github.com/IATI/ckanext-iati/issues/204 
Hopefully we get an update.
