### ISSUE TITLE
Standard ruleset rule not enforced: `reporting-org` must match org ID in registry

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#487]
The [`reporting-org`](http://reference.iatistandard.org/activity-standard/iati-activities/iati-activity/reporting-org/) standard reference page includes the following rule:

> All activities in an activity xml file must contain the same `@ref` AND this `@ref` must be the same as the `iati-identifier` recorded in the registry publisher record of the account under which this file is published.

It’s also part of the [standard ruleset](http://reference.iatistandard.org/rulesets/standard-ruleset/#reporting-org-ref):

> The identifier MUST be the same as that recorded by the publisher on the IATI Registry

This is basically a security feature. It prevents a publisher reporting activities as if they were a different publisher. However, this security feature doesn’t appear to be enforced by d-portal.

This can be illustrated by [this activity](http://d-portal.org/q.html?aid=US-GOV-11-998-SAQMMA17F2618), which is part of [this dataset](https://iatiregistry.org/dataset/unitedstates-developing_countries_unspecified_us_department_of_state_part18) and published by [this publisher](https://iatiregistry.org/publisher/unitedstates). It says it’s published by [a different publisher](http://d-portal.org/ctrack.html?publisher=US-GOV-11#view=main), with a different org ID.

In order to enforce this, I suggest ignoring activities where the `reporting-org` does not match the org ID in the registry.

**Comment by k8hughes** [comment]
qq does this occur with any users other than the US govt?

**Comment by andylolz** [comment]
> qq does this occur with any users other than the US govt?

@k8hughes about 49 publishers break this ruleset rule at present.

**Comment by andylolz** [comment]
@amy-silcock for example:
http://d-portal.org/q.html?aid=77-ANI-2014000032

Is reported actually reported by [uasd](https://iatiregistry.org/publisher/uasd).

**Comment by amy-silcock** [comment]
Thanks@andylolz. @xriss and @notshi  can you remember why this logic was agreed when d-portal was set up?

**Comment by xriss** [comment]
Originally we did not source data from the registry but from the datastore at which point you cannot enforce this rule, as we simply do not know which file each activity came from as they came mixed together.

Technically we could check now, however, if we ignored activities with the wrong reporting org we would lose about 400,000 activities mostly from the US.

So not something I would recommend.

I would argue that the registry should be rejecting these files and asking the publisher to fix them. If they started doing that then we would follow suit to make sure that nothing gets through but right now I think we are dong the best we can with the available data.

d-portal does not do validation or hide questionable data, we simply display them the best we can.

**Comment by andylolz** [comment]
> d-portal does not do validation or hide questionable data, we simply display them the best we can.

This is cool – this sort of principle suggests d-portal does have a product identity /cc @k8hughes.

Anyway – fair enough. I don’t really mind where validation / rules are enforced. Just that given they exist, they should probably be enforced somewhere. This one is apparently for security, so it seems like it should be enforced (though in practice, I doubt any publisher would do anything nefarious.)

> we would lose about 400,000 activities mostly from the US.

Well, so if I select “United States” from the list of publishers on the homepage, [d-portal currently says they have 1,337 activities](http://d-portal.org/ctrack.html?search&publisher=US-USAGOV#view=main). That’s not correct, but I guess it’s because it’s using `reporting-org`. I can’t search by reporting-org on the homepage, though. So it’s not terribly easy to get at those lost activities anyway.

**Comment by xriss** [comment]
They may be hard to get at by publisher (which is a codelist problem, as the search page only allows known codes) but they do show up elsewhere for instance in country views.

http://d-portal.org/ctrack.html#view=search&publisher=US-GOV-1

is the only numbered code that is listed in the registry but they are using US-GOV-2 US-GOV-3 etc etc and publishing them all under US-USAGOV Maybe this is part way through an updating process and it will eventually be split into multiple publishers?

eg this small dataset

http://preview.iatistandard.org/index.php?url=https%3A//www.foreignassistance.gov/assets/IATI/Antigua_and_Barbuda.xml

has US-GUV-19 , US-GUV-7 and US-GUV-9 data and it all seems to be good data just unknown IDs as far as the registry is concerned.

here US-GUV-19 is "Department of Homeland Security" but the registry does not tell us this

http://d-portal.org/ctrack.html?search&publisher=US-GOV-19#view=main

**Comment by andylolz** [comment]
> all seems to be good data

Yeah it seems mostly fine I guess. But it’s bad in the sense that it breaks [a standard ruleset rule](http://reference.iatistandard.org/rulesets/standard-ruleset/#reporting-org-ref), which was what this ticket was about.

So maybe I’ve got the wrong end of the stick here, but I gather `reporting-org` is supposed to be there for validation, rather than visualisation. I.e. it’s supposed to match the org ID of the publisher on the registry. If it doesn’t, that’s supposed to be a red flag.

At the moment, if it doesn’t match, d-portal doesn’t red flag it / doesn’t hide the activities. That’s okay I guess? But d-portal also displays the new `reporting-org` as if it’s correct, and even creates a publisher page for the `reporting-org`. That seems less okay.

So for instance, d-portal says [this activity](http://d-portal.org/q.html?aid=US-GOV-19-AG-2X-15-0105) was reported by the [Department of Homeland Security](http://d-portal.org/ctrack.html?publisher=US-GOV-19#view=main). I don’t think that’s correct. It was reported by the [United States](http://d-portal.org/ctrack.html?publisher=US-USAGOV#view=main), [just here](https://iatiregistry.org/dataset/unitedstates-ag).

**Comment by notshi** [comment]
Thanks, @andylolz - have raised this in the ckan repo.

**Comment by xriss** [comment]
You are right in the sense that it is technically broken but lots of IATI data is technically broken.

Again if you look at http://preview.iatistandard.org/index.php?url=https%3A//www.foreignassistance.gov/assets/IATI/Antigua_and_Barbuda.xml these IDs are also used for participating-org so the publisher thinks they exist and that publisher provides 40% of the data so we also think they exist.

What is a valid publisher ID is a big question and we certainly considered just scraping all the IDs used in the XML data and picking the most used narrative for each rather than using the registry as the authoritative source. 

As a consumer of the data we try to be as lax as possible in order to get the most useful information out of it.

**Comment by andylolz** [comment]
> What is a valid publisher ID is a big question and we certainly considered just scraping all the IDs used in the XML data and picking the most used narrative for each rather than using the registry as the authoritative source.

Okay so I think you might be muddling publisher IDs with org IDs, and I wonder if that could be a source of confusion here.

Publisher IDs are a small subset of all org IDs. The number of publisher IDs is roughly equal to the number of publishers. Scraping IDs used in XML data will get you lots of org IDs, but most of these won’t be publisher IDs. Indeed, the registry can (mostly) answer the question of what is a valid publisher ID.

The IDs used in `participating-org`s are org IDs, not (necessarily) publisher IDs. 

But look: What we’re talking about here (really) is something fundamental to d-portal. You’re saying that as a consumer of the data, d-portal tries to be as lax as possible in order to get the most useful information out of it. In this ticket, I’m wondering if it might be more useful to be a bit stricter, particularly given how many publishers rely on d-portal as a feedback mechanism. I think you’re hoping the registry will provide that feedback mechanism, and I just can’t see that happening anytime soon.

**Comment by amy-silcock** [comment]
For now, the tech team's recommendation is to leave d-portal as it is.

The issue should be dealt with via validation and the Registry. It's not an issue for d-portal to solve.

In the mean time we're contacting organisations and requesting that they fix their reporting org issues. E.g USG have indicated that they will be correcting the reporting orgs in their files.
