### ISSUE TITLE
Installation instructions missing?

### ISSUE THREAD

**Issue by Schmlughtz007** [devinit/D-Portal#488]
Hi there,

I want to install the D-Portal, but I don't know how, what is the technology used? nodejs? python? .net?
Could anyone point me to where to look

Thanks

**Comment by andylolz** [comment]
Hi @Schmlughtz007!

Random IATI community member here (not a d-portal dev, but thought I’d chip in with a first pass.)

In the [Features section of the README](https://github.com/devinit/D-Portal#features), there’s a link to:

> [Install](https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md) your own d-portal.

You should find more information there.

**Comment by notshi** [comment]
Thanks @andylolz - yes, that should work. It has been tested very recently but if you encounter any problems, please let us know.

**Comment by Schmlughtz007** [comment]
Hi, it's still me ... 

I tested on two different computers, but the error remains the same, is the error related to the **python** version or to the **nodejs** version? 


> node-expat@2.3.17 install D:\Projects\IATI\Web\DPortal\D-Portal\dstore\node_modules\node-expat
> node-gyp rebuild


D:\Projects\IATI\Web\DPortal\D-Portal\dstore\node_modules\node-expat>if not defined npm_config_node_gyp (node "D:\Softs\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Softs\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\Softs\Python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Softs\\nodejs\\node.exe" "D:\\Softs\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\IATI\Web\DPortal\D-Portal\dstore\node_modules\node-expat
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\Roaming\npm-cache\_logs\2018-09-18T20_52_40_940Z-debug.log
npm notice created a lockfile as package-lock.json. You should commit this file.
added 138 packages from 81 contributors and audited 293 packages in 16.906s
found 0 vulnerabilities

**Comment by Schmlughtz007** [comment]
It seems this is well known issue : 
https://github.com/astro/node-expat/issues/166
The solution is to launch powershell in admin mode and then : 
npm install --global --production windows-build-tools

but this is using python 2.7 arghhh

**Comment by k8hughes** [comment]
I'm going to close this issue as Andy has shared the instructions.
