### ISSUE TITLE
Click thru between aggeration tables and breakdowns do not match

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#489]
It seems that the values in the aggregation tables do not match the values that you access on click through.  

This table details DFID by sector, by year:

![firefox_screenshot_2018-09-18t14-33-00 370z](https://user-images.githubusercontent.com/1209944/45694919-35dd1e80-bb58-11e8-8960-6ed7f44b272d.png)

(via: http://www.d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=sectors)

If I click the Agriculture 2016 spend cell in the table I am taken to 

http://www.d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=sector_transactions&year=2016&sector_group=311 , which tells me:

![firefox_screenshot_2018-09-19t12-39-37 018z](https://user-images.githubusercontent.com/1209944/45753668-79479380-bc11-11e8-8069-d6821f35e9d4.png)

Can we understand how we get two very different figure (409,895,000 and 1,137,400,237!)?

I can imagine that this *might* be something to do with how transactions on multi-sector activities could be split, but it'd be useful to understand what the processes behind these two pages would be, first of all

**Comment by notshi** [comment]
Thanks, @stevieflow - this is definitely strange. Could be related to the latest CRS update which still needs checking out. Will look into it.

**Comment by stevieflow** [comment]
Interestingly, this doesnt seem to be a issue common to all publishers

For this one: http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=sectors - the click thru numbers (that are not 0) match (I've raised in #492 that the 0 figures here seem wrong)

**Comment by andylolz** [comment]
In the IFAD example, all activities are assigned to a single sector. In the DFID example, activities have multiple sectors with a sector percentage split.

I think the big table view is factoring in sector percentage split, while the other view (for a specific sector and specific year) isn’t. That’s what causes the discrepancy.

From [the DFID example](http://www.d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=sectors):

![screen shot 2018-10-16 at 23 47 01](https://user-images.githubusercontent.com/464193/47051908-2c1df980-d19e-11e8-8d0c-67f976588bf4.png)

If we click through to [Energy generation and supply (`230`) in 2015](http://www.d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=sector_transactions&year=2015&sector_group=230):

![screen shot 2018-10-16 at 23 51 23](https://user-images.githubusercontent.com/464193/47051985-7acb9380-d19e-11e8-8ac0-7a184184e071.png)

The numbers don’t match up. 117,945 USD ≠ 786,299 USD. Let’s look at [the only activity](http://www.d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=act&aid=GB-1-204784-102):

![screen shot 2018-10-16 at 23 54 29](https://user-images.githubusercontent.com/464193/47052100-ef9ecd80-d19e-11e8-8ae6-5009d97a7888.png)

“Power generation/renewable sources” (`23030`) is a `230` sector code, but the rest aren’t. So only 15% of the spend here is relevant to this sector.

15% of 786,299 USD is 117,945 USD, so this seems to stack up.

I checked a few more and it looks like this is the issue.

**Comment by notshi** [comment]
Thanks, both.

The wording for the click through page should probably be reworded to reflect the data on the page.
This page is currently listing all activities that contribute to that sector for the year.

So listing a total spend is confusing matters as it is calculating all spend, not limited to sector or year.
This is why we get two different figures.

In a way, this page is half built and was originally meant for something else but it has been wired up to the table as a click through.

We will need development time to create the new page for breakdowns to match.

Meanwhile, I'll look into rewording the current click through page.

**Comment by notshi** [comment]
Thanks, both. This should now be fixed.
