### ISSUE TITLE
All sectors all years pie chart doesn't look correct for one publisher 

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#491]
This publisher: http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=main

has a pie chart visualization for all sectors / all years:

![firefox_screenshot_2018-09-18t14-54-06 577z](https://user-images.githubusercontent.com/1209944/45696321-42af4180-bb5b-11e8-82e5-37aa772017b7.png)

The headline for 0% in Fishing (for example) is concerning, as on click thru:

![firefox_screenshot_2018-09-18t14-56-19 164z](https://user-images.githubusercontent.com/1209944/45696383-65d9f100-bb5b-11e8-981c-c468dc9b14e7.png)

Without scrolling through all years, I wanted to query why we have 0 for this category, when there is *some* expenditure declared on the subsequent page

**Comment by xriss** [comment]
This looks like it is caused by NULL values for a transaction getting included in a sum of all values database query which causes the result to be NULL

This will only go wrong for queries that include that transaction so explains why only some results are wrong.

I will take a look at the best way to fix this and get back to you as the quick fix I just tried did not work.

**Comment by xriss** [comment]
This has escalated slightly, currently upgrading the version of postgres and things may be a little bit broken until that completes and then hopefully less broken afterwards.

**Comment by xriss** [comment]
The problem was NaN values, rather than NULL values.

Hopefully this will be fixed by the nightly import forcing them all to 0 instead, will find out in  a few hours.

**Comment by xriss** [comment]
and discovered why we started getting NaN values.

IMF exchange rates download broke about 4 days ago when they switched from http to https should be fixed now but I'm going to have to run another import to get all the values up to date.

**Comment by stevieflow** [comment]
Many thanks
