### ISSUE TITLE
Aggregations of 0 seem wrong

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#492]
Take a look at http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=sectors&year=2014

![firefox_screenshot_2018-09-18t18-34-30 645z](https://user-images.githubusercontent.com/1209944/45708692-fe7f6980-bb79-11e8-8ac8-1ac12b7c2840.png)

If I follow the link for 0 for Agriculture in 2015 

http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=sector_transactions&year=2015&sector_group=311

I get:

![firefox_screenshot_2018-09-18t18-36-28 386z](https://user-images.githubusercontent.com/1209944/45708772-2a025400-bb7a-11e8-93c3-c8141ca07843.png)

This could be similar to #489 & #491 but maybe slightly different?  I just want to check on why this is 0 - as opposed to (random number)

**Comment by andylolz** [comment]
It seems like the problem you are describing here is that the IATI spend figure in the org sectors table doesn’t match the total spend figure when you click through. Is that right? If so, this seems like a duplicate of #489.

> but maybe slightly different?

In what sense?

**Comment by stevieflow** [comment]
@andylolz yes, I think it could be a duplicate of #489, but I wanted to isolate this specifically because of the 0 figure.  I *know* that 0 is wrong, so thought it worth isolating

But - as you describe, the behavior of a mismatch is the same

**Comment by stevieflow** [comment]
Interestingly, this doesnt seem to be a issue common to all publishers

For this one: http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=sectors - the click thru numbers (that are not 0) match (I've raised in #492 that the 0 figures here seem wrong)

**Comment by stevieflow** [comment]
To update this: the click thrus where we have non-0 values actually match in this example: http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41108#view=sectors&year=2014 (hence, this is not applicable to #489)

But the 0 values do mismatch.  I want to query why these are specifically 0

**Comment by stevieflow** [comment]
This has now been fixed via #491
