### ISSUE TITLE
Suggestion: Map - hide filter if no (planned) projects (low priority)

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#493]
On this publisher there are 0 planned projects:

http://www.d-portal.org/ctrack.html?search&publisher=CA-3#view=main

When I flick to the map: http://www.d-portal.org/ctrack.html?search&publisher=CA-3#view=map&lat=11.055457691950169&lng=9.687442992470665&zoom=3

A drop down value still exists for Planned - which results in an empty map:

![firefox_screenshot_2018-09-19t09-59-41 058z](https://user-images.githubusercontent.com/1209944/45746409-21059700-bbfb-11e8-980e-da5e9386e27d.png)

It might be helpful to either remove an option when we know no projects have any of the ``activity-status`` , or provide some kind of onscreen help text...

**Comment by notshi** [comment]
Closed as we are not currently accepting feature requests.
