### ISSUE TITLE
document-link includes a description/narrative field (in 2.03

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#494]
This element was added in 2.03

http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/document-link/description/

It would be useful to enable this on the activity in d-portal, as some publishers may be using it for clarification of their documents

This example: http://d-portal.org/q.html?aid=NL-KVK-27189542-SP16

![firefox_screenshot_2018-09-19t12-17-57 504z](https://user-images.githubusercontent.com/1209944/45752760-7303e800-bc0e-11e8-87f0-1e49b30d8550.png)

whereas the XML includes:`

`<title><narrative>8-page narrative annual report 2016 SP</narrative></title>
<description><narrative>210501 SP Annual Report 2016 - FINAL</narrative></description>`

**Comment by lleirborras** [comment]
👍

**Comment by notshi** [comment]
Thanks, @stevieflow - this is now live on d-portal.

**Comment by stevieflow** [comment]
Thanks
