### ISSUE TITLE
What is cTrack used by d-portal?

### ISSUE THREAD

**Issue by Schmlughtz007** [devinit/D-Portal#495]
When I follow the installation instruction https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md I am stuck at : chapter 3. the Git Bash stops at :  COPY feedback.html -> spa\feedback.html

When I enter the URL, it is redirected to : http://localhost:1408/ctrack.html#view=search with a blank page.

When I look at the View Source I got : 
http://localhost:1408/ctrack.html#view=search
<html lang="en"> 
	<head>
		
		<title>d-portal</title>

		<script src="C:/Program Files/Git/ctrack/jslib/ctrack_loader.js"></script>

This is insane, how could a Website point to C:/Program Files/ ???
did I miss something? what is this cTrack?

**Comment by xriss** [comment]
This is a bug/gotcha in windows git bash, it helpfully replaces / when used on the command line or inside bash scripts with a full windows path. In this case we are passing / as the root of the website and it is mangling it into a windows path.

Sorry I haven't tested on windows in a while and would recommend running in a VM in windows rather than deal with this sort of strangeness...

**Comment by Schmlughtz007** [comment]
Thanks xriss, 

I thought it was me, I was getting mad, at why it was not working... so, is there any chance to fix the issue?

Thx

**Comment by Schmlughtz007** [comment]
It's really amazing, I'm just Web Site on github really work?
After the difficulties I had for installing the D-Portal on Windows, I went to Azure and created an Unbunto Server VM, and followed the instructions. 

After following these steps I got stuck at the same step as for Windows environment i.e. step 3. when I go with firefox to : http://localhost:1408 nothing is shown...

hmmm

**Comment by xriss** [comment]
Maybe if you are running on another virtual machine then you need to use that machines address rather than localhost ?

Anyhow I've removed the use of / from the bash scirpts which will hopefully make windows bash happy but have not tested it yet...

**Comment by Schmlughtz007** [comment]
Thanks Xriss,

It is better now, I'm not having the C:\Program Files, everything is ok, except, now I have one new error : 

SCRIPT1002: SCRIPT1002: Syntax error
ctrack.html (1,1)

 SCRIPT5009: 'ctrack_loader' is not defined
ctrack.html (12,3)

And the screen remains desperately empty

Any idea?
Thx

**Comment by notshi** [comment]
Hi @Schmlughtz007 

I've updated the [readme](https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md#1-install-on-windows) and tested this on Windows - there were a number of things that needed updating, mainly getting node-expat to run (it seems to like v8), so please have another go, if you're still up for it, and let us know if it's working for you.

**Comment by notshi** [comment]
Please see #532 for further queries.
