### ISSUE TITLE
Result values - use commas?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#496]
For legibility (and as per the formatting of budget and transaction values) it'd be useful to format the numbers with a comma, when they are four digits in legth, or more.

Example from: http://d-portal.org/ctrack.html?search&publisher=XM-DAC-41121#view=act&aid=XM-DAC-41121-2017-AFR-CIV

![result](https://user-images.githubusercontent.com/1209944/46125321-7e639e80-c220-11e8-8973-329055820eb3.png)

**Comment by andylolz** [comment]
More about digit grouping in different locales here:
https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping

**Comment by notshi** [comment]
Thanks, both.

In the spirit of consistency, will have a look at implementing commas for result values that are **numbers**.

**Comment by notshi** [comment]
This now live on d-portal.

**Comment by stevieflow** [comment]
Thanks!

**Comment by andylolz** [comment]
Just to flag again that [ISO 31-0](https://en.wikipedia.org/wiki/ISO_31-0#Numbers) says you use a space for digit grouping e.g. 40 000 000 (40 million). Comma and full stop are reserved for use as a decimal sign (depending on your locale).

If your users are in English speaking countries then using commas for digit grouping is fine.

**Comment by andylolz** [comment]
This looks GREAT!

But just to flag again that [ISO 31-0](https://en.wikipedia.org/wiki/ISO_31-0#Numbers) says you use a space for digit grouping e.g. 40 000 000 (40 million). Comma and full stop are reserved for use as a decimal sign (depending on your locale).

If your users are in English speaking countries then using commas for digit grouping is fine.

**Comment by andylolz** [comment]
Also: These big numbers aren’t commified:

![screen shot 2018-10-02 at 10 31 53](https://user-images.githubusercontent.com/464193/46340820-747dd900-c62e-11e8-82d1-4c50abae284b.png)

**Comment by notshi** [comment]
Many thanks for the reminder, @andylolz. Finally got round to doing this - the current figures are now commafied.
