### ISSUE TITLE
Planned Projects list the start date as end date

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#499]
See: http://d-portal.org/ctrack.html?search&country=AF#view=planned

![d-portal 6](https://user-images.githubusercontent.com/1209944/46473325-ae3e1380-c7d7-11e8-9d60-353b13d2ebd9.png)

However, when you access one of these projects:
http://d-portal.org/ctrack.html?search&country=AF#view=act&aid=47122-19-AFG-32A-X

The end date cited in the list is actually a start date

![d-portal 7](https://user-images.githubusercontent.com/1209944/46473353-c150e380-c7d7-11e8-80cc-b0e86a19cd14.png)

**Comment by lleirborras** [comment]
On planed projects sometimes it does not even make sense the end-date. Could a possible solution be using the Start date and update the column label instead?

**Comment by amy-silcock** [comment]
How about using the planned-start date for planned projects, and labeling it as such. @xriss and @notshi would this be possible?

**Comment by notshi** [comment]
Many thanks, all. Apologies - this was a text bug! We are using start dates for the list but labelled it wrongly. Should be fixed now.
