### ISSUE TITLE
Filter by humanitarian flag ?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#500]
I can see on an activity page whether the ``humanitaria`` flag is declared :

eg: http://d-portal.org/q.html?aid=GB-CHC-1065972-DF168

![humanitarian](https://user-images.githubusercontent.com/1209944/47169888-8d5bdf00-d2fc-11e8-98f2-264ade42cb84.png)

At the d-portal search , is it possible to have a filter in order to only see/search humanitarian activities:

- those with ``humanitarian="1" (or ="true") at the ``iati-activity`` element, 
- those with any ``transaction`` that contain a similar declaration ?

**Comment by stevieflow** [comment]
Update: in #501 there's an issue that activities with the ``humanitarian`` flag only at ``transaction`` level, do not get flagged in d-portal

**Comment by stevieflow** [comment]
Adding to this, as I know a humanitarian flag filter is in development on the new search:

http://d-portal.org/ctrack.html#view=search2

However, I can't seem to get this to work -- and think it is to do with the varied True/False true/fale 1/0 boolean strings in use by publishers

Here's a hum activity: http://d-portal.org/q.html?aid=XM-DAC-41140-ML01.08.071.CPA2

It has WFP as a participating-org

Here's the filters for hum activities + WFP as a participating-org: http://d-portal.org/ctrack.html#view=search2&*@humanitarian=1&/participating-org@ref=XM-DAC-41140 (I get 0)

**Comment by notshi** [comment]
Thanks, @stevieflow - this should now be fixed. Do let us know if that's not the case.

The ```humanitarian``` searches are quite intensive so loading might take some patience!

**Comment by stevieflow** [comment]
Yep, thanks - I get results on http://d-portal.org/ctrack.html#view=search2&*@humanitarian=1&/participating-org@ref=XM-DAC-41140 now!
