### ISSUE TITLE
Activities with humanitarian=1 in transactions only, are not flagged as humanitarian

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#501]
Take a look at 

http://d-portal.org/q.html?aid=US-GOV-1-AID-OFDA-G-17-00123

In the XML, there is no ``humanitarian`` flag at the ``iati-activity`` level: 

`<iati-activity xmlns:usg="https://explorer.usaid.gov/" default-currency="USD" hierarchy="1" last-updated-datetime="2018-09-26T14:29:16.914Z" xml:lang="en" generated-datetime="2018-09-26T14:29:16.914Z" version="2.03">`

However, in transactions, there is 

`<transaction humanitarian="1">`

Can these be flagged visually as humanitarian in d-portal, therefore?

**Comment by notshi** [comment]
Thanks, @stevieflow - might need more clarification in terms of the standard. 

From [```<transaction>```](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/):

> ```@humanitarian```
    A process flag to indicate that this transaction relates entirely or partially to humanitarian aid. If the entire activity relates to humanitarian aid this should be reported using iati-activity/```@humanitarian```, rather than for each transaction.

We're currently only displaying a humanitarian flag when an activity is reported using iati-activity/```@humanitarian```, ie. the **entire activity** relates to humanitarian aid.

Maybe we should do it differently for activities with humanitarian related transactions only?

For example:
![screenshot-20181219170257-1018x438](https://user-images.githubusercontent.com/1515961/50235919-fd481d80-03b0-11e9-978d-c657a4eb8557.png)

**Comment by stevieflow** [comment]
Thanks @notshi 

Yes, an interesting issue - it's discussed here too https://discuss.iatistandard.org/t/humanitarian-flag-entirely-or-partially/1229/17

I know the US *only* publish the humanitarian flag at the transaction level, - as the activity level is not applicable.  

For the purposes of indicating something *involves* humanitarian aid on d-portal, I would suggest to include this visual flag whenever an activity has a humanitarian flag, at any level

**Comment by notshi** [comment]
Thanks, @stevieflow have read that thread before and it is still ongoing.

If we include the visual flag for humanitarian activities at transaction level, from a users' perspective, the activity will be the same as an activity that is entirely related to humanitarian aid.

This could be a little tricky for when we add the filter as well - or it could make it simpler - treat either as the same.

Wondering if this might filter down to misunderstandings or confusion about the data?

**Comment by PetyaKangalova** [comment]
> For the purposes of indicating something involves humanitarian aid on d-portal, I would suggest to include this visual flag whenever an activity has a humanitarian flag, at any level

@stevieflow  I agree with @notshi that adding the **same** visual flag, irrespective whether the `@humanitarian `is used at transaction or activity level, will be confusing for users. 

Currently the visual flag for iati-activity/@humanitarian looks like this
![image](https://user-images.githubusercontent.com/24607542/50780788-c07a9280-129b-11e9-9177-f39f0424cefb.png)

The visual flag for iati-activity/transaction/@humanitarian is presented as below

![image](https://user-images.githubusercontent.com/24607542/50779869-5d87fc00-1299-11e9-9673-69d24179a33f.png)

In my opinion the presentation should remain as it is at the moment as it most accurately present the data.

**Comment by stevieflow** [comment]
OK thanks @PetyaKangalova @notshi - I can see what is meant

It'll be interesting to see how #500 would / could be implemented when the humanitarian flag operated in two different ways.
