### ISSUE TITLE
Humanitarian flag on transactions seems to hide transaction date

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#505]
See http://d-portal.org/q.html?aid=US-GOV-1-720FDA18IO00013

![transaction](https://user-images.githubusercontent.com/1209944/50632520-166bd500-0f40-11e9-9300-ce19e7c970d5.png)

Details:

------------------
Operating System
Linux (64-bit)

Screen Resolution
1920 x 1080

Web Browser
Chrome 71.0.3578.98

Web Browser Size
1855 x 935

**Comment by stevieflow** [comment]
related to #501

**Comment by notshi** [comment]
Thanks, @stevieflow - this is now fixed.
