### ISSUE TITLE
Show non-DAC sectors when used (on activity page

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#508]
eg: http://d-portal.org/q.html?aid=XM-OCHA-CBPF-MM-18%2FDDA-3415%2FSA2%2FSNFI%2FINGO%2F11254

This activity does not use a DAC sector, but does include 

`<sector vocabulary="10" code="4" percentage="100.00"/>`

However, the display for d-portal doesn't indicate this:

![sector](https://user-images.githubusercontent.com/1209944/51806300-4624a900-2270-11e9-9469-11451b278e85.png)

**Comment by k8hughes** [comment]
Is it possible to show sector graphs for activities when the publisher isn't using DAC sector codes?
Like the graph displayed on this page:
http://www.d-portal.org/ctrack.html#view=act&aid=XM-DAC-41140-200447

**Comment by stevieflow** [comment]
I'd like to advocate for this development, as humanitarian agencies will increasingly use vocabulary 10 as their sector....

**Comment by andylolz** [comment]
In case it’s helpful…

For sector vocabulary 10, it looks like the codelist is available as JSON here:
http://vocabulary.unocha.org/json/beta-v1/global_coordination_groups.json

…otherwise, the CSV includes French translations:
https://docs.google.com/spreadsheets/d/1SxSircxhXMZCe0PWafCht-whjBdI9UqoeFeSUbiLGc4/export?format=csv&gid=2037574879

**Comment by amy-silcock** [comment]
It would be good to have a way of showing more detail. As vocab 10 is not a replicated codelist there is a question of how d-portal would ensure it's showing the correct values/that the page still exists. I'm also wary of saying yes, so that d-portal then has to start displaying graphs for all sector codelists.

Perhaps there's a way of displaying a graph with the codes and providing a link to the IATI sectorvocab page? And take into consideration how many sector graphs each activity may have.

As only 9 organisations are publishing using vocab 10 currently this is not an urgent priority.

Though from others on how more useful information could be displayed would be good.

**Comment by stevieflow** [comment]
Just to reiterate - my original observation was simply to *show* / print other sector codes when they are in an activity.  No request for graphs or any interpretation - just show what is in the source data

**Comment by notshi** [comment]
Thanks, all.

Non-DAC sectors are now displayed in SAVi in the same section and in similar layout/style as the current sectors apart from the fill colour.

![Screenshot-20190318215903-1017x214](https://user-images.githubusercontent.com/1515961/54566552-1325a880-49c9-11e9-9cb4-6081cf7688b6.png)

It would be good to see an activity with both DAC and non-DAC sectors if anyone has any examples.

**Comment by notshi** [comment]
I've taken another look at this and am not sure this is a good thing to do. It's confusing and I'm not sure it adds to the data 'story' of this activity.

Perhaps I should display it vastly different from the DAC sectors so it's a separate entity altogether. The implications of 'simply showing' something on SAVi is larger than one might think.

**Comment by notshi** [comment]
![Screenshot-20190319011233-1015x229](https://user-images.githubusercontent.com/1515961/54573470-59d4cc00-49e4-11e9-995c-6e9cc19db9b7.png)
Think I'm happy with this final version - after many iterations, separating this as a different section makes it clearer that although these are sectors, they are not the same.

![Screenshot-20190319011208-1035x327](https://user-images.githubusercontent.com/1515961/54573469-59d4cc00-49e4-11e9-824a-c74625312f51.png)
This is an [example](http://d-portal.org/q.html?aid=XM-OCHA-FTS-217833) that mixes DAC and non-DAC sectors. We display the count for DAC sectors only.

Many thanks, all.

**Comment by stevieflow** [comment]
This is great, thanks!

One other thing I noticed was this example: http://d-portal.org/q.html?aid=XM-DAC-41121-2019-AFR-AGO

Here, there are actually four vocabularies in use, including both 98 & 99 - the labels used in d-portal [are as per the code list](http://reference.iatistandard.org/203/codelists/SectorVocabulary/) - but it is slightly difficult to distinguish between them.  I dont think there is anything you can do, however

![rovocab](https://user-images.githubusercontent.com/1209944/54587921-6f181d80-4a19-11e9-9e78-e360e3032a9f.png)

**Comment by stevieflow** [comment]
In terms of the above - I wonder if grouping the sectors by their vocabulary - and presenting the vocabulary name as a "title" might make these instances more legible?

**Comment by notshi** [comment]
Great example!

The non-DAC sectors are already grouped by vocab and listed from most contributions to least.

I wonder, what is IATI's stance on non-DAC codelists. Are we encouraging the usage? Or are we encouraging DAC adoption - assuming there is direct mapping.

**Comment by stevieflow** [comment]
Thanks

> The non-DAC sectors are already grouped by vocab and listed from most contributions to least.

Yes - can see.  I just wonder if a long list like this example is easy to render, or we could give a bit more visual clue

> I wonder, what is IATI's stance on non-DAC codelists.

The creation of a Sector vocabulary codelists suggests to me they are positively encouraged (with DAC being the common / default).  In the humanitarian field, the vocab 10 is more relevant, also
