### ISSUE TITLE
Display transaction/sector data in an activity

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#512]
It's possible to include ``sector`` within a transaction (and also ``recipient-country / region``) within any ``transaction`` element.  The standard implies that if this is done, then the sector should not be used at the activity level.  Regardless, we know publishers such as the US include sector in transactions: 

http://d-portal.org/ctrack.html#view=act&aid=US-GOV-1-SD-AID-FFP-G-16-00035

```
<transaction ref="A9245C64464C">
<transaction-type code="2"/>
<transaction-date iso-date="2016-03-31"/>
<value value-date="2016-03-31">17499656.00</value>
<description>
<narrative>
HUMANITARIAN RESPONSE FOR CONFLICT-AFFECTED POPULATIONS
</narrative>
</description>
<disbursement-channel code="2"/>
<sector code="72040" vocabulary="1">
<narrative>Emergency food aid</narrative>
</sector>
<sector code="7001" vocabulary="99">
<narrative>Protection, Assistance and Solutions</narrative>
</sector>
```

In d-portal we do not indicate this.  It would be very useful to display this data on the activity page, within each transaction

NB: this is *not* a request for any graphs or analysis - just to display the data

**Comment by notshi** [comment]
We now display everything we see in transaction data in the new SAVi.

Example - http://d-portal.org/ctrack.html#view=act&aid=41119-ZW-S8-RT
