### ISSUE TITLE
Display activity defaults

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#513]
Most IATI activities include these elements:

```
<collaboration-type code="1"/>
<default-flow-type code="10"/>
<default-finance-type code="110"/>
<default-aid-type code="C01"/>
<default-tied-status code="5"/>
```
These are not displayed in the activity page - it would be good to do so

NB With the exception of collaboration type, it is possible to override any of these values within transactions.  I'll create a follow up issue on this

**Comment by notshi** [comment]
Thanks, @stevieflow - I'll need to know the usage context of each of these element before I approach displaying them; ie. how useful are these elements for people, balancing the display of useful information and obfuscation.

**Comment by stevieflow** [comment]
Thanks @notshi 

They will provide useful context to any activity, but one thing we might see is that many publishers use the same values

Taking a quick look at two:

- Default Finance Type http://dashboard.iatistandard.org/codelist/2/default-finance-type_@code.html - code 110 is by far most common
- Default Aid Type http://dashboard.iatistandard.org/codelist/2/default-aid-type_@code.html - code C01 is most common

So - unlike sector/country/policy-marker codes where their values help determine the nature of the activity, these codes set a context, which is often in common with many others

Hopefully that helps think about where / how best to position them..?

**Comment by notshi** [comment]
Defaults are now displayed in the new SAVi.
