### ISSUE TITLE
Display transaction "modalities"

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#514]
Within any transaction it is possible to include the following elements

```
<disbursement-channel code="1" />
<flow-type code="10" />
 <finance-type code="110" />
<aid-type code="A01" vocabulary="1" />
<aid-type code="1" vocabulary="2" />
<tied-status code="3" />
```
If these are used by a publisher, it would be useful to display them in the activity page

Notes:

- Disbursement channel element is standalone
- The other elements act to "override" defaults that may have been set at the activity level.  See: #513

**Comment by stevieflow** [comment]
Thanks @notshi 

Yes - can understand the dilemma.  I guess the issue is that this information may convey something important to the user, and could mislead people if it wasn't viewable.  Others may argue that this isn't - but what would be the point of including it in the standard, if that were the case...?  

In the specific case of transaction modalities, a position d-portal could take is to *not* display them, when they are already included via defaults at the activity level...

**Comment by notshi** [comment]
Modalities are now displayed with the new SAVi.

**Comment by stevieflow** [comment]
Thanks @notshi 

> In the specific case of transaction modalities, a position d-portal could take is to not display them, when they are already included via defaults at the activity level...

Can I just double check that the current position is to display them on the page regardless?

**Comment by notshi** [comment]
Yes, that's correct.

We are displaying elements as is from the published file - if they published default and/or transaction modalities, they will be displayed in their sections on the webpage.
