### ISSUE TITLE
Missing publishers on IATI Registry

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#516]
We've noticed a number of US publishers that are not on the Registry so we don't have an automatic way to link their names to their id. 

![Screenshot-20190404142028-654x167](https://user-images.githubusercontent.com/1515961/55558875-e53ca580-56e4-11e9-81c6-74afce9799aa.png)
*Source: [Dash](http://www.d-portal.org/ctrack.html?#view=dash)*

As you can see, this unnamed publisher is reporting most of the activities on IATI.

As an example, looking at this published file, you can see that the **Publisher Identifier does not match the Reporting-org** within the file.

![Screenshot-20190404144227-739x570](https://user-images.githubusercontent.com/1515961/55560392-0a7ee300-56e8-11e9-9c59-b9a4f3f2b686.png)
*Source: [Registry link](https://iatiregistry.org/dataset/unitedstates-developing_countries_unspecified_us_department_of_state_part18)*
![Screenshot-20190404144251-784x255](https://user-images.githubusercontent.com/1515961/55560422-15397800-56e8-11e9-99d9-5ac760d9c68c.png)
*Source: [Preview](http://preview.iatistandard.org/index.php?url=https%3A//www.foreignassistance.gov/assets/iati/developing_countries_unspecified_us_department_of_state_part18.xml)*

According to the [standard](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/reporting-org/):

> All activities in an activity xml file must contain the same ```@ref``` AND this **```@ref``` must be the same as the iati-identifier recorded in the registry publisher record** of the account under which this file is published.

There are 16 publishers identifying as US-GOV-* (2, 6, 7, 9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 26) and the files are published under US-GOV-1 and US-USAGOV.

**Comment by andylolz** [comment]
You are right – thanks for flagging.

Also: Maybe there should be a public issue tracker for data issues! WDYT?

**Comment by notshi** [comment]
@andylolz Yes! We find quite a few of those each time we look at the data so it would be nice to have a dedicated place for such things.

At the moment, we add the [Data](https://github.com/devinit/D-Portal/labels/Data) labels to similar type issues.

**Comment by andylolz** [comment]
We pitched to [make a thing](https://twitter.com/garyjforster/status/1062923862415982592) but we didn’t win :( I wonder if a github repo is the MVP.

Btw see #487 where this same issue last came up. In Sept 2018, @amy-silcock [indicated](https://github.com/devinit/D-Portal/issues/487#issuecomment-424675890) the US gov had been contacted and were in the process of fixing this.

**Comment by notshi** [comment]
A Github repo would be perfect. This way, we can keep track of these issues openly.

Our stance is - the publisher needs to be listed somewhere official so we can get a list of publishers.

The current ruleset **does not help** since you can have a source of activities eg; from the datastore that would contain mixed publishers and having mixed publishers is good data and useful.

**Comment by andylolz** [comment]
> The current ruleset does not help since you can have a source of activities eg; from the datastore that would contain mixed publishers and having mixed publishers is good data and useful.

Yes, we don’t need to go back over #487, which proposed a different solution. I’m just flagging that it raised the same problem. See:

> This can be illustrated by [this activity](http://d-portal.org/q.html?aid=US-GOV-11-998-SAQMMA17F2618), which is part of [this dataset](https://iatiregistry.org/dataset/unitedstates-developing_countries_unspecified_us_department_of_state_part18) and published by [this publisher](https://iatiregistry.org/publisher/unitedstates). It says it’s published by [a different publisher](http://d-portal.org/ctrack.html?publisher=US-GOV-11#view=main), with a different org ID.

**Comment by andylolz** [comment]
> A Github repo would be perfect

How about this one:
https://github.com/aidtransparency/iati-data/issues

**Comment by amy-silcock** [comment]
The US gov reporting should now be fixed, although there's still some more work to do with them around ids.
