### ISSUE TITLE
Bug: Activities with `@humanitarian="true"` are not labelled as humanitarian

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#517]
[This activity](http://d-portal.org/q.html?aid=XM-DAC-41122-Afghanistan-0060%2FA0%2F06%2F014%2F004) has `@humanitarian="1"`, and is flagged as humanitarian.

[This activity](http://d-portal.org/q.html?aid=GB-1-202339-101) has `@humanitarian="true"`, but is not flagged as humanitarian. (Note that `@humanitarian="true"` is also valid XML. In fact, it’s [the canonical representation](https://www.w3.org/TR/xmlschema11-2/#f-booleanCanmap) for a boolean!)

It looks like this needs fixing in activities.css:
https://github.com/devinit/D-Portal/blob/45561c0f05c1fe26de670d7a78864063c596a51b/ctrack/art/high/activities.css#L41-L48

**Comment by notshi** [comment]
Many thanks, @andylolz. We're working on SAVi 2.0 right now and will add that to the list.

**Comment by notshi** [comment]
I feel like it would make more sense to keep this as an explicit codelist; ie. 0 or 1, not 4 possible values.
And maybe stick to that approach consistently throughout the standard.

At the current state, it catches you off guard with it's native xml eccentricities.

**Comment by andylolz** [comment]
I know you know all this, but just to state it here:

It wouldn’t be enforceable at schema level, since true/false are still valid booleans. IATI could recommend using 0/1, but some publishers would still use true/false so you’d still need to handle the edgecase anyway. Plus, just the thought of a long discourse thread proposing this as guidance makes my eyes water. \<Duncan Bannatyne voice\> For that reason, I’m out!

**Comment by stevieflow** [comment]
Hi @andylolz @notshi - thanks for this

We've some evidence here in terms of the use of 1/0 & true/false (and also True/False it seems) in IATI booleans: http://dashboard.iatistandard.org/booleans.html

Note - DFID have just started to include ``humanitarian="true"`` in their data, so it'd be quite useful to see that flagged in d-portal

I'm with @andylolz - so long as you supply a valid boolean, we should be able to use your data

NB: @davidmegginson might be able to point to the ``is_truthy()`` function that deals with a range of booleans...

**Comment by andylolz** [comment]
Thanks, @stevieflow.

> We've some evidence here in terms of the use of 1/0 & true/false (and also True/False it seems) in IATI booleans: http://dashboard.iatistandard.org/booleans.html

^^ Worth noting that this dashboard page lists publishers using `True` and `False` (i.e. title case). These are **invalid values** – `false` and `true` must be lower case according to the XML spec. I’ve made a ticket for that here: IATI/IATI-Dashboard#543

**Comment by stevieflow** [comment]
Denmark use humanitarian="true", I have discovered today: http://d-portal.org/q.html?aid=DK-1-128253-30530

**Comment by notshi** [comment]
Many thanks, both - this is now fixed.
