### ISSUE TITLE
Bug - Default Currency not being used in budget table

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#518]
Hi,

There's a bug on this page: http://www.d-portal.org/ctrack.html?publisher=BE-BCE_KBO-0451857573&usd=EUR#view=countries&year=2018

The allocated and total budget should be the same value, as they are the same in the organisation's activity and organisation file for each country reported.

- The allocated budget column looks to be picking up the currency from each budget, and if not present from the default currency. In this case its EUR.

- However, the total budget column looks to only be picking up the currency from each budget, and if not present presumes it to be USD. In this example fact, the default currency is set to EUR.

I've had a look at some other examples and they follow the logic above. Please can you look into this?

**Comment by notshi** [comment]
Hi @amy-silcock , thanks for reporting - it looks like a conversion problem. Will take a look at this.

**Comment by amy-silcock** [comment]
Great, thanks @notshi!

**Comment by notshi** [comment]
Hi @amy-silcock, thanks for your patience - this was a down to a bug in dealing with org files and should now be fixed.

**Comment by amy-silcock** [comment]
Great, thanks @notshi !
