### ISSUE TITLE
Transaction titles overlay on data (in IE?)

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#520]
I noticed this when working with someone using Internet Explorer

![thumbnail_image001](https://user-images.githubusercontent.com/1209944/57182470-4ea40580-6e97-11e9-9331-d192a605eb62.png)

**Comment by notshi** [comment]
Thanks, @stevieflow - which version of IE is this?

**Comment by stevieflow** [comment]
hmm - it wasn't my machine, so not sure @notshi .. and I've no IE myself to try and check/replicate

**Comment by notshi** [comment]
Will close this for reasons explained here.
 https://github.com/devinit/D-Portal/issues/554#issuecomment-617101290
