### ISSUE TITLE
DAC 3-digit sector codes listed as “NON-DAC”

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#521]
DAC 3-digit sector codes are described as “NON-DAC” which isn’t strictly true.

E.g. here: https://d-portal.org/q.html?aid=XM-OCHAS-HPC6770-2720

**Comment by notshi** [comment]
Thanks, @andylolz - this should now be fixed.

**Comment by andylolz** [comment]
Looks good – thanks!
