### ISSUE TITLE
CRS 2017 update

### ISSUE THREAD

**Issue by xriss** [devinit/D-Portal#522]
The new 2017 CRS data should now be available.

We need it in a similar format to the 2016 data eg:

https://github.com/devinit/D-Portal/blob/master/dstore/csv/crs_2016.csv

https://github.com/devinit/D-Portal/blob/master/dstore/csv/crs_2016_sectors.csv

@k8hughes

**Comment by SJ-bond** [comment]
Yes please, this would be really useful to have in order to build trust in the data, especially for country offices using d-portal.

**Comment by k8hughes** [comment]
These were shared on June 13th so this should be ready to work on now :)

**Comment by xriss** [comment]
Hi @SJ-bond and @k8hughes, CRS data should now be live on the site.
