### ISSUE TITLE
Banner for pages with v1 data

### ISSUE THREAD

**Issue by k8hughes** [devinit/D-Portal#525]
As v1 of the standard has been deprecated we want to notify users when they are on a page that show v1 data.  Could we have a banner that displays only on the pages that have v1 data?

Suggested text:
Data on this page has been published according to version 1 of the IATI Standard, which has now been deprecated. Learn more [link to https://iatistandard.org/en/news/notice-iati-standard-version-1-is-deprecated/]

**Comment by notshi** [comment]
Thanks, @k8hughes - yes, we will do this.

**Comment by notshi** [comment]
This is now live on the site and will be displayed on SAVi for data versioned 1.01 - 1.05.

For example:
http://d-portal.org/ctrack.html?search=Centre%20for%20Indian%20Knowledge%20Systems#view=act&aid=GB-COH-03788027-GPAF-IMP-024
