### ISSUE TITLE
"Where does the money come from" pie chart queries

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [devinit/D-Portal#526]
[GGGI](http://www.d-portal.org/ctrack.html?publisher=XM-DAC-47136#view=main) have raised a couple of queries about the 'Where does the money come from' graph, after noticing that they are shown as money coming 100% from themselves:

1) What is the logic that dictates how this graph is populated
2) Under what circumstances is this graph displayed? It does not seem to appear every time that I navigate to a particular publisher.

Many thanks,
Josh

**Comment by notshi** [comment]
Hi @JoshStanleyDevInit - "Where does the money come from" graph should not be showing for publisher pages so I'm not sure which view they are looking at.

**Comment by JoshStanleyDevInit** [comment]
Hi @notshi,

This is the [link](http://d2c7a4f699c18188fd8599bc72c2c2df.d-portal.org:8000/ctrack.html#view=main) and screenshot that GGGI provided:

![image](https://user-images.githubusercontent.com/46994072/64348283-d38d6000-cfec-11e9-934d-e526bbfc8f37.png)

Thanks,
Josh

**Comment by notshi** [comment]
Hi @JoshStanleyDevInit - this is not an official d-portal link.

It is a preview instance to check uploaded data on d-portal hence the special URL. It should not be confused with the live pages.

**Comment by JoshStanleyDevInit** [comment]
Hi @notshi,

Ah okay - thanks for looking into this and confirming.

Josh
