### ISSUE TITLE
Drill-down error

### ISSUE THREAD

**Issue by bill-anderson** [devinit/D-Portal#527]
1. Selected a filter - Sector = 11110. Returned 9069 active projects
2. Viewed by [recipient countries]( http://d-portal.org/ctrack.html?sector_code=11110#view=countries)
3. Clicked on Nigeria / IATI Spend 2017 cell
4. 16036 projects [returned](http://d-portal.org/ctrack.html?sector_code=11110#view=list_transactions&year=2017&country_code=NG)

**Comment by notshi** [comment]
Thanks, @bill-anderson - that page is listing all projects for Nigeria, regardless of their activity status (active, planned, ended etc).

We should, however, add a column to specify their status so that's more obvious.

**Comment by bill-anderson** [comment]
I think it is listing all sector 11110 projects irrespective of country. First in list is for Argentina.
ah, It's the #view 

This works ...
http://d-portal.org/ctrack.html?sector_code=11110&year=2017&country_code=NG#view=main

rather than 
http://d-portal.org/ctrack.html?sector_code=11110&year=2017&country_code=NG#view=list_transactions

**Comment by notshi** [comment]
Thanks, Bill.
This should now be fixed.
