### ISSUE TITLE
Bahamas/Commonwealth of the Bahamas 

### ISSUE THREAD

**Issue by benparkergit** [devinit/D-Portal#529]
I don't get this country in the d-portal home page drop down although there is at least one IATI activity with `"recipient-country code="BS"` from GlobalGiving. 

It's `US-EIN-300108263-GGProj:25315`

Thanks.

**Comment by notshi** [comment]
Hi @benparkergit - thanks for bringing this up.

Previously, we've only listed countries that align with the current OECD DAC CRS (https://github.com/devinit/D-Portal/issues/458).

However, it is rather easy for us to list all the countries so we have done this and you should be able to view [Bahamas](http://d-portal.org/ctrack.html?country=BS#view=main) on d-portal now. The only difference would be a missing flag and assigned background image on their portals.

Hopefully, this is ok but there might be issues of countries that are not classified as recipient countries listed in there.

**Comment by benparkergit** [comment]
Thanks!
