### ISSUE TITLE
Issue in installation on Windows

### ISSUE THREAD

**Issue by upworka0** [devinit/D-Portal#531]
I tried to install D-Portal on windows system by this readme.
https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md

All progresses were passed successfully. From step 1 to step 6 (Testing local data).

But after run ./serv, I can see only blank screen like this screenshot.
http://prntscr.com/pqx6y0

And I am sure ctrack_loader.js was not loaded correctly in the inspector Network tab.

Is there any special instruction for installation on windows?

**Comment by notshi** [comment]
Hi @upworka0 - many thanks for reporting this.

I've updated the [readme](https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md#1-install-on-windows) and tested this on Windows - there were a number of things that needed updating, mainly getting node-expat to run (it seems to like v8), so please have another go, if you're still up for it, and let us know if it's working for you.

**Comment by notshi** [comment]
Please see https://github.com/devinit/D-Portal/issues/532 for futher queries.
