### ISSUE TITLE
Unable to install the local D-Portal on Windows

### ISSUE THREAD

**Issue by isaacmulamba** [devinit/D-Portal#532]
Hi,

I was able to install D-portal on my local Ubuntu machine but when I tried to follow the procedure to install on Windows, the installation process stopped/hanged. Two issues:

1. While cloning into D-portal, there was a fatal error: unable to check out the working tree. Image1.png attached

![image](https://user-images.githubusercontent.com/56195210/68069538-86511480-fd37-11e9-9830-867c5aa947bf.png)

I have researched stackoverflow, consulted friends...

2. I thought okay, no problem, let's just proceed with the installation. And then, the installation process sort of stopped/hanged, if I can put it that way. I navigated to the browser http://localhost:1408/ but nothing loaded. I tried to troubleshoot in order to understand whether or not a script wasn't loading properly, I saw nothing unusual.

Funny enough, on Ubuntu, this behavior happens but the local D-Portal loads normally, without any problem.

![image](https://user-images.githubusercontent.com/56195210/68069589-6c640180-fd38-11e9-8c37-c45affe8bf57.png)

3. Local D-Portal working on Ubuntu

![image](https://user-images.githubusercontent.com/56195210/68069617-dda3b480-fd38-11e9-909d-44a7a1afbcd9.png)

Please help. What did I do wrong here?

Isaac

**Comment by andylolz** [comment]
The first error says:

```
error: unable to create file dstore/*.import.last.log: Invalid argument
```

That’s due to [this file](https://github.com/devinit/D-Portal/blob/master/dstore/*.import.last.log), which looks as though it might have been added in error?
https://github.com/devinit/D-Portal/commits/master/dstore/*.import.last.log

**Comment by isaacmulamba** [comment]
Thanks, Andy. I might be able to get around that first error by manually getting rid of it. Looks like this error might be leading to the second error because when I researched it, I found that the second error: "Clone succeeded, but checkout failed" might be related to some windows filename issues. I will retry and post a feedback.

**Comment by andylolz** [comment]
Sounds good. So I’d suggest trying the following:
 * fork this repo to https://github.com/isaacmulamba/D-Portal by clicking the "Fork" button
 * remove the file in question via the github interface, by [going here](https://github.com/isaacmulamba/D-Portal/blob/master/dstore/*.import.last.log) and clicking the trash icon
 * then try running `git clone https://github.com/isaacmulamba/D-Portal` on your machine, and see if that does the trick.

**Comment by isaacmulamba** [comment]
Andy, I did remove the file manually and retried, it ran without errors but
still the local D-portal never loaded up. Will continue looking into this
later. Thanks for your suggestions

**Comment by notshi** [comment]
Hi @isaacmulamba - many thanks for reporting this and testing on Ubuntu.

I've updated the [readme](https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md) and tested this on Windows - there were a number of things that needed updating, mainly getting node-expat to run (it seems to like v8), so please have another go, if you're still up for it, and let us know if it's working for you.

**Comment by isaacmulamba** [comment]
Hi @notshi,

I tried it today using Powershell and followed the instructions. Well, I ran into more errors than the last time I ran it...did you try installing it on windows yourself before asking me to try it again? 

Error 1: you know about this

isaac.mulamba@LT-7YFTPW1 MINGW64 ~
$ git clone -c core.symlinks=true https://github.com/devinit/D-Portal
Cloning into 'D-Portal'...
remote: Enumerating objects: 216, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 44019 (delta 148), reused 102 (delta 54), pack-reused 43803
Receiving objects: 100% (44019/44019), 126.84 MiB | 9.69 MiB/s, done.
Resolving deltas: 100% (34957/34957), done.
**error: unable to create file dstore/*.import.last.log: Invalid argument**
Updating files: 100% (867/867), done.
**fatal: unable to checkout working tree**
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Error 2: This is new [and I stopped here to go back to my work, I was at work doing this :)]

isaac.mulamba@LT-7YFTPW1 MINGW64 ~/D-Portal (master)
$ dstore/dstore init
DROPPING jml
CREATE TABLE IF NOT EXISTS jml (  aid  TEXT  PRIMARY KEY  ,  jml  TEXT  );
ALTER TABLE jml ADD COLUMN  aid  TEXT  PRIMARY KEY  ;
ALTER TABLE jml ADD COLUMN  jml  TEXT  ;
DROPPING xson
CREATE TABLE IF NOT EXISTS xson (  aid  TEXT  ,  pid  TEXT  ,  root  TEXT  NOT NULL  ,  xson  TEXT  NOT NULL  );

Thanks,

Isaac

**Comment by xriss** [comment]
Looks like that bad file is getting added by the nightly import scripts. Not sure why, will see if I can track it down as deleting it is not enough.

And yes, we tested on Windows - the instructions on the Readme has been revised and we've re-checked the steps from a clean installation at least 3 times over again just to make absolutely sure.

Have removed it again and will try and stop it getting added back tonight.

**Comment by isaacmulamba** [comment]
Hi @xriss @notshi 

I tried it again, doesn't work on Windows. Wait, I asked two other collaborators to try separately, within minutes they made it work on Ubuntu. One tried to troubleshoot, gave up after two hours; the other suggested deploying an executable docker image on Windows :)

The app deployed on Windows might be useful for me...might! If anyone would deploy the local d-portal in a Linux environment, they might as well just use your web-based portal because in Linux, they will face many limitations.

Thanks,

**Comment by notshi** [comment]
That's correct - we work exclusively in Linux so this should work in Ubuntu.

It was a challenge to make it work in Windows but the current instructions are accurate and do work in Windows 10.

Please make sure you're not using powershell instead of bash and follow the instructions explicitly, preferably from a fresh install; ie. reinstall node v8, reinstall gitforwindows, reclone the repo etc.

These are all setup problems and the environment it's running in - especially given it works in Ubuntu (in minutes).

**Comment by isaacmulamba** [comment]
@notshi I think you meant I should make sure that I am using Powershell, well, I did today, guess what? The process successfully installed Python 2.7 (which I already had installed on my machine, I use Python 2.7 for other applications) and IT STOPPED there...in Powershell :)

Some of these stuffs are very dependent on an environment. You might have just one more variable in your environment that is making all go smooth, and I am missing that, which is making the installation not go well. But I'll get it to work, I'll keep trying.

**Comment by isaacmulamba** [comment]
@notshi I am also happy to know it was a challenge [for you, the developer] to make it work in Windows. When I tell people about the difficulties of working with opensource software, nobody believes me :). opensource sounds nice, free, cheap...but it's more headaches than anything (just like Linux in some cases :)

**Comment by notshi** [comment]
You need to use both powershell **and** git bash for different steps.

**Comment by isaacmulamba** [comment]
Don't worry, this is like the 5th time installing and reinstalling the D-Portal, from different folders...mind you, I got it to work on Ubuntu...so the steps are like engraved in my mind now.

**Comment by isaacmulamba** [comment]
Hi @notshi @xriss 

I made it work. Thanks a lot for your help.

Isaac
