### ISSUE TITLE
Huge activity - out of memory

### ISSUE THREAD

**Issue by xriss** [devinit/D-Portal#533]
We are currently running out of memory parsing this dataset:

https://iatiregistry.org/dataset/usaid-multiple-3

The file is about 120meg of data - which is OK - the problem is that most of that size is contained in a **single** activity with a large number of transactions.

The current way we're doing things now is to split a file at the activities level and only deal with one activity at a time. This current method does not work if a single activity is this big.

Maybe we could check how other people, eg datastore, deal with this file.

@k8hughes @amy-silcock @JoshStanleyDevInit

**Comment by amy-silcock** [comment]
Thanks @xriss I'll check with USAID if this is intended or not. We'll certainly check with others too.

**Comment by siemvaessen** [comment]
Have you tried to increase memory on that machine @xriss ? How much memory is currently allocated to it?

**Comment by xriss** [comment]
Its currently 32gig and I'm not sure that increasing it would help. I suspect it is more of an internal GC related limit. Currently the fail seems to be when it comes to pushing data across to postgres.

I keep *full* activities as a singe field in the database as xml so I can return them easily for display and as postgres jsonb for indexing. So that makes for 80meg single records in this case. The xml I can fix but if I have hit a jsonb limit then I have hard to fix postgres problems.

All things I can look into but it is a considerable amount of work for just one activity.

**Comment by xriss** [comment]
BTW the activity id is US-GOV-1-720000000000.0 and the reason it is so huge is the number of transactions it contains.

I think I can fix this just by increasing the node stacksize when importing, we shall see if it works on the server after todays import.


The activity is available on the new datastore but it does not seem to have any transactions associated with it so I guess it is causing problems there as well?

https://test-datastore.iatistandard.org/api/activities/?iati_identifier=US-GOV-1-720000000000.0&fields=all&format=json

https://test-datastore.iatistandard.org/api/activities/US-GOV-1-720000000000.0/transactions/?format=json

**Comment by xriss** [comment]
and it now imports but is a tad large so rather hard to view

http://d-portal.org/q.html?aid=US-GOV-1-720000000000.0

**Comment by andylolz** [comment]
> oh and just for completeness it is missing from the old datastore

Adding one more to the list: I’ve just spotted that it is also breaking IATI Canary.

**Comment by amy-silcock** [comment]
Update from USAID is that they will look to reduce the size of this activity.

**Comment by amy-silcock** [comment]
USAID have reduced the size of the activity @xriss is all now okay with d-portal?

**Comment by xriss** [comment]
Everything is fine with D-Portal.

We already fixed the out of memory during import, So we have been importing that activity fine although a little slow to display all the transactions it contained.

Currently that activity seems to have been removed. So I hope that is the fix you expect.
