### ISSUE TITLE
Search query aggregate data

### ISSUE THREAD

**Issue by nathanbegbie** [devinit/D-Portal#534]
Hi There 👋 

I'm part of a team that's looking to see if we can build a partner matching tool using IATIdescription data  using NLP. The code is [here](https://github.com/datasciencecampus/iati-partner-search/)

D-Portal seems like a really cool tool and we figured that there was probably a lot of overlap in potential users who might be using D-Portal's search functionality. We were wondering if D-Portal collected any statistics on search usage and whether that's something that could be shared at a high enough level of aggregation?

Please let me know if you have any thoughts!

Nathan

**Comment by notshi** [comment]
Hi @nathanbegbie - thanks for the interest! Your project sounds cool - how far along are you?

We don't collect statistics on search usage at all as we try quite hard not to create data (also privacy issues). This keeps us very lean and portable.

We're currently adding new filters to d-portal and one of the things we're creating is the ability to use external filters so you could use d-portal to display the results of your search. Would this be of interest to you?

**Comment by notshi** [comment]
Hi @nathanbegbie is there still something else we can help you with?

**Comment by notshi** [comment]
Closing this as resolved.
