### ISSUE TITLE
Organisation page: links to XML and to Registry page not correct

### ISSUE THREAD

**Issue by rolfkleef** [devinit/D-Portal#535]
When looking at [an organisation overview page](http://d-portal.org/ctrack.html?reporting_ref=GB-COH-07676886#view=main) there is a section about the organisation file with some links that would be helpful but seem incorrect:

* [View XML](http://d-portal.org/q.xml?aid=GB-COH-07676886): leads to an empty activities file
* View IATI Registry Dataset: leads to a URL with fault variable expansion: http://iatiregistry.org/dataset/%7B_it.@dataset%7D (also the case for View dataset logs)

**Comment by notshi** [comment]
Thanks, @rolfkleef - great catch! We figured we'd fix this before anyone noticed.

We've just added organisation views to d-portal last night so this is still in progress and is part of a major refactoring phase.

- The XML links should now work.
- The dataset URLs will need a re-import so should work tomorrow.

**Comment by notshi** [comment]
By the way, the XML link is should now be http://d-portal.org/q.html?&from=xson&root=/iati-organisations/iati-organisation&pid=GB-COH-07676886

**Comment by notshi** [comment]
Hi @rolfkleef could you confirm if these issues have been fixed? Thanks.

**Comment by rolfkleef** [comment]
Ah yes, all looks fine now, thanks!
