### ISSUE TITLE
Advance filters might benefit from some organisation

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#537]
The advanced filters are great to see, but it's quite a lot to position in front of the user

![d-portal (1)](https://user-images.githubusercontent.com/1209944/69321390-f10cb600-0c3a-11ea-88b6-fb0a808ca6fe.png)

I think these are currently in alphabetical order, but might benefit from another arrangement - I (and others) can no doubt suggest, if helpful

**Comment by notshi** [comment]
Thanks @stevieflow - it was suggested that they are to be arranged alphabetically.

Previously, the filters were arranged in more familiar groupings (at least to me); ie. defaults are grouped together, humanitarian (flag) and tag together, finances together etc.

However, am looking to arrange them according to the standard instead (the way it is listed on the website) - this might be more familiar for people.

These filters are hidden under 'Advance filters' so they won't be too intimidating at first landing. I'm just trying to reduce the number of clicks to get to them.

Ultimately, we don't want to scare new people to the site but also don't want to hide all the options for those that stick around.

**Comment by notshi** [comment]
The current layout is a mild arrangement of most interesting to default modalities at the bottom.
We have kept the policy marker the same place as it was before so people are not taken aback by a new layout.
