### ISSUE TITLE
humanitarian filter - switch instead of dropdown?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#538]
Currently the humanitarian filter is a drop down

As there will only ever be two choices (yes or no), could this be dealt with by an on/off switch , similar to : 

![d-portal (2)](https://user-images.githubusercontent.com/1209944/69321707-77c19300-0c3b-11ea-93af-0c8a031c31de.png)

**Comment by andylolz** [comment]
Ooh, nice idea

**Comment by notshi** [comment]
Actually, the humanitarian filter is 3 states:
1. Disabled
2. Yes
3. No

So it can't be a switch! :}

**Comment by andylolz** [comment]
Ahhh, good point! So that's:
 * All activities
 * Only humanitarian
 * Only development

**Comment by stevieflow** [comment]
Is the first state when the attribute is not present? If so, then I'd
suggest it's a No..?

**Comment by stevieflow** [comment]
I think an on/off switch can still apply though.  In effect, if you select "yes", you just want to filter to activities that have attribute ''@humanitarian="1"'' (or similar) at the ''iati-activity'' element

**Comment by andylolz** [comment]
Right, yeah – so in that case, the options would be:

 * Humanitarian only
 * All activities

I.e. no way of specifying "development only".

**Comment by notshi** [comment]
When we apply filters for the search, we need it to be 3 states.

Apply filters when ```@humanitarian``` =1 or true
Apply filters when ```@humanitarian``` =0 or false
Apply filters regardless if ```@humanitarian``` exists or not; ie. all activities.

The default for no filters is always all activities.

**Comment by stevieflow** [comment]
I see your point @andylolz

My understanding of the humanitarian flag is it is just that - you use it to declare when an activity has some humanitarian aspect.  It's a positive addition you make to the data, rather than an assumption. Before this, it was just assumed that all data was development, i guess

I dont think ^^ helps, although it could paint the user story

- as a d-portal user I want to filter to activities that only have the humanitarian flag, so that I am clear this data is relevant to humanitarian (or something)

**Comment by andylolz** [comment]
> as a d-portal user I want to filter to activities that only have the humanitarian flag, so that I am clear this data is relevant to humanitarian (or something)

Yes, exactly.

Expressing this as user stories is helpful. I find it a bit difficult to come up with the user story for the "`@humanitarian` =0 or false" filter. It’s guaranteed to only return a subset of all development activities, because the `@humanitarian` attribute was only added at v2.02.

**Comment by amy-silcock** [comment]
This has been implemented as a drop down option. This keeps it in the same style as the other filter options.

**Comment by stevieflow** [comment]
> This keeps it in the same style as the other filter options.

Is that the end of the discussion therefore?

**Comment by notshi** [comment]
Closing this as resolved.
