### ISSUE TITLE
Multiple values selected in filters

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [devinit/D-Portal#540]
The Tech Team have a question about the expected functionality when a user selects more than one value for a particular filter.

When you select more than one value in the Publisher field, for example, the number of returned activities is always zero, which suggests the system is looking for activities reported by Publisher A **and** Publisher B.

However, when you select two values in the Recipient Country field (which you know both appear in the same activity), zero results are still returned, which doesn't seem right.

I would expect that the fields work as an AND, in which case Publisher and Activity Status should not have the 'Select one or **multiple options**' text on them, as an activity can only be reported by one publisher, and can only have one activity status.

Or, I would expect the fields to work as an OR, in which case activities should be returned that match any of the given values for each parameter.

Please can you advise how this should be working and whether it is currently working correctly?

Thanks!
Josh

**Comment by xriss** [comment]
Multiple selected values in the same drop down should combine with OR logic and multiple drop downs should combine with AND logic.

But this got broken when adding new filters and is now fixed.

**Comment by JoshStanleyDevInit** [comment]
Looks good, thanks @xriss!
