### ISSUE TITLE
Duplicate organisation-identifier

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#542]
We've been noticing seesaw graphs with the published element ```recipient-org-budget``` in organisation files, indicating 200 counts appearing and disappearing daily by 1 publisher.

![Screenshot-20191215150830-531x775](https://user-images.githubusercontent.com/1515961/70864811-dd105780-1f4d-11ea-932c-fad127b6d1cc.png)

It looks like the org-id **XM-DAC-7** is being used by multiple publishers.

1. https://iatiregistry.org/dataset/minbuza_nl-organisation
2. https://iatiregistry.org/dataset/equileap-org

Equileap, particularly, has published 2 org-id in their organisation file.

![Screenshot-20191215152356-494x358](https://user-images.githubusercontent.com/1515961/70864901-2f05ad00-1f4f-11ea-9ac1-f6ee706224e3.png)

Could we notify the publisher and possibly Aidstream about this? @amy-silcock @devinit/policy-comms-engagement

**Comment by JoshStanleyDevInit** [comment]
Hi @notshi,

In 2018 Equileap, removed XM-DAC-7 on Aidstream, but didn't republish the file.

This has been done now though. so the issue should be fixed.

**Comment by notshi** [comment]
Thanks, @JoshStanleyDevInit - can confirm this is fixed now.
