### ISSUE TITLE
Change default years in "Where does the money come from?"

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#544]
Currently when you search for a country and go into "Where does the money come from?" table, the default view is the below: http://d-portal.org/ctrack.html?country_code=AO#view=donors

![image](https://user-images.githubusercontent.com/24607542/71723034-0ae90d80-2e23-11ea-82e1-887ec0bfa7fe.png)

Given that we are now in 2020, it would make sense for the default view to show more recent years.
Spend for 2018, 2019, 2020 and Budget for 2020, 2021.

Is there a reason why the years were for 2015, 2016,2017?

Many thanks! @WendyMAThomas

**Comment by WendyMAThomas** [comment]
Thanks for adding this, @PetyaKangalova . I am wondering if it would make more sense if the default first year you see is the current year? Or the current year minus one? The rationale is that although you can of course use the arrows to go back and forth, it is helpful it the default view shows one of IATI's main strengths, which is the ability to see current spend and future budget. When it defaults to 2015, 2016 or 2017, it doesn't make it quickly apparent that there is current and future data in IATI.

**Comment by notshi** [comment]
Thanks, both. The default years were chosen for CRS comparison and so that available data could populate the columns; current years had more instances of '0'.

We should be getting 2018 CRS data soon.

![Screenshot-20200104065950-1024x885](https://user-images.githubusercontent.com/1515961/71761172-04f53a00-2ec0-11ea-915b-11278d6e84e8.png)

**Comment by notshi** [comment]
However, there is a bug here in that the years for IATI spend should move one year so it should currently be - 2016, 2017, 2018; ie. the middle column should be the same as the CRS since that's what it sorts to.
