### ISSUE TITLE
United Nations OCHA Financial Tracking Service (UN OCHA FTS)  double counting

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#546]
It looks like there is some leftover data published from an old API that is still in the registry from this particular publisher: [United Nations OCHA Financial Tracking Service (UN OCHA FTS)](http://d-portal.org/ctrack.html?publisher=XM-OCHA-FTS#view=main)

Due to this, there could be instances of double counting.

For example, [these activities](http://d-portal.org/ctrack.html?text_search=Improving%20the%20Food%20Security%20of%20Vulnerable%20Conflict-Affected%20Households%20in%20West%20Darfur.#view=ended) have the same title and various degrees of similar data within but are published by different publishers.

![Screenshot-20200130211609-951x231](https://user-images.githubusercontent.com/1515961/73491161-e2165280-43a5-11ea-8e83-c0b4d6385a63.png)

I suppose they could be totally different projects but the scenario looks suspicious. @amy-silcock @k8hughes @PetyaKangalova

**Comment by stevieflow** [comment]
I can look into this

**Comment by notshi** [comment]
Thanks, @stevieflow - did anything come about from this?

**Comment by stevieflow** [comment]
Thanks @notshi 

Yes - the publication has been withdrawn for now, to refresh / re-enable

But - your example

> published by different publishers.

I think we'd see that regardless, as FTS (and AidData) are primarily secondary publishers (of existing data)?

**Comment by notshi** [comment]
Thanks for the information, @stevieflow.
