### ISSUE TITLE
Ministry of Foreign and European Affairs of the Slovak Republic organisation-identifier mismatch

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#551]
We found that [Ministry of Foreign and European Affairs of the Slovak Republic](https://iatiregistry.org/dataset/slovakaid-69_1_ac) has reported a different ```organisation-identifier``` to their ```reporting-org/@ref``` in their activity and organisation files.

![iati_slo0](https://user-images.githubusercontent.com/1515961/79050947-4c106b00-7c25-11ea-8d3f-503d0d500985.png)

Their ```reporting-org/@ref``` is **XM-DAC-69-1** but they have been publishing data with incremental changes to that identifier.

![iati_slo1](https://user-images.githubusercontent.com/1515961/79050950-4ca90180-7c25-11ea-8704-f40638604c86.png)

This means they now have many profiles on d-portal.

1. No data, just org-file http://d-portal.org/ctrack.html?publisher=XM-DAC-69-1#view=main
2. Data, no org-files
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-00#view=main
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-01#view=main
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-02#view=main
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-03#view=main
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-04#view=main
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-05#view=main
    http://d-portal.org/ctrack.html?publisher=XM-DAC-69-18#view=main

Please advice, thank you @amy-silcock @k8hughes @PetyaKangalova

**Comment by amy-silcock** [comment]
Hi @notshi 

We'll try and get in contact with SlovakAid. This is a data quality issue and not one to fix via d-portal.

**Comment by notshi** [comment]
Thanks, @amy-silcock - I've raised it here and added the [Data](https://github.com/devinit/D-Portal/labels/Data) label for data issues that we found as we don't know where else to report it and so we can keep track of it.

**Comment by notshi** [comment]
Closed as an ignored data problem.
