### ISSUE TITLE
Visualise budgets

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#552]
IS there any plan or possibility to visualise the budget data, along the same lines (and maybe the same graph) as the transactions?

**Comment by notshi** [comment]
Yes, we are in the process of upgrading SAVi which will include both budget and planned-disbursements as graphs.

**Comment by notshi** [comment]
Hi @stevieflow the new SAVi is now live so both budgets and planned-disbursements should include graphs now.

**Comment by stevieflow** [comment]
Yep - I see it!  Thanks.  Will close this specific request, as it's there now!
