### ISSUE TITLE
d-portal not working in IE

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#554]
Is d-portal currently meant to work in Internet Explorer?

This is the issue raised by a user, however, they are able to access d-portal in other browsers.

----------------------------------------------

Hi!

These  two links only show a black page in IE:

http://d-portal.org/ctrack.html?publisher=ES-DIR3-EA0035768#view=main

http://d-portal.org/ctrack.html?publisher=ES-DIR3-EA0035768#view=act&aid=ES-DIR3-EA0035768-Z05-19-01-00800

However if I access using this link:

http://d-portal.org/q.html?aid=ES-DIR3-EA0035768-Z05-19-01-00800

The page of the Project appears correctly.

So, it seems that the mistake is in the ctrack.html

**Comment by notshi** [comment]
Thanks, @amy-silcock - we are not supporting IE for the same reasons as https://github.com/data4development/IATI-data-validator/issues/54.

**Comment by amy-silcock** [comment]
Thanks for the confirmation Shi!
