### ISSUE TITLE
When a single country/region is in an activity, d-portal declares 0%

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#555]
See example:

http://d-portal.org/q.html?aid=47122-RWA-IPV

![d-portal org q html aid 47122-RWA-IPV](https://user-images.githubusercontent.com/1209944/79841872-f029ad00-83af-11ea-9dd8-4263071e18b3.png)

This is the *only* recipient-country / region in this activity:

![d-portal org q xml aid 47122-RWA-IPV](https://user-images.githubusercontent.com/1209944/79842002-26ffc300-83b0-11ea-8bf3-2255d8df74e1.png)

Previously, d-portal would declare the country as 100%, as it was the only one in the activity.  Has this logic now changed?

(For the record, this doesnt seem to impact on aggregation graphs/numbers elsewhere)

**Comment by xriss** [comment]
Should be fixed now.

The new SAVI is a complete rebuild of how SAVI works and an attempt to show as much of the XML data as possible, there may be problems but any new mistakes there should be self contained and not break the rest of the site.

Hopefully :)

**Comment by stevieflow** [comment]
Amazing - thanks for the quick fix!
