### ISSUE TITLE
Combined graph - show before financials

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#557]
See http://d-portal.org/ctrack.html?reporting_ref=GB-CHC-229476#view=act&aid=GB-CHC-229476-WISH2ACTION

![d-portal (29)](https://user-images.githubusercontent.com/1209944/79844083-1b61cb80-83b3-11ea-8f7d-2e3f988b7b0b.png)

The graph that combines budget and transaction data is useful to see

It seems illogical (or a waste of screen real estate!) - to me - that this is presented between the budget and transactions sections - 

![d-portal (30)](https://user-images.githubusercontent.com/1209944/79844243-5401a500-83b3-11ea-87cc-8d8284e61759.png)

Better to present the combined graphs before the budgets (and label it as "Activity Financials" or similar?), and then proceed with the other sections...

**Comment by notshi** [comment]
Thanks, @stevieflow - the charts are now moved before the budgets.

**Comment by stevieflow** [comment]
I noticed this (when on a call) just now.  Thanks!
