### ISSUE TITLE
Multiple narratives not showing when in the same element

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#558]
See this example:

http://d-portal.org/q.html?aid=46002-P-DJ-FA0-003

Here the title is only printed in English:

![d-portal org q html aid 46002-P-DJ-FA0-003](https://user-images.githubusercontent.com/1209944/79979045-cd26f800-8498-11ea-8725-49630f4bd589.png)

Yet - the XML contains English and French, both as narrative elements within the parent title element:

![d-portal org q xml aid 46002-P-DJ-FA0-003](https://user-images.githubusercontent.com/1209944/79979144-f47dc500-8498-11ea-8562-f503e14e2681.png)

Previously, d-portal did display multi-lingual narratives

In this example, the French and English descriptions are actually shown, but that seems to be because they are published as separate XML elements:

![d-portal org q xml aid 46002-P-DJ-FA0-003 (1)](https://user-images.githubusercontent.com/1209944/79979277-2a22ae00-8499-11ea-84e2-12dc97dc9752.png)

**Comment by notshi** [comment]
Thanks for raising this, @stevieflow - multiple narratives are now displayed.
