### ISSUE TITLE
CLASP organisation-identifier mismatch

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#559]
[Collaborative Labeling and Appliance Standards Program](https://iatiregistry.org/dataset/clasp-org) has reported two  ```organisation-identifier``` in their organisation file.

![clasp_org](https://user-images.githubusercontent.com/1515961/80280247-d0b9b980-86fa-11ea-8303-28b470a5c754.png)

![dfid_org](https://user-images.githubusercontent.com/1515961/80280586-d6180380-86fc-11ea-8e93-2a5b3d6f7c8d.png)

This seems to be an [ongoing problem](https://github.com/devinit/D-Portal/issues/487) and should be fixed at the Registry end; checking if both ```@ref``` match and disallowing multiple identifiers.

Please advice, thank you @amy-silcock @k8hughes @PetyaKangalova

**Comment by amy-silcock** [comment]
Technically the Standard allows organisations to do this. However it is a misuse of the elements and certainly not advised.

Could d-portal cross reference the organisation-identifiers against the organisation IATI Org ID on the Registry? And then either:

- only use data from the <iati-organisation> element containing the matching IATI Org ID
- Where multiple <iati-organisation> elements are used, and the publisher is not a @secondary-reporter, ignore the file altogether.

**Comment by notshi** [comment]
Thanks, @amy-silcock - we could but that means we are now changing our stance from 'showing data' to 'validating data'.

It was mentioned in https://github.com/devinit/D-Portal/issues/487#issuecomment-424675890 that the Registry should be doing this instead. Is this now not the case?

**Comment by stevieflow** [comment]
> However it is a misuse of the elements and certainly not advised.

Sorry, I don't agree

The root element of the org file is iati-organisations (plural).  

Its entirely in line with the standard to declare more than one organisation in the org file.  Take a look at [GlobalGiving](https://www.iatiregistry.org/publisher/1437e088-7bfe-4190-82f7-feb6d723c9d5?filetype=Organisation): they have 9,970 organisations in their file, which acts as a quick lookup for their activities (for example).

Incidentally, this same issue exists for the [GlobalGiving d-portal page](https://d-portal.org/ctrack.html?reporting_ref=US-EIN-300108263#view=main), so maybe rename this issue (I'll close my duplicate -- sorry about that)?

**Comment by notshi** [comment]
Closed as an ignored data problem. Please re-open or create a new issue if problem persists.
