### ISSUE TITLE
text_search does not search all descriptions?

### ISSUE THREAD

**Issue by markbrough** [devinit/D-Portal#562]
In the following query (which I understand searches for `COVID` in the title/description) there are no activities funded by Sweden:
https://d-portal.org/q.xml?from=act&limit=-1&distincton=aid&text_search=COVID

However, this activity does contain "COVID" in the description of type `2` (Objectives)
http://d-portal.org/q.html?aid=SE-0-SE-6-5217002501-BGD-12220

I am not sure why this would be - possibly `text_search` does not search all description types?

**Comment by xriss** [comment]
yeah it doesn't, nor does it search non english titles or descriptions. Originally It was intentionally limited to just a few elements, mostly due to speed and the initial database design.

Maybe since we are now exposing much more of the activity through SAVI we should have it search in all narratives in the activity?

**Comment by markbrough** [comment]
That would be awesome, but I think even just starting with the descriptions would be cool!

I was also wondering if it's possible to search for transaction descriptions using the existing endpoints?
https://d-portal.org/q.xml?from=trans&limit=-1&distincton=aid&%2Ftransaction-description/narrative=Total%20Disbursement%20in%20May%20of%202019

i.e. to find this activity (one of its transactions matches that narrative):
http://d-portal.org/q.xml?aid=46002-P-LR-A00-003

NB I was separately trying to see if it's possible to find [this USAID activity](https://d-portal.org/ctrack.html?country_code=NP&reporting_ref=US-GOV-1&sector_code=13030#view=act&aid=US-GOV-1-AID-367-A-16-00006) using the following query, but I don't think it is? NB it uses `humanitarian-scope` at the transaction rather than the activity level, so it doesn't validate against the IATI Standard, but still seems like quite a neat solution:
https://d-portal.org/q.xml?from=trans&limit=-1&distincton=aid&%2Fhumanitarian-scope@code=EP-2020-000012-001

**Comment by markbrough** [comment]
@xriss, thanks so much - this is amazing! dquery looks like a super nice and powerful tool.

I think using dquery I cannot get back the full XML for the relevant activities - so I would then just make a new request to look up those activities by ID, e.g. 
http://d-portal.org/q.xml?aid=US-GOV-1-AID-391-A-17-00002|US-GOV-1-7200AA18M00010

Would that make sense? Many thanks again!

**Comment by xriss** [comment]
You can get the xml but will need to use a sub query to get the full activity data.

So initially I was just getting a bunch of activity ids which the main site can then use as a filter but you want to select the xson at the activity root and have it transformed back into xml like so.

http://d-portal.org/dquery/#%0ASELECT%20*%20FROM%20xson%20WHERE%20root%20=%20'/iati-activities/iati-activity'%20AND%20%20aid%20IN%20(%0ASELECT%20DISTINCT%20aid%0AFROM%20xson%20WHERE%0A%20%20%20%20root%20=%20'/iati-activities/iati-activity/transaction'%0AAND%0A%20%20%20%20xson-%3E%3E'/humanitarian-scope@code'%20=%20'EP-2020-000012-001'%0A)

Click on "Download XSON" and "Download XSON as XML"  in the menu to get a link to run that query and return full activities as xml.

**Comment by amy-silcock** [comment]
For the d-query on COVID-19, we would like it to follow the guidance. For this it would be great for it to be searching all activity titles, description narratives and transaction narratives.

It doesn't need to be searching anything other free-text within the activity.

**Comment by notshi** [comment]
Thanks, @amy-silcock - this change will not affect the COVID-19 search as it is regarding the free-text search only.

**Comment by xriss** [comment]
The text search will now search inside all narrative elements of any language. So more of a full activity search as it is no longer constrained to just the title and description.

As a side effect the COVID-19 has improved slightly as previously it was also not searching in all languages.

**Comment by markbrough** [comment]
Hey @xriss @notshi - just wanted to check if `text_search=COVID` will also look in transaction descriptions? (The new [IATI data use guidance](https://docs.google.com/document/d/1hV_Bk2_VEQmrbSPbp3vE0Rho-gZtOJBSpLkOYInTnOY/edit) suggests searching transaction descriptions for variations of COVID), and some publishers are looking at publishing this data. If not, I guess I could use something like this query:

```sql
SELECT aid FROM xson WHERE root = '/iati-activities/iati-activity' AND  aid IN (
SELECT DISTINCT aid
FROM xson WHERE
    root = '/iati-activities/iati-activity/transaction'
AND
    xson->>'/description/narrative/text()' LIKE '%COVID%'
)
```
([see on dquery](http://d-portal.org/dquery/#%0ASELECT%20aid%20FROM%20xson%20WHERE%20root%20=%20'/iati-activities/iati-activity'%20AND%20%20aid%20IN%20(%0ASELECT%20DISTINCT%20aid%0AFROM%20xson%20WHERE%0A%20%20%20%20root%20=%20'/iati-activities/iati-activity/transaction'%0AAND%0A%20%20%20%20xson-%3E%3E'/description/narrative/text()'%20LIKE%20'%25COVID%25'%0A)))

This should retrieve e.g. this activity, but it doesn't seem to work - I guess I have something wrong in the syntax:
http://d-portal.org/q.xml?aid=XM-DAC-41121-2020-MENA-IRQ

Ideally, I would like to look for anything containing "COVID" - something like this xpath expression, though I am not really familiar with xson!
```
contains(description/narrative/text(), 'COVID-19')
```

Many thanks!!

**Comment by notshi** [comment]
Hi @markbrough yes, ```text_search=COVID``` should also look in transaction descriptions so that activity should be listed; ie.

http://d-portal.org/ctrack.html?text_search=covid#view=act&aid=XM-DAC-41121-2020-MENA-IRQ

We use a subset of xpath expression to describe xml data using json so that particular query will not work. Instead, here's one that does. It's quite an intensive search so will take a while for results to appear.

```sql
SELECT aid FROM xson WHERE root = '/iati-activities/iati-activity' AND aid IN (
SELECT DISTINCT aid
FROM xson WHERE
    root = '/iati-activities/iati-activity/transaction/description/narrative'
AND
    xson->>'' LIKE '%COVID%'
)

```

ps: ```xson``` is something we made up because you have to name things but nonetheless, it is just a json representation of xml. Hope this helps.

**Comment by markbrough** [comment]
Awesome, thanks a lot! I guessed that you were also looking in transaction descriptions under text_search - that is excellent :)

**Comment by markbrough** [comment]
BTW: I have a feeling there is a URL I can use to show through D-Portal IATI-XML data from an (arbitrary) external URL... or am I mistaken?

e.g. to display in the D-Portal interface this IATI-XML file:
https://raw.githubusercontent.com/markbrough/covid19-data/gh-pages/xml/GB-GOV-1-activities.xml

**Comment by markbrough** [comment]
Sorry, I created a new issue for this under #571 - I think this issue can be closed now?
