### ISSUE TITLE
Org file XML doesnt seem to load

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#566]
I cant get the XML link for the Org file to load - after a while it generates a 502 error

Have tried it on a few organisations

**Comment by andylolz** [comment]
So e.g. this?
http://d-portal.org/q.xml?&from=xson&root=/iati-organisations/iati-organisation&pid=GB-GOV-1

**Comment by xriss** [comment]
This is a strange one, I have "fixed" it but the issue needs tp stay open as it seems to be a memory clobbering problem...
