### ISSUE TITLE
Mix up of Org file data?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#567]
Looking at DFID on d-portal:

http://d-portal.org/ctrack.html?reporting_ref=GB-GOV-1#view=main

The org file data doesnt seem to relate / belong to DFID:

![d_portal](https://user-images.githubusercontent.com/1209944/81062777-8096e000-8ece-11ea-9ba7-4b8d7cf9dae0.png)

Looking then at the CLASP Org file: https://aidstream.s3.us-west-2.amazonaws.com/xml/clasp-org.xml

This organisation has as both CLASP and DFID in their org file.  This is entirely legitimate in the standard: 

```
<iati-organisation xmlns:aidstream="http://example.org/aidstream/ns#" last-updated-datetime="2018-02-05T20:48:41+00:00" xml:lang="en" default-currency="USD">
<organisation-identifier>GB-GOV-1</organisation-identifier>
<name>
<narrative xml:lang="en">
UK - Department for International Development (DFID)
</narrative>
</name>
<reporting-org type="21" ref="US-EIN-33-1112770">
<narrative>
Collaborative Labeling and Appliance Standards Program
</narrative>
</reporting-org>
<aidstream:type>10</aidstream:type>
<aidstream:country>GB</aidstream:country>
</iati-organisation>
```

I am guessing that d-portal is looking for the first org file reference for the publisher , and then bringing in that data.  That should generally work, but we see here a flaw

I think this might in turn need to be tied back to the Registry publisher OD< to assure that the canonical org file data is brought in...?

**Comment by xriss** [comment]
Already raised here,

https://github.com/devinit/D-Portal/issues/559

we are not sure how best to deal with it as it seems to be a data problem.

**Comment by stevieflow** [comment]
Sorry - I duplicated #559
