### ISSUE TITLE
Is filtering on custom namespace elements possible?

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#568]
For example, `usg:treasury-account/usg:regular-account@code=72`.

I tried naively tried this one, but wasn’t able to get it to work. Is there some way to apply a filter like this?

Thanks!

**Comment by xriss** [comment]
It should be, although with a few restrictions that you may have hit, although I have not tested it so there may be other problems.

Where exactly is usg:treasury-account/usg:regular-account@code expected?

The restrictions are:

No indexes in the data base so any query will be rather slow.

No repeated elements, so if  usg:treasury-account is repeated multiple times only the last one will be available.

**Comment by xriss** [comment]
OK

there are 65409 results, which means that although the following should work it's a bit too big for it to actually do so...

http://d-portal.org/ctrack.html?aids=http%3A%2F%2Fd-portal.org%2Fdquery%3Fsql%3DSELECT%2520DISTINCT%2520aid%2520FROM%2520xson%250AWHERE%250A%2509root%253D%27%252Fiati-activities%252Fiati-activity%252Ftransaction%27%250AAND%250A%2509xson-%253E%253E%27%252Fusg%253Atreasury-account%252Fusg%253Aregular-account%2540code%27%2520%253D%2520%2772%27%250A#view=main

I'll take a look at the limits I'm putting on the server, it might be OK to raise them a tad

**Comment by xriss** [comment]
and that link should work now as I've bumped the size of requests the server will accept.

and you may want to take a look at the dquery that is used to get what you want

http://d-portal.org/dquery/#SELECT%20DISTINCT%20aid%20FROM%20xson%0AWHERE%0A%09root='/iati-activities/iati-activity/transaction'%0AAND%0A%09xson-%3E%3E'/usg:treasury-account/usg:regular-account@code'%20=%20'72'%0A

The simpler old style q version will not work for non standard elements as they get filtered out.

**Comment by notshi** [comment]
Hi @andylolz - does this work for you? Just wondering if I can close this issue.

**Comment by andylolz** [comment]
Oops! Apologies for not replying. Yes, this is great thanks! Close away.
