### ISSUE TITLE
How to create my own website using d-portal data ?

### ISSUE THREAD

**Issue by romy-n** [devinit/D-Portal#569]
Hello,

I have a concern.
I want to set up an online website that uses data from the d-portal.org site to update my own web site, but I don't know how to do it. The research led me here.

How to make an online website which automatically synchronizes with the d-portal database concerning data from Cameroon?

I have a Windows 10 machine.

Thank you

**Comment by notshi** [comment]
Hi @romy-n 

You can use our widgets from http://d-portal.org/ctrack.html#view=generator

To get data from Cameroon:

1. Pick Cameroon from the RECIPIENT dropdown
2. Choose a VIEW (click on Example Views to see examples)
3. Copy the embed code and paste it into your website like Wordpress

There is also a video on the page that can tell you more about using it.
