### ISSUE TITLE
Generator page not displaying correctly

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#570]
In both firefox and chrome the generator page is not displaying correctly for me: http://d-portal.org/ctrack.html#view=generator

![image](https://user-images.githubusercontent.com/27764077/81547487-d1498580-9373-11ea-9aff-58f1dce55d9c.png)

**Comment by notshi** [comment]
Thanks, @amy-silcock for spotting this - should now be fixed.

**Comment by amy-silcock** [comment]
Thanks Shi!
