### ISSUE TITLE
Displaying data into D-Portal via external URL of IATI-XML data?

### ISSUE THREAD

**Issue by markbrough** [devinit/D-Portal#571]
I don't know if this is at all possible or intended with D-Portal given the architecture - I wanted to check if there is a URL I can use to show through D-Portal IATI-XML data from an (arbitrary) external URL... I thought I had seen something, but from looking at the source code it looks like this is only based on a JSON response, I think with a list of activity IDs. Or am I mistaken?

e.g. I would like to display in the D-Portal interface this IATI-XML file:
https://raw.githubusercontent.com/markbrough/covid19-data/gh-pages/xml/GB-GOV-1-activities.xml

The same way as I can display that file via the IATI Previewer:
http://preview.iatistandard.org/index.php?url=https://raw.githubusercontent.com/markbrough/covid19-data/gh-pages/xml/GB-GOV-1-activities.xml

**Comment by xriss** [comment]
We don't have an easy way to do that via the web but we do publish d-portal to npm, so you could use the command line to convert an xml file to a html file

It's all a bit experimental and untested but try the command line interface, NB you will need npx installed but then you can download and convert your file like so

	curl https://raw.githubusercontent.com/markbrough/covid19-data/gh-pages/xml/GB-GOV-1-activities.xml -o acts.xml
	npx d-portal xml2html acts.xml

That should use curl to download your file to acts.xml and then convert it into acts.html which is then pretty much stand alone, it has some extra javascript loaded from d-portal.org to make some things work (graphs, table sorting) but the html will still look OK if this fails to run eg when you view the local file in your browser.

BTW npx is supposed to cache the d-portal files but it seems to reinstall it every time so this is currently sub optimal and you are better off installing the d-portal code locally and running it from inside node_modules like so

	npm install d-portal # download to node_modules
	node_modules/.bin/d-portal # run from inside node_modules

**Comment by xriss** [comment]
also

If you just want to display multiple activities that are already in d-portal you can just use a list of ids separated by | like so

http://d-portal.org/ctrack.html#view=act&aid=46004-42094-042-GRNT0280|DE-1-201166933

**Comment by notshi** [comment]
Hi @markbrough, did you manage to get this working with npm?

[IATI Switcheroo](https://notshi.github.io/IATIswitcheroo/) allows you to visualise xml/json as d-portal SAVi but it's not via an external URL.

**Comment by notshi** [comment]
@markbrough I'm sure you're aware that this is now possible with portald so I'm assuming this is safe to close?

**Comment by markbrough** [comment]
Yes! Thanks so much @notshi this is super cool!!
