### ISSUE TITLE
Publisher stats page - styling missing?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#572]
Taking a look at https://d-portal.org/ctrack.html?#view=dash_quality&publisher=FI-3 and other pages -- I think the styling has gone astray...?

Tested in Ubuntu 18.04 - Firefox & Chrome

![d_portal (1)](https://user-images.githubusercontent.com/1209944/82584902-0e402400-9b8d-11ea-8d7c-1f0ec2c931cc.png)

**Comment by notshi** [comment]
Thanks for catching this, @stevieflow - should be fixed now.
