### ISSUE TITLE
IMF missing historical exchange rates of currencies

### ISSUE THREAD

**Issue by xriss** [devinit/D-Portal#574]
We are missing exchange rates that we used to have.

These rates are fetched from the IMF directly via
https://www.imf.org/external/np/fin/data/param_rms_mth.aspx

Exchange rates for 1995-2003 are missing and are not accessible via the IMF website.

Missing rate for year 2000
https://www.imf.org/external/np/fin/data/rms_mth.aspx?SelectDate=2000-01-01&reportType=CVSDR&tsvflag=Y

Working rate for year 2004
https://www.imf.org/external/np/fin/data/rms_mth.aspx?SelectDate=2004-01-01&reportType=CVSDR&tsvflag=Y

Can we get the IMF to fix this or is there a better source of this information? @amy-silcock @PetyaKangalova

**Comment by akmiller01** [comment]
The IMF exchange rate indicator itself has many holes in the data, but their GDP figures published in USD and NCU (national currency unit) are much more complete.

So when I calculate exchange rates from IMF data I use the implied exchange rate between indicators "Gross domestic product, current prices, National currency, Billions" (NGDP) and "Gross domestic product, current prices, U.S. dollars, Billions" (NGDPD) for any given country/year combination.

I've also done a bit of work mapping ISO 3166-1 alpha-3 (ISO3 country codes) which are contained in the IMF data and the ISO 4217 (currency codes) which most publishers use in their currency fields, if this is useful to you.

https://github.com/akmiller01/IATI-annual-report-2020/blob/master/currency_codes.csv

ISO 3166-1 alpha-3 is in the column "ISO" and ISO 4217 is in the column "cc." But in reality the data is much messier than just ISO 4217 so some exemptions should be noted, for e.g. https://github.com/akmiller01/IATI-annual-report-2020/blob/master/unfiltered_disagg.py#L10-L28

**Comment by amy-silcock** [comment]
Thanks @akmiller01

**Comment by notshi** [comment]
Closing this is as it is an issue with IMF and we can't do anything about it.
