### ISSUE TITLE
USAID using country code 998 in transactions

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#575]
USAID is publishing 998 as a ```recipient-country@code``` in transactions, when it should be ```recipient-region@code```, so it shows up on the country table.

![Screenshot-20200601233129-959x390](https://user-images.githubusercontent.com/1515961/83461220-0ff8ca00-a460-11ea-8e69-1ef2268b0f4b.png)

http://d-portal.org/ctrack.html?aids=COVID-19#view=list_transactions&country_code=998

@amy-silcock @PetyaKangalova

**Comment by amy-silcock** [comment]
Thanks @notshi I'll get in contact with them.

**Comment by notshi** [comment]
Thanks, @amy-silcock looks like USAID has fixed this.

I'm now seeing Australia AID populating that list instead. Shall I close this issue and open a new one for them?

**Comment by amy-silcock** [comment]
Thanks @notshi, up to you. Happy with either way. I'll get in contact with Australia AID.

**Comment by notshi** [comment]
Thanks, @amy-silcock - will close this and have raised it here https://github.com/devinit/D-Portal/issues/584
