### ISSUE TITLE
d-portal IATI XML is not valis with the IAT XML schema (but can be fixed)

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#576]
I often take an example activity from d-portal and use the XML to model / prototype data changes.  But - the XML out-of-the-box from d-portal is not quite valid against the IATI schema:

So: https://d-portal.org/ctrack.html#view=act&aid=GB-GOV-50-PF-01-BRZ
XML: http://d-portal.org/q.xml?aid=GB-GOV-50-PF-01-BRZ
Validation: https://iati.cove.opendataservices.coop/data/5f7b2986-9aa4-4b84-972d-2f5fe35e7776

The errors are to do with:

- some of the attributes that belong at iati-activity are at iati-activities
- there is an extension in use, but not encoded 

I have to change the original

```
<iati-activities xmlns:iati-extra="http://datastore.iatistandard.org/ns">
<iati-activity dataset="prosperityfund-allocations" default-currency="GBP" generated-datetime="2020-04-22T16:04:04.954146+00:00" version="2.03">
```
to:

```
<iati-activities generated-datetime="2020-04-22T16:04:04.954146+00:00" version="2.03" xmlns:iati-extra="http://datastore.iatistandard.org/ns">
  <iati-activity default-currency="GBP" iati-extra:dataset="prosperityfund-allocations" >
```

Also: The last-update-datetime attribute is also missing from iati-activity.  This does not invalidate the file, but will be in the source data.  I'm guessing this is lost in the ingestion process? (I can create a new ticket for this issue, however?)

I think @markbrough may have also experienced this issue

**Comment by xriss** [comment]
yup

I copy the attributes from iati-activities into iati-activity because after import everything is happening at the activity level. So it makes more sense for them to live there along with a few extra bits and bobs that are only known at import time such as the dataset name.

How the XML data is parsed and used internally has completely changed recently ( to enable full data search in the database ) so these issues have cropped up as this newer complete internal data is now used to generate output XML where it was not used in the past. There are also a few small transforms to this data, such as copying default values down into the data so that they are also searchable.

But not sure why last-update-datetime is going missing, can you give an example in another issue?

Technically I think I should actually be outputting multiple iati-activities in a file with a single iati-activity in each so that these attributes can be given per activity.

Would the validator handle that sort of data?

**Comment by xriss** [comment]
I think there may also still be a few endpoints that will get you the old data which is just complicating things, so I should find and fix all of these as well.

**Comment by stevieflow** [comment]
Thanks @xriss 

> Technically I think I should actually be outputting multiple iati-activities in a file with a single iati-activity in each so that these attributes can be given per activity.

> Would the validator handle that sort of data?

I created a test file: https://gist.github.com/stevieflow/3e0597e644e3c32f74047b672c331726 - this failed validation, I think because iati-activities is the root element

There might be ways to escape that  - @dmegginson @andylolz  might know,....?

**Comment by stevieflow** [comment]
> I copy the attributes from iati-activities into iati-activity because after import everything is happening at the activity level. So it makes more sense for them to live there along with a few extra bits and bobs that are only known at import time such as the dataset name.

Yes, understood.  I guess one way to keep with the XML being valid is to use a namespace to declare the attributes that you move, which render the data invalid.  eg:
```

<iati-activities generated-datetime="2020-04-22T16:04:04.954146+00:00" version="2.03"  xmlns:iati-extra="http://datastore.iatistandard.org/ns">
<iati-activity dataset="prosperityfund-allocations" default-currency="GBP" iati-extra:generated-datetime="2020-04-22T16:04:04.954146+00:00" iati-extra:version="2.03">
```

At least that way you can use the fields where you need them, but then the outut XML will be valid for other users

(NB: I mocked that ^^ example up quickly, so it might be wrong !)

**Comment by xriss** [comment]
I have made a few small tweaks to explicitly include namespaces at import time, will have to wait until tomorrow for this to go live.

Then I still need to sort out what to do with the version numbers...

**Comment by xriss** [comment]
I think this is "fixed", decided it is probably simplest and safest to just add a fake version=2.03 to the output, regardless as to contents. Should cause less problems than the missing version number.

All copied attributes that came from iati-activities use an iati-activities namespace so they become iati-activities:generated-datetime and iati-activities:version when copied into the iati-activity. The same is also done for org files. This makes it pretty obvious what they are and where they came from.

**Comment by xriss** [comment]
BTW I noticed that activity ids with / confuse https://iati.cove.opendataservices.coop/ when given as a link url. Try pasting the following in.

http://d-portal.org/q.xml?aid=XM-OCHA-CBPF-AFG-19/3481/RA4/APC/NGO/14847

**Comment by notshi** [comment]
Hi @stevieflow did the fix work?

**Comment by stevieflow** [comment]
Hi @xriss @notshi many thanks

Yes - the single XML view now seems valid with the schema.  Great stuff

Is it also possible to end the URL with the file extension, eg

http://d-portal.org/q.xml?aid=XM-OCHA-CBPF-AFG-19/3481/RA4/APC/NGO/14847.xml (that might in turn help with validating via tools such as CoVE)?

**Comment by notshi** [comment]
Hi @stevieflow there is already a file extension; ie. q.xml - the rest of the URL is the query string which has to come after the extension.

**Comment by stevieflow** [comment]
Sorry, thanks @notshi - I see the related issue now https://github.com/OpenDataServices/cove/issues/1283 (and that @bjwebb responded)

Therefore, we can close this specific issue.  Thanks
