### ISSUE TITLE
Stichting Onderzoek Multinationale Ondernemingen (SOMO) using version 5.0 in org file

### ISSUE THREAD

**Issue by notshi** [devinit/D-Portal#577]
SOMO is publishing 5.0 ```@version``` in their organisation file.

![Screenshot-20200610133223-1043x279](https://user-images.githubusercontent.com/1515961/84268849-413c5e80-ab20-11ea-8a1f-d5a3b09a2875.png)

https://iatiregistry.org/dataset/somo-org

@amy-silcock @PetyaKangalova

**Comment by amy-silcock** [comment]
I have let the publisher know :)

**Comment by amy-silcock** [comment]
This should now be fixed

**Comment by notshi** [comment]
Thanks, @amy-silcock - can confirm it on our side!
