### ISSUE TITLE
Refine Search no longer filtering COVID-19 activities

### ISSUE THREAD

**Issue by sarahshamiso** [devinit/D-Portal#579]
Previously if you clicked on the COVID-19 "button," and then on Refine Search and entered a value in one of the filters, it would apply the selected filter + the COVID-19 filter. Now, when you do this, it only applies the selected filter and not the COVID-19 filter.

For example, if you click the COVID-19 "button," then click on Refine Search, then enter UNDP under Publisher, it previously would give you only COVID-19 related UNDP activities. Now it gives you all UNDP activities.

**Comment by notshi** [comment]
Hi @sarahshamiso, thank you very much for reporting this.

This is now fixed. http://d-portal.org/ctrack.html?reporting_ref=XM-DAC-41114&aids=COVID-19#view=main

**Comment by sarahshamiso** [comment]
Fantastic -- thank you!

Could you explain what the issue was that caused this to happen?

**Comment by notshi** [comment]
@sarahshamiso Yes, of course.

When we moved the last batch of features to the front page, we kept back a more complicated feature that the COVID-19 search relied on. This led to some incompatibilities and consequently, this bug.\

Hope that explains it.

**Comment by notshi** [comment]
Hi @sarahshamiso - is the refine search working ok for you?

**Comment by sarahshamiso** [comment]
Yes @notshi -- appears to be working now! Thank you!

**Comment by notshi** [comment]
Thank you, @sarahshamiso! I will now close the issue.
