### ISSUE TITLE
D-portal not showing results

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#581]
@xriss and @notshi  d-portal was loading super slowly this morning and now not showing any results. Myself, Amy and Josh all don't get any results. See example below:
![image](https://user-images.githubusercontent.com/24607542/86228187-00b38c00-bb86-11ea-8951-f50def477422.png)

Could you look into this?

**Comment by notshi** [comment]
Thanks, @PetyaKangalova Looks like the database ran out of space so we've flushed out some things that we didn't need so it should be back up and running as per usual again. Let us know if this isn't the case.

**Comment by PetyaKangalova** [comment]
@notshi  many thanks for the quick response. Working fine now so will close the issue :)
Re upgrade I'll mention to Kate and Amy.
