### ISSUE TITLE
CDATA (again)

### ISSUE THREAD

**Issue by rolfkleef** [devinit/D-Portal#582]
It seems that texts encoded in CDATA in IATI files don't get included in d-portal (for example in [this Hivos project](https://d-portal.org/ctrack.html#view=act&aid=NL-KVK-41198677-AFGO_PROJECTCLUSTER-1006707))

I can find an earlier reference to cdata in #124, and when [looking at the code in jml.js](https://github.com/devinit/D-Portal/blob/4ace4434ea305658bfbb03a5e69406b9d96ef647/dflat/js/jml.js#L29) and the [sax-js parser](https://github.com/isaacs/sax-js) I would expect a `parser.oncdata` event handler in the list (I'm not sure how sax-js does this, maybe the ontext event is also fired for cdata?).

**Comment by xriss** [comment]
Should be fixed now. so will pick up data over night.

I had to change the sax parser as the old one was causing build problems and didn't notice that the new one dealt with CDATA slightly differently to the old one.

**Comment by rolfkleef** [comment]
thanks @xriss - looks alright now!
