### ISSUE TITLE
Clicking the COVID-19 button on the homepage results in a permanent loading spinner

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#583]
Clicking [the COVID-19 button](https://d-portal.org/ctrack.html?aids=COVID-19#view=main) on [the homepage](https://d-portal.org/ctrack.html#view=search) results in a permanent loading spinner on Chrome.

Looks like this is a mixed content error – the request made is to an http:// URL.

**Comment by xriss** [comment]
ah, yes, that would be the power of https I think we need to just drop the http from the start of urls and it all works out.

**Comment by andylolz** [comment]
This looks resolved now. Thanks!
