### ISSUE TITLE
Does d-portal show when cached datasets were last successfully downloaded?

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#587]
For example, this activity:
http://d-portal.org/q.html?aid=AU-5-INJ402-WS

[The dataset logs](http://d-portal.org/ctrack.html#view=dash_sluglog&slug=ausgov-ws) show this dataset failed to download today, so dportal used cached data as a fallback:
![Screenshot 2020-07-22 at 11 34 38](https://user-images.githubusercontent.com/464193/88166608-6e942600-cc0f-11ea-8577-07c5ae4b9298.png)

Is there a way to know when this data was last successfully fetched? Does dportal make this information available?

Thanks!

**Comment by notshi** [comment]
Hi @andylolz 

We have logs of that data but we don't show it publicly.
Will see if we can add it to the import logs as well so it shows when the file is last updated as it starts the import.

**Comment by andylolz** [comment]
Adding it to the import logs somehow would be great 💯

**Comment by notshi** [comment]
Hi @andylolz - many thanks for your patience!

The logs should now indicate when the files are successfully downloaded.

**Comment by andylolz** [comment]
Looks great! Thanks for this
