### ISSUE TITLE
Policy marker filter- Gender Equality

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#591]
It seems like D-portal filter incorrectly gives an option of two additional gender policy markers options in the D-Portal policy marker menu (see below 3_1 and 4_1)? The policy significance codelist in IATI specifies that significance 3 and 4 cannot be used for the Gender Equality Marker: https://iatistandard.org/en/iati-standard/203/codelists/policysignificance/

![image](https://user-images.githubusercontent.com/24607542/95844391-c8087e80-0d40-11eb-85ec-852f57c69812.png)

It seems to me that some organisations have incorrectly used the gender marker with significant 3 and 4, therefore showing as an option in the data filter?  Can you please check if that is the case? This to me is a a data quality error. 

In my view we should be following the allowed codelist and not incorporate in the filter the gender equality marker with significance 3 and 4.  Let me know.

**Comment by notshi** [comment]
Thanks for raising this.
There are many exceptions and gotchas in the IATI codelist and guidance that sometimes things get missed.

In the guidance section, it says
> Policy Significance code = 4 (Explicit primary objective) SHOULD ONLY be used in conjunction with Policy Marker code = 9 (Reproductive, Maternal, Newborn and Child Health)

This should be a straightforward change.

However, for Policy Significance code = 3 (principal objective AND in support of an action programme) it says
> For desertification-related aid only

Which marker is this for? Policy Marker code = 8 (Aid Targeting the Objectives of the Convention to Combat Desertification) seems to be the obvious one and if so, could this exception also be listed in the guidance section? @PetyaKangalova

**Comment by PetyaKangalova** [comment]
Thanks a lot @notshi ! And yes, this is the only case where there is guidance for a codelist, so not easy one to find and follow!

> For the  for Policy Significance code = 3 (principal objective AND in support of an action programme) it says
> 
> For desertification-related aid only
> 
> Which marker is this for? Policy Marker code = 8 (Aid Targeting the Objectives of the Convention to Combat Desertification) seems to be the obvious one and if so, could this exception also be listed in the guidance section? @PetyaKangalova

For the above, yes, that is correct.  Will add to documentation.

**Comment by matmaxgeds** [comment]
@PetyaKangalova is this already taken care of in the validator i.e. would it throw an error for the activities that are using this codelist incorrectly?

**Comment by notshi** [comment]
Thanks, @PetyaKangalova - the fix is now live on the website.

Echoing @matmaxgeds concerns as well and that this should also be updated for publishing tools; ie. Aidstream etc if not already so it doesn't contribute to data quality issues down the line.

**Comment by PetyaKangalova** [comment]
@matmaxgeds  and @notshi that is a good catch and this specific check is not in the validator. I'll add to the list.

In the meantime, I got in touch with the DAC to understand how significance 3 works and it looks like it has been [discontinued already.](https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/333)

**Comment by notshi** [comment]
Thanks, @PetyaKangalova 

It looks like you're looking into marking this as *withdrawn* - should it still appear in the drop down?

**Comment by PetyaKangalova** [comment]
@notshi yes, withdrawn codelist still appear in the drop down. So significance 3 will still appear as an option for policy marker 8.

**Comment by notshi** [comment]
Thanks, @PetyaKangalova that's good to know. Let me know if it's ok to close this issue.

**Comment by PetyaKangalova** [comment]
@notshi yes, closing issue now :)
