### ISSUE TITLE
How does results/indicator --> location & dimension work?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#597]
I'm trying to understand as to how this is wired up in d-portal:

Example: http://d-portal.org/q.html?aid=US-EIN-45-2796201-0068

![d-portal-org-q-html-aid-US-EIN-45-2796201-0068](https://user-images.githubusercontent.com/1209944/104437450-aa88c200-5586-11eb-9ec5-4a177b94f615.png)

Here, there's use of dimension , but it's presented visually as a new line, looking as if Actual value is not related to the Target  - illustrated by other fields populated as "Not provided"

However, looking at the XML: http://d-portal.org/q.xml?aid=US-EIN-45-2796201-0068

```
<result type="1">
<title>
<narrative>Paralegals support citizens to seek remedies to land injustice</narrative>
</title>
<indicator measure="1">
<title>
<narrative>number of new paralegal cases documenting land for communities and citizens, particularly smallholder farmers</narrative>
</title>
<baseline value="0" year="2018"/>
<period>
<period-start iso-date="2018-08-01"/>
<period-end iso-date="2021-03-31"/>
<target value="1030">
<comment>
<narrative>Target for lifetime of project - to 31st March 2022</narrative>
</comment>
</target>
<actual value="314">
<dimension name="Kenya" value="11"/>
<dimension name="Sierra Leone" value="12"/>
<dimension name="Myanmar" value="291"/>
<comment>
<narrative>Actual value recorded on January 31, 2020</narrative>
</comment>
</actual>
</period>
</indicator>
</result>
```

The dimension values (linked to the actual) are actually within the same period as the target.  Visually, would we therefore expect to see the Target and Actual presented in the same period line, with the dimension details being situated in relation to the Actual?

==============

In terms of the schema, a dimension (and also location) can be declared in three places:

- result/indicator/baseline
- result/indicator/period/target
- result/indicator/period/actual

(FTR, I don't quite understand why this cannot be situated at - result/indicator/ too - but that's not for you guys !)

I took the [sample XML from the IATI docs](https://raw.githubusercontent.com/IATI/IATI-Extra-Documentation/version-2.03/en/activity-standard/activity-standard-example-annotated.xml) to test this: http://b319646f92668e5acb64c34c565da244.d-portal.org:8000/ctrack.html#view=act&aid=AA-AAA-123456789-ABC123

Here, the dimensions and location are present in all three elements, and populated with the same values.  This looks how we'd expect, I think:

![d-portal (40)](https://user-images.githubusercontent.com/1209944/104439655-40bde780-5589-11eb-83e6-7bff241efc72.png)

I then altered this sample, and changed the values: http://fa7e18ac22866eba830032b5146c2cf2.d-portal.org:8000/ctrack.html#view=act&aid=AA-AAA-123456789-ABC123

Doing this, gives us the same behaviour as in the original example:

![d-portal (41)](https://user-images.githubusercontent.com/1209944/104439796-6fd45900-5589-11eb-8482-07d47be49c91.png)

Here, we can see that the relationship between the target and actual, is now lost (visually)

Hence, I think there needs to be a bit of revision of how d-portal presents this data.  Hope this makes sense - lots of head scratching (at the standard, mainly!)!

**Comment by xriss** [comment]
yeah we are not really sure how it should work...

Currently, we try and group all the data by unique combinations of dimensions and locations (a facet for want of a better term), so if a baseline/target/actual does not have exactly the same combination of these then they are not considered related data and will not show up on the same line for the same date. ( the baseline will also go missing if it is not associated with any period )

I'm not sure that is the right thing to do but it was the best we can could come up with from looking at the data and I think that accounts for everything you are seeing here.

It may make sense in some cases to merge a baseline with no dimension into a target/actual with a dimension but the logic for when and why to do that would be messy so we went with simple logic that is just as reasonable.

**Comment by xriss** [comment]
Oh, I think you may be thinking that a period implies that a single target and actual contained within it are explicitly related to each other.

However there may be *MULTIPLE* targets and actuals within each period, each with different dimensions and locations.

Which is why we have to rearrange everything to try and make sense of it all.

**Comment by stevieflow** [comment]
Thanks @xriss 

> However there may be MULTIPLE targets and actuals within each period, each with different dimensions and locations.

Ah yes - I'd (purposefully) forgot about that!  @andylolz pointed me to this example, to illustrate: http://d-portal.org/q.html?aid=BE-BCE_KBO-0474198059-PROG2017-2021_OS2_BurkinaFaso

That said, I think the original example could be refined.  In this, there's three dimensions, all pegged to the actual.  For baseline and target, there are none. My understanding is that for d-portal to display these together in the same visual period, all three elements would need the exact same dimensions (and/or location) values.   

However, could there not be a tolerance for instances such as this, where within a period there are no conflicting dimensions.  So - I think - that would in turn present the dimension values within the same period....

But generally agree  - complex stuff

**Comment by notshi** [comment]
Hi @stevieflow, thanks for your input.

However, we'd rather keep decisions on our side as simple as possible especially when the standard is so confusing in the area for results. Adding 'tolerances', special cases, etc will only make things more complicated and hide problems in the data.

We've gone through quite a few iterations for displaying IATI results data and this seems to be the simplest ; ie. display what is in the data and if data is not provided, we display it as that.

Your example have conflicting dimensions so they should not be merged.

**Comment by stevieflow** [comment]
Ah ha!

So - I think this issue has helped me understand things so much better!

I took a look at the example I originally cited, and realised it's wrong, in terms of having values for the dimensions in the , erm, values attribute!  

Hence, I rewrote this as follows:

```
    <result type="1">
      <title>
        <narrative>
          Paralegals support citizens to seek remedies to land injustice
        </narrative>
      </title>
      <indicator measure="1">
        <title>
          <narrative>number of affected citizens engaged in resolving grievances related to land justice</narrative>
        </title>
        <baseline value="0" year="2018">
          <dimension name="sex" value="Male" />
        </baseline>
        <baseline value="0" year="2018">
          <dimension name="sex" value="Female" />
        </baseline>
        <period>
          <period-start iso-date="2018-08-01" />
          <period-end iso-date="2021-03-31" />
          <target value="10000">
            <dimension name="sex" value="Male" />
            <comment>
              <narrative>Target for lifetime of project - to 31st March 2024</narrative>
            </comment>
          </target>
          <target value="4000">
            <dimension name="sex" value="Female" />
            <comment>
              <narrative>Target for lifetime of project - to 31st March 2024</narrative>
            </comment>
          </target>
          <actual value="7141">
            <dimension name="sex" value="Male" />
            <comment>
              <narrative>Actual value recorded on August 1, 2020</narrative>
            </comment>
          </actual>
          <actual value="2942">
            <dimension name="sex" value="Female" />
            <comment>
              <narrative>Actual value recorded on August 1, 2020</narrative>
            </comment>
          </actual>
        </period>
      </indicator>
    </result>
```

.. which comes out nicely as 

![d-portal (42)](https://user-images.githubusercontent.com/1209944/104622077-b9579d80-5688-11eb-99a1-dfa62a0c227c.png)

Hooray!

In terms of having the dimension in baseline, target and actual - I can now appreciate why you'd have this - esp in line with d-portal visualisation.  Phew!

I'll maybe submit a PR to the documentation, in terms of having an example of using multiple dimensions , as that then requires multiple baseline, target and actual elements.  

Thanks
