### ISSUE TITLE
Year range filter

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#605]
@xriss  and @notshi  I am helping an organisation explain in their methodology the "Year Range filter".

For [this example](http://d-portal.org/ctrack.html?country_code=KE&year_min=2018&year_max=2018&policy_code=2_1%2C1_1#view=main) - year range min=2018 and max=2018, I get **844 Total.** For active, ended, planned we have an answer [here](http://d-portal.org/faq.html#tech8) when date not specified.

Can you confirm which IATI elements the "Year Range" filter  looks at? 

My understanding is it looks at any activities that have started in or before 2018 (looking at actual or planned start date) and any activities that have ended in or after 2018 (looking at actual/planned end date). Then that is how you get the total number of activities in the example below. Is that correct?

**Comment by notshi** [comment]
Hi @PetyaKangalova 

We look at actual/planned dates for activities that are 'alive' during the min and max year.

Therefore, the activities that started before 31 December 2018 **and** ended after 1 January 2018 to get an overlap of the ranges.

**Comment by PetyaKangalova** [comment]
@notshi  thanks a lot for the speedy response!

**Comment by notshi** [comment]
FYI - the Glossary description has been updated to include this information.
