### ISSUE TITLE
Sightsavers activity file missing from dportal

### ISSUE THREAD

**Issue by lucasfog1** [devinit/D-Portal#606]
Hi everyone,

Yesterday, I changed the URL to Sightsavers' activity file on the IATI Registry (it is now being hosted elsewhere). This morning, DPortal is showing 0 activities (when in fact there are 784).

![0activities](https://user-images.githubusercontent.com/66275247/108191191-c72a9380-710a-11eb-823a-d8ea3dc509c3.png)

I tested the file (located here https://www.sightsavers.org/wp-content/uploads/2021/02/sightsavers_iati_activities_file.xml ) on IATI Validator and it had no errors, and previewed it here successfully: http://d-portal.org:8000/upload

![IATI_Validator](https://user-images.githubusercontent.com/66275247/108192127-c9d9b880-710b-11eb-851f-988a31e3f94a.png)

![Dportal_Test_Results](https://user-images.githubusercontent.com/66275247/108192381-17eebc00-710c-11eb-8cb7-005203ff3d4a.png)

Could someone advise please if this is due to how long DPortal takes to load data from a new URL, or if it's an issue with the file or URL? Our donors use DPortal for compliance so this is quite urgent for us.

Many thanks for your help!

Lucas

**Comment by xriss** [comment]
We had a glitch last night where postgres had an automatic security updated applied during import and a bunch of files failed to import during that downtime.

I've told it not to do that again and things should all be OK after another import, so tomorrow at the latest. Will check up on this issue again then.

**Comment by xriss** [comment]
This seems to be fixed now.

**Comment by lucasfog1** [comment]
Yes, it seems to be fixed now. Thanks @xriss for looking into this.
