### ISSUE TITLE
Unable to download .csv from activity pages in Chrome

### ISSUE THREAD

**Issue by lucasfog1** [devinit/D-Portal#608]
Whenever I try to download a .csv file from any activity page in Chrome, the screen just flashes and nothing happens. It works in Edge browser. Just wanted to flag. Thanks

**Comment by notshi** [comment]
Thanks, @lucasfog1 for the report but we can't replicate it.

Which version of Chrome are you running and do you have any plugins or extensions running on the browser?
If you try to download the .csv file in Incognito mode, does it work?

**Comment by lucasfog1** [comment]
Thanks for your reply @notshi. My colleague was having the same issue so thought I'd report it. Version 88.0.4324.182 (64-bit), no extensions but browser settings is managed by our IT department. It does work in Incognito, so appears to be an issue on our side. Feel free to close this if it can't be replicated.

**Comment by notshi** [comment]
Thanks for the clarification. Will close as we cannot replicate it.
