### ISSUE TITLE
QUESTION: D-portal default aid type

### ISSUE THREAD

**Issue by andreaszenasidi** [devinit/D-Portal#619]
A data user is trying to filter activities by default-aid-type and was inquiring if this also searches at the transaction level. It seems to me that d-portal only searches for the default-aid-type at the activity level and not the aid-type at transaction levels. Could you please confirm if this is indeed the case? If yes, would be useful to add this to the FAQ, I couldn't find any information there about this.

Thank you in advance!

**Comment by notshi** [comment]
Hi @andreaszenasidi it currently filters activities only using the ```default-aid-type``` element hence the labelling includes ```default```. This is the same with the other ```default``` elements; it doesn't search at transaction level.

The links for these filters in the Glossary sends you to their respective IATI standard page definition but yes, it would be useful to explicitly mention that they do not search at transaction level.

However, we are able to allow transaction search as well for all the ```default``` elements.

Would this be preferable and more useful for the data user?
Or is there a case where people specifically want data at ```default``` level only?

**Comment by andreaszenasidi** [comment]
@notshi thank you for confirming how the filter works! 

I will discuss the transaction level search with the team and will raise a separate issue if we want to make a change. 

Thanks again!
