### ISSUE TITLE
Assigning activity and ended status to projects

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#627]
My understanding is that the activity and ended projects are calculated based on the activity dates. CKU have pointed out that the dates shows are their planned end dates, rather than the actual end dates (note, they shouldn't be published actual end dates for non-completed activities).

See here for a the summary of activities:
http://d-portal.org/ctrack.html?reporting_ref=DK-CVR-12006004#view=main 

The shown end dates are pulled from the planned end dates. For example see the first activity:
http://d-portal.org/ctrack.html?reporting_ref=DK-CVR-12006004#view=ended 
![image](https://user-images.githubusercontent.com/27764077/126964481-39a4632b-8450-4bd7-b9c5-2f9d9c48a037.png)

http://d-portal.org/ctrack.html?reporting_ref=DK-CVR-12006004#view=act&aid=DK-CVR-12006004%20DMCDD-19-A-10

![image](https://user-images.githubusercontent.com/27764077/126964360-7d732254-87f5-40d7-a246-7123b8aba4d3.png)

Can the activity active/completed classification use actual end date rather than planned end date.
If there's a past planned end date but no actual end date then the standard presumes that the activity is delayed so is still active.

**Comment by notshi** [comment]
Thanks for raising, @amy-silcock - looks like this was a typo.

Actual start/end dates should always be used over planned dates when found.

This fix is now in and should be live tomorrow. Do let us know otherwise.

**Comment by amy-silcock** [comment]
Thanks @notshi! This looks good to me. I've also asked the publisher to check that everything is as they expect.

**Comment by amy-silcock** [comment]
The publisher has confirmed everything is working as expected.
