### ISSUE TITLE
d-portal not returning results

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#634]
Noticed this morning, d-portal front end isn't able to return search results. Rather it gets stuck on this screen:

![image](https://user-images.githubusercontent.com/27764077/144832282-2fd5427d-bdb7-4d40-b8f7-c18f5fd67269.png)

Unsure if this is a continuation of the issues flagged on Friday https://github.com/devinit/D-Portal/issues/630#issuecomment-985704661

**Comment by notshi** [comment]
Thanks, @amy-silcock we believe this is still teething issues from the streaming option. We're on it.

**Comment by amy-silcock** [comment]
Thanks Shi!

**Comment by notshi** [comment]
Ok - so every time there's an error, it blocks a connection and eventually the database will run out of connections. Previously, we missed one of the possible errors so over time, as more people used d-portal, the error is more likely to be triggered and it clogged up the database.

We've pushed a change that should hopefully, catch all the errors now. Will keep an eye out for anything amiss but appreciate any reports coming in. Many thanks again.

**Comment by amy-silcock** [comment]
Sounds great. Good to see d-portal's front end returning results :)

**Comment by notshi** [comment]
Hi @amy-silcock just checking if the fix working as expected?

**Comment by amy-silcock** [comment]
Hi, the fix is working as I expect
