### ISSUE TITLE
D-portal colour glitch

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#637]
The following e-mail was received by a d-portal data user:

Dear IATI Support,

I’m guessing this is a slight glitch in the new deployment of d-portal, but I notice the colour scheme of d-portal is different depending on the URL.

Here it has a background image and the normal white text on black:

https://d-portal.org/ctrack.html?country_code=AF&reporting_ref=XM-DAC-41121#view=act&aid=XM-DAC-41121-2021-ASO-AFG

 
![image](https://user-images.githubusercontent.com/27764077/145376333-164dfafa-f77f-41eb-b2e3-ce393936c42c.png)

And here it is with black text on white:

![image](https://user-images.githubusercontent.com/27764077/145376254-a85b6dae-0c9b-4c9a-9798-8e2011b48c83.png)

https://d-portal.org/q.html?aid=XM-DAC-41121-2021-ASO-AFG

I got that after clicking on the link after “IATI IDENTIFIER” (something I often do to get share a clean URL to the activity).

I’ve tested this in Firefox and Edge with the same results.

**Comment by notshi** [comment]
Thanks, @amy-silcock the fix should now be live.

The clean URL has been updated to a SAVi url.
Anything with 'q' is a query so it returns an unstyled html page as it is built server-side.

This change is part of the streaming option where all the output from d-portal is now using the same generation; previously it was separate for each endpoint and there were a few endpoints.

The updated urls are, for example:

https://d-portal.org/savi/?aid=XM-DAC-41121-2021-ASO-AFG for an activity
https://d-portal.org/savi/?pid=XM-DAC-41121 for an organisation

Below are all the instances where the urls have been changed:

```
@iati-identifier
@organisation-identifier
transaction > provider-org@provider-activity-id
transaction > receiver-org@receiver-activity-id
participating-org > @activity-id
related-activity > @ref
```

If we missed any links, do let us know.

**Comment by amy-silcock** [comment]
Thanks @notshi,

I've tested the links all the above links are working for me. The planned-disbursement activity-id is also working as expected.
