### ISSUE TITLE
GEF Secretariat- "AG" country search not returning results

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#638]
[GEF activity file](https://d2mxkr7359ifh6.cloudfront.net/GEF/AG.xml) includes 4 activities that include recipient-country AG: https://iatiregistry.org/dataset/gef-ag
![image](https://user-images.githubusercontent.com/24607542/148760383-93887ce2-37eb-4567-bf00-f0725abfb830.png)

Searching on d-portal for publisher "GEF Secretariat" and country "Antigua and Barbuda- AG" returns 0 results: http://d-portal.org/ctrack.html#view=search&country_code=AG&reporting_ref=XI-BRIDGE-6385676864

If I just search the activity id, I can find the project: http://d-portal.org/ctrack.html#view=act&aid=XI-BRIDGE-6385676864-5390
![image](https://user-images.githubusercontent.com/24607542/148760782-9ebe8b24-bc79-459d-ac06-676eb6d8d61d.png). However, it doesn't look  like it is picking up the recipient country and also seems like the page hasn't fully loaded (blue line in the screenshot).

Could you look into that? GEF have thousands of files and we have asked them to reduce the number of files. I wonder if there is an issue loading the data.

**Comment by notshi** [comment]
Thanks, @PetyaKangalova for raising.

Looks like the publisher has used the identifier, XI-BRIDGE-6385676864-5390 for duplicate activities and d-portal can only display one; ie. in this case, we've picked up the activity from the dataset, gef-5390.

Here are the datasets on the registry:
1. https://iatiregistry.org/dataset/gef-ag (4 activities)
2. https://iatiregistry.org/dataset/gef-5390 (1 activity)

For comparison, here is the data you expect from dataset gef-ag on d-preview.
http://f24f4e769cb4f70f1b9034aaa49bc1c0.d-preview.codeforiati.org/ctrack.html#view=act&aid=XI-BRIDGE-6385676864-5390

**Comment by notshi** [comment]
Looking closer, it looks like the publisher has added a bunch of new datasets but have not removed the old datasets that contain the same activities; ie. country datasets (newly added 2 days ago) and individual activity datasets (3 months old).

In some instances, there is even a duplicate country dataset; ie. https://iatiregistry.org/dataset/gef-6385676864-af and https://iatiregistry.org/dataset/gef-af

**Comment by PetyaKangalova** [comment]
@notshi  thanks so much! Should have checked for duplicates first but assumed it was a different issue. They indeed have quite a few duplicate activities that need to be fixed: http://dashboard.iatistandard.org/stats/current/aggregated-publisher/gef/publisher_duplicate_identifiers.json

I'll get back to them, so closing this issue as it is nothing to do with d-portal not picking up the data :)
