### ISSUE TITLE
QUESTION: WWF Paraguay's activity doesn't show up in d-portal

### ISSUE THREAD

**Issue by andreaszenasidi** [devinit/D-Portal#643]
The publisher reported that WWF Paraguay's activity doesn't show up in d-portal. I can't see any obvious reason why or I am missing something. Would be great to understand why it doesn't show up.

**Registry:** https://iatiregistry.org/publisher/wwf-py
**Activity dataset:** https://iatiregistry.org/dataset/wwf-py-activities

**Comment by notshi** [comment]
Thanks for raising, @andreaszenasidi - I can see there is one activity in the dataset and one org file.

![Screenshot 2022-04-04 at 15-54-00 - Organizations - IATI Registry](https://user-images.githubusercontent.com/1515961/161571872-3f0bf653-82ed-4a80-a80b-5d4c8f90ce55.png)

Both of these show up in d-portal via the [Publisher d-portal](http://d-portal.org/ctrack.html?publisher=PY-RUC-80025907-6) link on the registry.

![Screenshot 2022-04-04 at 15-54-21 d-portal](https://user-images.githubusercontent.com/1515961/161571900-fb7dbf03-a5e7-42cf-84fb-56fbc9f8c592.png)

Is this not what you were expecting?

The one thing that seems out of place is the publisher name not showing up on d-portal.
The name is also not displaying on the [dashboard](http://dashboard.iatistandard.org/publisher/wwf-py.html).

![Screenshot from 2022-04-04 15-59-55](https://user-images.githubusercontent.com/1515961/161572766-a437062f-ffc0-4e71-a08d-7a9c6aae69b4.png)

There should be a publisher name next to **Publisher:** so we will take a look at what's happening there.

**Comment by notshi** [comment]
Looks like the metadata wasn't updated from the Registry due to a typo but that's been fixed now and the Publisher name is now live.

![Screenshot from 2022-04-04 16-18-25](https://user-images.githubusercontent.com/1515961/161576447-438fc24d-7ea9-46e2-9868-1b5c05ef6d75.png)

I'm assuming the problem was that the publisher was unable to find themselves via the d-portal search page due to this.

**Comment by andreaszenasidi** [comment]
@notshi many thanks for looking into this. Yes, this is the activity I was looking for, but I couldn't find them before while I can see them now.
