### ISSUE TITLE
TEI tag vocabulary : import/use names?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#649]
Following on from https://github.com/devinit/D-Portal/issues/648

The filter search works perfectly: 

http://d-portal.org/ctrack.html?/tag@vocabulary=4#view=ended

On viewing a specific activity, the name for the relevant code isn't dsiplayed

![d-portal (16)](https://user-images.githubusercontent.com/1209944/226274635-c1e0c431-aced-4533-b36b-9507e136aad3.png)

I assume that this is because the code list isnt imported.  Would it be possible to do that?  It's available as a spreadsheet (which I _think_ the download will be a stable URL) via https://europa.eu/capacity4dev/joint-programming/documents/tei-codes-0

--------

An alternative could be to use the descriptive text that a publisher supplies (if at all).  In the case of this example, it is provided:

```
<tag code="TEI000" vocabulary="4">
<narrative xml:lang="EN">Generic code to be used when no attribution to a specific TEI</narrative>
</tag>
```

Thanks

**Comment by notshi** [comment]
Thanks for raising.

Narratives for `tag` element of non-embedded codelists should now be live on d-portal.

**Comment by stevieflow** [comment]
Amazing - thanks @notshi 

> Narratives for tag element of non-embedded codelists 

This is probably a new issue: but is that how d-portal generally treats these types of codes?  Thanks

**Comment by notshi** [comment]
Yes, when they are non-embedded codelists, we display the `narrative` element when we find them as we cannot look up the description otherwise.

**Comment by stevieflow** [comment]
Thanks @notshi
